import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url)),dist=path.join(root,'dist');
const stamp=execFileSync('git',['rev-parse','--short=12','HEAD'],{cwd:root,encoding:'utf8'}).trim();
fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});
for(const f of ['index.html','src','assets','audio','vendor','licenses','assetlib.js','surfaces.js','two-d'])fs.cpSync(path.join(root,f),path.join(dist,f),{recursive:true,filter:source=>!source.split(path.sep).some(p=>p.startsWith('_'))});
function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(/\.(html|js|css)$/.test(p)){let s=fs.readFileSync(p,'utf8');if(e.name==='index.html'){s=s.replace('<html lang="en">',`<html lang="en" data-build="${stamp}">`).replace('./src/style.css',`./src/style.css?v=${stamp}`).replace('./src/main.js',`./src/main.js?v=${stamp}`).replace('./vendor/three.module.js',`./vendor/three.module.js?v=${stamp}`);}s=s.replace(/((?:from|import)\s*\(?\s*['"])(\.{1,2}\/[^'"?]+\.js)(['"])/g,`$1$2?v=${stamp}$3`);fs.writeFileSync(p,s);}}}walk(dist);
fs.writeFileSync(path.join(dist,'.nojekyll'),'');fs.writeFileSync(path.join(dist,'build.json'),JSON.stringify({commit:stamp},null,2));console.log(`Built Fright House ${stamp} into dist/`);
