export const SCALE={x:28,y:14,ox:354,oy:92};
export const props=[{id:'counter',x:1,y:1,w:2.5,d:1.05},{id:'cabinet',x:5.7,y:.45,w:1.4,d:.65},{id:'bench',x:.45,y:4.2,w:.65,d:1.7}];
export function project(x,y,z=0){return {x:SCALE.ox+(x-y)*SCALE.x,y:SCALE.oy+(x+y)*SCALE.y-z};}
export function unproject(x,y){const a=(x-SCALE.ox)/SCALE.x,b=(y-SCALE.oy)/SCALE.y;return {x:(a+b)/2,y:(b-a)/2};}
export function initial(){return {x:4.25,y:5.3,room:'hall',time:0,walk:0,face:1,ticket:false,door:false,gate:false,turning:0,paused:false,light:true,phase:'playing'};}
export function floor(x,y,room){return room==='store'?x>=0&&x<=6&&y>=0&&y<=5:(x>=0&&x<=9&&y>=0&&y<=7)||(x>=6&&x<=9&&y>=7&&y<=11);}
export function blocked(x,y,s,r=.17){for(const [dx,dy]of [[-r,-r],[r,-r],[-r,r],[r,r]])if(!floor(x+dx,y+dy,s.room))return true;if(s.room==='store')return x>1-r&&x<2.5+r&&y<1.8+r;for(const p of props)if(x+r>p.x&&x-r<p.x+p.w&&y+r>p.y&&y-r<p.y+p.d)return true;const g=s.gate?{x:7.4,y:7.33,w:.22,d:2.84}:{x:6,y:8.65,w:3,d:.18};return x+r>g.x&&x-r<g.x+g.w&&y+r>g.y&&y-r<g.y+g.d;}
export function advance(s,sx,sy,dt){if(s.paused||s.phase!=='playing')return;const n=Math.hypot(sx,sy)||1,speed=78,dx=(sx/n/(2*SCALE.x)+sy/n/(2*SCALE.y))*speed*dt,dy=(sy/n/(2*SCALE.y)-sx/n/(2*SCALE.x))*speed*dt;const before={x:s.x,y:s.y};if(!blocked(s.x+dx,s.y,s))s.x+=dx;if(!blocked(s.x,s.y+dy,s))s.y+=dy;if(Math.hypot(s.x-before.x,s.y-before.y)>.001){s.walk+=dt*10;if(sx)s.face=Math.sign(sx);}s.time+=dt;}
export function targets(s){return s.room==='store'?[{id:'drawing',x:3.7,y:1.1,label:'READ · the child’s drawing'},{id:'back',x:5.5,y:3.1,label:'RETURN · ticket hall'}]:[{id:'ticket',x:2.9,y:2.55,label:s.ticket?'READ · admission ledger':'SEARCH · empty ticket counter'},{id:'door',x:8.25,y:3.3,label:s.door?'ENTER · red door':'OPEN · red door'},{id:'lever',x:5.4,y:6.1,label:'TURN · painted wall'},{id:'exit',x:8.1,y:10.45,label:'LEAVE · service corridor'}];}
export function nearest(s){return targets(s).find(o=>Math.hypot(s.x-o.x,s.y-o.y)<1.05)||null;}
export function path(s,x,y){const step=.4,k=(x,y)=>x+','+y,start=[Math.round(s.x/step),Math.round(s.y/step)],goal=[Math.round(x/step),Math.round(y/step)],queue=[start],prev=new Map([[k(...start),null]]);let end=null;for(let n=0;n<queue.length;n++){const [a,b]=queue[n];if(Math.hypot(a-goal[0],b-goal[1])<=1){end=[a,b];break;}for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const v=[a+dx,b+dy],id=k(...v);if(!prev.has(id)&&!blocked(v[0]*step,v[1]*step,s)){prev.set(id,[a,b]);queue.push(v);}}}if(!end)return [];const out=[];for(let p=end;p;p=prev.get(k(...p)))out.unshift({x:p[0]*step,y:p[1]*step});return out.slice(1);}
