import test from 'node:test';
import assert from 'node:assert/strict';
import {AREAS} from '../two-d/campaign/areas.js';
import {newCampaign,MAZE_AREAS,openDoor,enterDoor,finishFall,once,collectEvidence,restorePower,playRecording,answerPhone,advanceTime,checkpoint,retry,saveCampaign,loadCampaign,stepMaze} from '../two-d/campaign/state.js';
import {ACTIVE_NODES,POWER_GATES,pathfind,EVIDENCE} from '../src/model.js';
function maze(){const s=newCampaign();s.area='workshop';once(s,'workshop-disturbance');assert.ok(finishFall(s));s.story=null;return s;}
function walk(s,to){const nodes=pathfind(s.mazeNode,to,s.gates);assert.ok(nodes.length);for(const node of nodes.slice(1))assert.ok(stepMaze(s,node));}
test('20 unique areas and exact coverage of original 22 maze nodes',()=>{assert.equal(AREAS.length,20);assert.equal(new Set(AREAS.map(a=>a.id)).size,20);const nodes=Object.values(MAZE_AREAS).flat();assert.equal(nodes.length,22);assert.deepEqual(new Set(nodes),ACTIVE_NODES);});
test('closed doors hide rooms; entering and returning preserves progress',()=>{const s=newCampaign();assert.equal(enterDoor(s,'street-hall'),false);assert.ok(openDoor(s,'street-hall'));assert.deepEqual(s.revealedRooms,['street']);assert.ok(enterDoor(s,'street-hall'));assert.ok(s.revealedRooms.includes('ticket-hall'));assert.ok(enterDoor(s,'street-hall'));assert.equal(s.area,'street');assert.deepEqual(s.openedDoors,['street-hall']);assert.equal(openDoor(s,'toy-door'),false);});
test('evidence -> gates -> power -> recording -> phone; no early reveal',()=>{const s=maze();assert.equal(answerPhone(s),false);assert.equal(collectEvidence(s,'bag'),false);for(const e of EVIDENCE){walk(s,e.node);assert.ok(collectEvidence(s,e.id));assert.equal(collectEvidence(s,e.id),false);}walk(s,'4,4');s.gates=[...POWER_GATES];assert.ok(restorePower(s));assert.ok(playRecording(s));assert.ok(answerPhone(s));advanceTime(s,9);assert.equal(s.escapeSeconds,180);s.story=null;advanceTime(s,2);assert.equal(s.escapeSeconds,178);s.paused=true;advanceTime(s,5);assert.equal(s.escapeSeconds,178);});
test('checkpoint resets later scare state and preserves evidence, doors and gates',()=>{const s=maze();s.evidence=['bag'];s.openedDoors=['toy-door'];once(s,'earlier-scare');checkpoint(s);once(s,'later-scare');s.evidence.push('shoe');s.gates[0]=1-s.gates[0];const restored=retry(s);assert.deepEqual(restored.evidence,['bag']);assert.deepEqual(restored.events,['workshop-disturbance','earlier-scare']);assert.deepEqual(restored.openedDoors,['toy-door']);assert.notDeepEqual(restored.gates,s.gates);assert.equal(once(restored,'earlier-scare'),false);assert.equal(once(restored,'later-scare'),true);});
test('versioned saves round trip paused; malformed saves are rejected',()=>{const s=maze();checkpoint(s);const restored=loadCampaign(saveCampaign(s));assert.equal(restored.area,'landing');assert.equal(restored.paused,true);for(const raw of ['no','{}','{"version":99}',JSON.stringify({...s,gates:[0,9,1]})])assert.equal(loadCampaign(raw),null);});
