import test from 'node:test';import assert from 'node:assert/strict';
import {newRide,startRide,tickRide,cartPosition,RIDE_OBSTACLES,RIDE_LENGTH} from '../two-d/levels/finale-model.js';
const run=(s,n,input={})=>{for(let i=0;i<n;i++)tickRide(s,input,1/60);};
test('forward drive never reverses or turns; screen-left/right remain consistent',()=>{const s=newRide();startRide(s);run(s,20);const y=s.cart.y;run(s,30,{turn:'left'});assert.ok(cartPosition(s).x<170);run(s,40,{turn:'right'});assert.ok(cartPosition(s).x>310);assert.ok(s.cart.y<y);assert.equal(s.cart.dir,'up');assert.equal(s.turns,0);const distance=s.cart.distance;run(s,40);assert.ok(s.cart.distance>distance);assert.ok(Math.abs(s.cart.lane)<1);});
test('track lasts over a minute with 64 progressively harder hazard waves and a safe opening stretch',()=>{assert.ok(RIDE_LENGTH/230>58);assert.ok(RIDE_OBSTACLES.length>48);assert.equal(new Set(RIDE_OBSTACLES.map(o=>o.y)).size,64);assert.equal(new Set(RIDE_OBSTACLES.map(o=>o.kind)).size,5);const s=newRide();startRide(s);run(s,350);assert.equal(s.obstacleHits,0);assert.equal(s.spiderActive,false);run(s,20);assert.equal(s.spiderActive,true);s.paused=true;const frozen=structuredClone(s);run(s,120);assert.deepEqual(s,frozen);});
test('tall debris cannot be jumped; oil slows and reduces steering without removing cart integrity',()=>{for(const kind of ['rubble','oil']){const s=newRide();startRide(s);const o=RIDE_OBSTACLES.find(o=>o.kind===kind);s.cart.y=o.y;s.cart.lane=o.x-240;s.jumpZ=35;s.jumpAge=.4;tickRide(s,{turn:s.cart.lane<0?'left':s.cart.lane>0?'right':null},.01);if(kind==='rubble'){assert.equal(s.obstacleHits,1);assert.equal(s.integrity,2);}else{assert.equal(s.obstacleHits,0);s.jumpAge=s.jumpZ=0;tickRide(s,{},.01);assert.equal(s.obstacleHits,1);assert.equal(s.integrity,3);assert.ok(s.skid>1);}}});
test('cruise speed rises with elapsed ride time; later sections combine different hazards',()=>{const s=newRide();startRide(s);s.hitObstacles=RIDE_OBSTACLES.map(o=>o.id);s.exploded=RIDE_OBSTACLES.map(o=>o.id);run(s,120);const early=s.speed;s.rideAge=65;run(s,120);assert.ok(s.speed>early+60);const late=RIDE_OBSTACLES.filter(o=>o.id>=72);assert.ok(late.some(o=>o.kind==='barricade'&&late.some(p=>p.y===o.y&&p.kind==='rubble')));});
test('dynamite explodes once, damages its lane, and leaves the opposite track safe',()=>{const bomb=RIDE_OBSTACLES.find(o=>o.kind==='dynamite');for(const hit of [true,false]){const s=newRide();startRide(s);s.cart.y=bomb.y+65;s.cart.lane=hit?bomb.x-240:80;s.cart.laneTarget=s.cart.lane;tickRide(s,{turn:s.cart.lane<0?'left':'right'},.01);assert.equal(s.explosionCount,1);assert.equal(s.obstacleHits,hit?1:0);assert.ok(s.explosions.length);tickRide(s,{},.01);assert.equal(s.explosionCount,1);s.paused=true;const old=structuredClone(s);run(s,60);assert.deepEqual(s,old);}});
test('monster releases spiderlings; they approach from behind, can hit or be jumped',()=>{const s=newRide();startRide(s);s.rideAge=12;s.cart.y-=1800;s.spiderActive=true;s.spider.y=s.cart.y+190;s.broodClock=0;tickRide(s,{},.01);assert.equal(s.broods,1);assert.equal(s.spiderlings.length,1);const y=s.spiderlings[0].y;run(s,20);assert.ok(s.spiderlings[0].y<y);for(const jumping of [true,false]){const a=newRide();startRide(a);a.spiderActive=true;a.rideAge=12;a.spider.y=a.cart.y+190;a.spiderlings=[{x:240,y:a.cart.y+5,age:0,committed:true,targetX:240}];if(jumping){a.jumpAge=.4;a.jumpZ=40;}tickRide(a,{},.01);assert.equal(a.spiderlingHits,jumping?0:1);}});
