import assert from 'node:assert/strict';import fs from 'node:fs';const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/Users/poli/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-unsafe-swiftshader']}),page=await browser.newPage({viewport:{width:1200,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const state=()=>page.evaluate(()=>window.__GAME__),wait=ms=>page.waitForTimeout(ms),norm=a=>Math.atan2(Math.sin(a),Math.cos(a));
async function hold(key,ms){await page.keyboard.down(key);await wait(ms);await page.keyboard.up(key);}
async function face(x,z){for(let n=0;n<12;n++){const s=await state(),wanted=Math.atan2(-(x-s.pos[0]),-(z-s.pos[1])),d=norm(wanted-s.yaw);if(Math.abs(d)<.025)return;await hold(d>0?'ArrowLeft':'ArrowRight',Math.min(500,Math.abs(d)/1.75*1000));}}
async function go(x,z){for(let n=0;n<100;n++){const s=await state(),dist=Math.hypot(x-s.pos[0],z-s.pos[1]);if(dist<.12)return;await face(x,z);await hold('KeyW',Math.min(400,dist/2.15*1000));}throw new Error('stuck toward '+[x,z]+' at '+JSON.stringify((await state()).pos));}
async function use(id,x,z){await face(x,z);await wait(100);assert.equal((await state()).near,id);await page.keyboard.press('KeyE');await wait(250);}
async function snap(name){await page.screenshot({path:`validation/iterations/v09/${name}.png`});}
try{await page.goto('http://localhost:8089');await page.waitForFunction(()=>window.__READY__,{timeout:90000});await page.click('#begin');await snap('entrance');await go(0,-18);await use('turnstile',0,-16);await page.keyboard.press('KeyF');await go(0,-8);await use('foul-door',-1.6,-8);await wait(900);await snap('swarm');await go(-3,-8);await face(-5,-8);await snap('foul-room');await go(0,-8);await go(0,-2.7);await use('switch',1.55,-2);await go(-1.25,1.2);await go(-1.25,5.5);await go(0,9.8);await go(6.9,10);await snap('upper-floor');await go(7,8.1);await use('room-door',7,6.2);await wait(500);await snap('animatronic');await page.keyboard.press('Escape');const frozen=await state();await wait(600);assert.equal((await state()).entrance.age,frozen.entrance.age);await page.click('#resume');await go(7,1);await go(4,0);await face(0,0);await snap('gallery');await go(1.2,0);await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.__GAME__.phase==='investigate',{timeout:7000});await page.keyboard.up('KeyW');await snap('maze-arrival');assert.deepEqual(errors,[]);const final=await state();fs.writeFileSync('validation/iterations/v09/entrance.json',JSON.stringify({passed:true,errors,final},null,2));console.log('PASS full entrance, swarm, switch, barrel passage, moving floors, door scare, pause, fall into maze');}
catch(e){console.error(e);console.error(JSON.stringify(await state()));await snap('failure');process.exitCode=1;}finally{await browser.close();}
