import test from 'node:test';import assert from 'node:assert/strict';
import {SECRETS,readEvidence,collectEvidence,endingFor,resetEvidence} from '../two-d/campaign/secrets.js';
import {MACHINE_PAGES,takeInstruction,readInstructions} from '../two-d/campaign/instructions.js';
import {newEpilogue,tickEpilogue,bedroomPose,policePose,policeBeacon,POLICE_LINE,GIRL_LINE} from '../two-d/levels/epilogue-model.js';
import {newLibrary,libraryAction,tickLibrary,libraryPath,libraryBlocked} from '../two-d/levels/library-model.js';
const storage=()=>({value:new Map(),getItem(k){return this.value.get(k)},setItem(k,v){this.value.set(k,v)},removeItem(k){this.value.delete(k)}});
function tick(s,seconds,input={}){for(let i=0;i<Math.ceil(seconds*60);i++)tickEpilogue(s,input,1/60);}
test('only all eleven distinct optional items select arrest; instructions are separate',()=>{const db=storage();for(const item of SECRETS.slice(0,-1))assert.ok(collectEvidence(item.id,db));assert.equal(endingFor(readEvidence(db)),'escape');assert.equal(collectEvidence(SECRETS[0].id,db),false);assert.equal(collectEvidence('fake',db),false);for(const page of MACHINE_PAGES)takeInstruction(page.id,db);assert.equal(readInstructions(db).length,3);assert.equal(endingFor(readEvidence(db)),'escape');collectEvidence(SECRETS.at(-1).id,db);assert.equal(endingFor(readEvidence(db)),'arrest');resetEvidence(db);assert.equal(endingFor(readEvidence(db)),'escape');});
test('cart unload precedes playable alley; dawn increases, leaves lift and tape tears before branch',()=>{const s=newEpilogue();tick(s,3);assert.equal(s.phase,'alley');let last=0;for(let i=0;i<950&&s.phase==='alley';i++){tickEpilogue(s,{up:true},1/60);assert.ok(s.dawn>=last);last=s.dawn;}assert.equal(s.phase,'escape');assert.ok(s.tapeBroken);assert.ok(s.leafFlights>0);assert.ok(s.dawn>.99);});
test('arrest previews do not change storage; handcuffs release every collected item once, then escort and crouch',()=>{const s=newEpilogue([],'arrest');tick(s,3);assert.equal(s.notice,POLICE_LINE);tick(s,10.5);assert.equal(s.phase,'cuff');assert.equal(s.spilled.length,11);const ids=s.spilled.map(x=>x.id);tick(s,3);assert.deepEqual(s.spilled.map(x=>x.id),ids);tick(s,5);assert.equal(s.phase,'crouch');tick(s,4);assert.equal(s.phase,'police-drive');});
test('girl speaks before reaching; lamp switches off at contact, night and glowing eyes can follow',()=>{const s=newEpilogue([],'bedroom');tick(s,5);assert.equal(s.notice,GIRL_LINE);tick(s,12.3);assert.equal(bedroomPose(s).frame,6);assert.ok(s.lampOn);assert.equal(bedroomPose(s).seated,true);assert.equal(bedroomPose(s).facing,'down-right');assert.equal(bedroomPose(s).girlY,145);tick(s,1);assert.equal(s.lampOn,false);tick(s,2);assert.ok(bedroomPose(s).darkness>.9);s.paused=true;const old=structuredClone(s);tick(s,20);assert.deepEqual(s,old);});
test('library book falls into reachable aisle; collection is required before the exit can unlatch',()=>{const s=newLibrary(true);s.phase='chase';s.x=510;s.y=217;s.worm.x=400;s.worm.y=180;s.worm.cooldown=100;tickLibrary(s,{},.04);assert.ok(s.book.falling);for(let i=0;i<40;i++)tickLibrary(s,{},.025);assert.ok(s.book.landed);assert.ok(!libraryBlocked(s,s.book.x,s.book.y));assert.ok(libraryPath(s,s.book.x,s.book.y).length);s.x=1610;s.y=138;assert.equal(libraryAction(s,'exit'),'locked');s.x=s.book.x;s.y=s.book.y;assert.equal(libraryAction(s,'book'),'book');assert.equal(libraryAction(s,'book'),null);s.x=1610;s.y=138;assert.equal(libraryAction(s,'exit'),'exit');});

test('officer reacts after the spill, then escorts down toward the foreground car',()=>{const s=newEpilogue([],'arrest');tick(s,14.3);assert.equal(s.phase,'reaction');assert.equal(s.spilled.length,11);assert.equal(s.notice,'Where did you get these?');const snapshot=structuredClone(s);s.paused=true;tick(s,1);assert.equal(s.age,snapshot.age);s.paused=false;tick(s,3.2);assert.equal(s.phase,'escort');const first=policePose(s);tick(s,2);const next=policePose(s);assert.ok(next.escortX>first.escortX&&next.escortY>first.escortY);assert.ok(next.escortHeight>first.escortHeight);assert.notEqual(policeBeacon({time:0}),policeBeacon({time:.1}));});

test('escort goes around the rear bumper and along the pavement to the near-side door',()=>{const s=newEpilogue([],'arrest');s.phase='escort';for(let age=0;age<=4;age+=.02){s.age=age;const p=policePose(s);assert.ok(p.escortX+28<209||p.escortY>=330,`sprite entered car footprint at ${p.escortX},${p.escortY}`);}s.age=4;const end=policePose(s);assert.equal(end.escortX,300);assert.equal(end.escortY,334);});

test('both endings display their alternative-ending message before THE END',()=>{for(const branch of ['arrest','escape']){const s=newEpilogue([],branch==='arrest'?'arrest':'bedroom');s.phase=branch==='arrest'?'police-drive':'bedroom';s.age=branch==='arrest'?7.99:24.99;tick(s,.1);assert.equal(s.phase,'ending-hint');assert.match(s.notice,branch==='arrest'?/Alternative bad ending available/:/collect all the items dropped by the children/);const age=s.age;s.paused=true;tick(s,12);assert.equal(s.age,age);s.paused=false;tick(s,10);assert.equal(s.phase,branch==='arrest'?'arrest-end':'bedroom-end');}});
