import {safeFallTarget as safeTarget} from './fall-driver.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {newFall,fallBlackout,ENTRY,openFallDoor,tickFall,obstaclePose,FALL_OBSTACLES,SHAFT} from '../two-d/levels/fall-model.js';
const advance=(s,t,input={})=>{for(let i=0;i<t*60;i++)tickFall(s,input,1/60);};
test('door opens, detective walks through, then a full second of darkness precedes falling',()=>{const s=newFall();assert.ok(openFallDoor(s));assert.equal(openFallDoor(s),false);advance(s,1);assert.ok(s.door>0&&s.door<1);assert.equal(s.y,ENTRY.startY);advance(s,.3);assert.equal(s.phase,'walking');const before=s.y;advance(s,.6);assert.ok(s.y<before);assert.ok(s.moving&&s.walk>0);assert.equal(s.cameraY,0);advance(s,.9);assert.equal(s.phase,'blackout');assert.equal(s.y,ENTRY.thresholdY);assert.equal(fallBlackout(s),1);assert.equal(s.vy,0);s.paused=true;const frozen=structuredClone(s);advance(s,2);assert.deepEqual(s,frozen);s.paused=false;advance(s,.75);assert.equal(s.phase,'blackout');assert.equal(fallBlackout(s),1);advance(s,.3);assert.equal(s.phase,'fall');assert.ok(s.y>=260);assert.equal(s.door,1);advance(s,.4);assert.equal(fallBlackout(s),0);});
test('obstacles move, collisions hurt once during invulnerability, and pause freezes descent',()=>{const s=newFall();s.phase='fall';const o=FALL_OBSTACLES[0],p=obstaclePose(o,0);s.x=p.x;s.y=p.y+23;tickFall(s,{},.04);assert.equal(s.health,2);tickFall(s,{},.04);assert.equal(s.health,2);assert.notDeepEqual(obstaclePose(o,0),obstaclePose(o,1));s.paused=true;const before=structuredClone(s);advance(s,2,{left:true});assert.deepEqual(s,before);});
test('a navigable route reaches the 3D bone pile, releases dust once, and completes',()=>{const s=newFall();openFallDoor(s);for(let i=0;i<2400&&!['caught','complete'].includes(s.phase);i++){const x=safeTarget(s);tickFall(s,{left:s.x>x+3,right:s.x<x-3},1/60);}assert.equal(s.phase,'complete');assert.ok(s.health>0);assert.equal(s.y,SHAFT.landing);assert.equal(s.dustBurst,1);assert.ok(s.cameraY>2500);advance(s,7);assert.equal(s.dust.length,0);assert.equal(newFall().health,3);});
test('hanging webs snag once while falling stones hurt, move faster than the detective and pause safely',()=>{const web=FALL_OBSTACLES.find(o=>o.kind==='web'),s=newFall(),p=obstaclePose(web,0);s.phase='fall';s.x=p.x;s.y=p.y+23;s.vy=140;tickFall(s,{},.02);assert.equal(s.webHits.length,1);assert.ok(s.snag>0);assert.equal(s.health,3);const rock=newFall();rock.phase='fall';rock.age=3;rock.y=600;rock.stones.push({id:0,x:rock.x,y:rock.y-26,vx:0,vy:240,r:9,age:0});tickFall(rock,{},.02);assert.equal(rock.stoneHits,1);assert.equal(rock.health,2);rock.paused=true;const frozen=structuredClone(rock);advance(rock,1);assert.deepEqual(rock,frozen);assert.equal(newFall().stoneCount,0);});
test('stones originate above the view at varied positions and timings',()=>{const s=newFall();s.phase='fall';s.age=3;s.y=900;s.stoneClock=0;tickFall(s,{},.01);assert.equal(s.stoneCount,1);assert.ok(s.stones[0].y<s.y-200);assert.ok(s.stones[0].vy>s.vy);const x=s.stones[0].x;s.stoneClock=0;tickFall(s,{},.01);assert.notEqual(s.stones[1].x,x);});

test('fall camera keeps the actor near screen centre with space above for falling stones',()=>{const s=newFall();Object.assign(s,{phase:'fall',y:900,cameraY:700,vy:150,invincible:20});advance(s,2);const centre=s.y-s.cameraY-s.spriteHeight/2;assert.ok(centre>=165&&centre<=200,`screen centre ${centre}`);s.paused=true;const camera=s.cameraY;advance(s,1);assert.equal(s.cameraY,camera);});
