import {routeTurn,routeJump} from './finale-driver.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {newGallery,tickGallery,boardCart,galleryBlocked,newRide,startRide,tickRide,queueRideTurn,MAZE,SIZE,TILE,DIRS,START,EXIT,mazeRoute,mazeOpen,RIDE_OBSTACLES,escapePose,cartPosition,jumpRide} from '../two-d/levels/finale-model.js';
const advance=(s,t,input={})=>{for(let i=0;i<t*60;i++)(s.level===10?tickGallery:tickRide)(s,input,1/60);};
test('gallery connects bones to cart, fright dialogue appears, clothes fly then settle and boarding aligns',()=>{const s=newGallery();advance(s,1.7);for(let i=0;i<850&&s.y>204;i++)tickGallery(s,{up:true},1/60);assert.equal(s.phase,'flee');assert.equal(s.notice,'Are the bones from.....? I have to get out of here.');assert.ok(s.clothFlights>0);assert.ok(galleryBlocked(240,153));assert.ok(!galleryBlocked(240,205));assert.ok(boardCart(s));advance(s,1.8);assert.equal(s.phase,'complete');assert.ok(s.boarded);assert.equal(s.x,240);assert.equal(s.y,165);});
test('clothes and boarding freeze with pause; retry clears reactions',()=>{const s=newGallery();advance(s,1.7);s.x=s.clothes[0].x;s.y=s.clothes[0].y+20;advance(s,.1,{up:true});assert.ok(s.clothes[0].z>0);s.paused=true;const before=structuredClone(s);advance(s,2,{up:true});assert.deepEqual(s,before);s.paused=false;advance(s,1.5);assert.equal(s.clothes[0].z,0);assert.equal(newGallery().clothFlights,0);});
test('maze is connected, contains loops and routes to exterior',()=>{let cells=0,edges=0;for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(mazeOpen(c,r)){cells++;assert.ok(mazeRoute(START,{c,r}).length);for(const [dx,dy]of [[1,0],[0,1]])if(mazeOpen(c+dx,r+dy))edges++;}assert.ok(edges>=cells);assert.ok(mazeRoute(START,EXIT).length>20);});
test('queued turns complete chase with walls respected; pause and retry reset',()=>{const s=newRide();startRide(s);for(let i=0;i<10000&&!['complete','caught'].includes(s.phase);i++){const dir=routeTurn(s);if(dir)queueRideTurn(s,dir);tickRide(s,{jump:routeJump(s)},1/60);assert.ok(mazeOpen(Math.floor(s.cart.x/TILE),Math.floor(s.cart.y/TILE)));assert.ok(mazeOpen(Math.floor(s.spider.x/TILE),Math.floor(s.spider.y/TILE)));if(i===100){s.paused=true;const frozen=structuredClone(s);advance(s,1);assert.deepEqual(s,frozen);s.paused=false;}}assert.equal(s.phase,'complete');assert.equal(s.obstacleHits,0);assert.ok(s.spiderActive);assert.ok(s.turns>5);assert.ok(s.visited.length>20);assert.equal(newRide().phase,'ready');});
test('reverse works mid-segment; remaining stopped is caught rather than softlocked',()=>{const s=newRide();startRide(s);advance(s,.2);const a={...s.cart};queueRideTurn(s,'down');assert.equal(s.cart.x,a.x);assert.equal(s.cart.y,a.y);advance(s,.2);assert.ok(s.cart.y>=a.y);advance(s,9);assert.equal(s.phase,'caught');});

test('spider sleeps through the first stretch and obstacles damage the cart only once',()=>{const s=newRide();startRide(s);advance(s,5);assert.equal(s.spiderActive,false);advance(s,1.1);assert.equal(s.spiderActive,true);const o=RIDE_OBSTACLES[0],r=newRide();startRide(r);r.cart.c=o.c;r.cart.r=o.r;r.cart.x=o.x;r.cart.y=o.y;r.cart.dir=o.vertical?'up':'right';tickRide(r,{},1/60);assert.equal(r.obstacleHits,1);assert.equal(r.integrity,2);advance(r,.1);assert.equal(r.obstacleHits,1);});
test('sunrise ending approaches the far side and disappears into the car before it drives away; rain leaves temporary wet spots',()=>{const r=newRide();r.phase='escape';r.age=2;const a=escapePose(r);r.age=6.6;const b=escapePose(r);assert.ok(b.person.x>a.person.x);assert.equal(b.door,0);assert.equal(b.personVisible,false);r.age=12;const c=escapePose(r);assert.ok(c.carX>480&&!c.personVisible&&c.driving);const g=newGallery();advance(g,3);assert.ok(g.dripCount>0&&g.wet.length>0);g.paused=true;const before=structuredClone(g);advance(g,2);assert.deepEqual(g,before);});

test('crates burst, every obstacle slows, barricades are jumpable, cooldown and pause hold',()=>{const b=RIDE_OBSTACLES.find(o=>o.kind==='barricade');function atBarrier(){const s=newRide();startRide(s);Object.assign(s.cart,{c:b.c,r:b.r,x:b.x,y:b.y,dir:b.vertical?'up':'right'});return s;}const hit=atBarrier();tickRide(hit,{},.01);assert.equal(hit.obstacleHits,1);assert.equal(hit.speed,48);assert.equal(hit.fragments.length,18);assert.ok(hit.impact>1);const hop=atBarrier();assert.ok(jumpRide(hop));assert.equal(jumpRide(hop),false);hop.jumpAge=.35;tickRide(hop,{},.01);assert.equal(hop.obstacleHits,0);assert.ok(hop.jumpZ>23);hop.paused=true;const frozen=structuredClone(hop);advance(hop,1);assert.deepEqual(hop,frozen);});
test('ink can be dodged or jumped, obscures temporarily on impact and respects maze walls',()=>{function setup(){const s=newRide();startRide(s);s.ink.push({x:s.cart.x,y:s.cart.y-10,vx:0,vy:120,age:0});return s;}const hit=setup();tickRide(hit,{},.01);assert.equal(hit.inkHits,1);assert.ok(hit.inkObscure>3);assert.equal(hit.ink.length,0);hit.ink=[];advance(hit,4);assert.equal(hit.inkObscure,0);const jump=setup();jump.jumpAge=.4;tickRide(jump,{},.01);assert.equal(jump.inkHits,0);const miss=setup();miss.ink[0].x+=30;tickRide(miss,{},.01);assert.equal(miss.inkHits,0);const wall=setup();wall.ink=[{x:10,y:10,vx:200,vy:0,age:0}];tickRide(wall,{},.01);assert.equal(wall.ink.length,0);assert.equal(wall.inkHits,0);});
test('gallery drips are frequent and clothing movement stays light without blocking',()=>{const s=newGallery();advance(s,2);assert.ok(s.dripCount>=12);const c=s.clothes[0];s.x=c.x;s.y=c.y+15;advance(s,.15,{up:true});assert.ok(c.from);advance(s,.45);assert.ok(c.z>0&&c.z<=12);assert.ok(Math.hypot(c.to.x-c.from.x,c.to.y-c.from.y)<=21);});

test('active spider fires occasional aimed ink only across an open corridor',()=>{let c,r;outer:for(let y=1;y<SIZE-1;y++)for(let x=2;x<SIZE-2;x++)if(mazeOpen(x-1,y)&&mazeOpen(x,y)&&mazeOpen(x+1,y)){c=x;r=y;break outer;}const s=newRide();startRide(s);s.age=10;s.inkClock=0;Object.assign(s.cart,{c:c+1,r,x:(c+1.5)*TILE,y:(r+.5)*TILE,dir:'right'});Object.assign(s.spider,{c:c-1,r,x:(c-.5)*TILE,y:(r+.5)*TILE,dir:'right'});s.queued='right';tickRide(s,{},.01);assert.equal(s.inkShots,1);assert.equal(s.ink.length,1);assert.ok(s.inkClock>=3.2);assert.ok(s.ink[0].vx>0);});
test('gallery mixes shirts with trousers, socks, belts and glasses; glasses stay grounded',()=>{const s=newGallery(),kinds=new Set(s.clothes.map(c=>c.kind));for(const kind of [4,5,6,7])assert.ok(kinds.has(kind));advance(s,1.7);const glasses=s.clothes.find(c=>c.kind===7);s.x=glasses.x;s.y=glasses.y+14;advance(s,.1,{up:true});advance(s,.5);assert.equal(glasses.z,0);});
