import {chromium} from '/Users/poli/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const out='/Users/poli/Projects/fright-house/validation/isometric';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const results=[];
for(const mobile of [false,true]){const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1200,height:1000},hasTouch:mobile,isMobile:mobile});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.url()+':'+r.status());});await page.goto('http://localhost:8089/isometric/index.html');await page.locator('#begin').click();await page.screenshot({path:out+`/${mobile?'touch':'desktop'}-hall.png`,fullPage:true});
async function state(){return page.evaluate(()=>window.frightIso);}
async function clickWorld(x,y,z=0){const b=await page.locator('canvas').boundingBox(),px=(354+(x-y)*28)*b.width/720+b.x,py=(92+(x+y)*14-z)*b.height/470+b.y;if(mobile)await page.touchscreen.tap(px,py);else await page.mouse.click(px,py);}
async function target(x,y,id){await clickWorld(x,y,12);await page.waitForFunction(()=>window.frightIso.route===0,{},{timeout:18000});await page.waitForTimeout(150);const s=await state();if(id==='door'&&s.room==='store')return;if(id==='back'&&s.room==='hall')return;if(!s.dialog&&s.near!==id)throw Error('Failed target '+id+' '+JSON.stringify(s));}
const before=await state();if(mobile){await page.locator('[data-key="arrowright"]').dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch'});await page.waitForTimeout(250);await page.locator('[data-key="arrowright"]').dispatchEvent('pointerup',{pointerId:1,pointerType:'touch'});}else{await page.keyboard.down('ArrowRight');await page.waitForTimeout(250);await page.keyboard.up('ArrowRight');}const right=await state();if(right.screen.x<=before.screen.x||Math.abs(right.screen.y-before.screen.y)>.01)throw Error('Screen-right control incorrect');
await target(2.9,2.55,'ticket');if(!(await state()).ticket)throw Error('ticket not collected');await page.locator('#close').click();await target(8.25,3.3,'door');if(!(await state()).door)throw Error('door not opened');await page.locator('#close').click();if(mobile)await page.locator('#use').click();else await page.keyboard.press('e');if((await state()).room!=='store')throw Error('no hidden room');await page.screenshot({path:out+`/${mobile?'touch':'desktop'}-hidden-room.png`,fullPage:true});await target(3.7,1.1,'drawing');await page.locator('#close').click();await target(5.5,3.1,'back');if((await state()).room!=='hall')throw Error('no return');await target(5.4,6.1,'lever');if(!(await state()).gate)throw Error('gate not turned');await page.locator('#pause').click();const t=(await state()).time;await page.waitForTimeout(300);if((await state()).time!==t)throw Error('pause failed');await page.locator('#pause').click();await target(8.1,10.45,'exit');if((await state()).phase!=='escaped')throw Error('no escape');await page.locator('#reset').click();const reset=await state();if(reset.ticket||reset.gate||reset.door||reset.room!=='hall')throw Error('reset failed');results.push({mode:mobile?'touch':'keyboard-and-mouse',rightMovesRight:true,clue:true,hiddenRoom:true,wall:true,escaped:true,pause:true,reset:true,errors});await page.close();}fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));await browser.close();
