import test from 'node:test';import assert from 'node:assert/strict';import {LIBRARY_AISLE_SHELVES,newLibrary,libraryBlocked,libraryPath,libraryLineClear,libraryAction,answerLibraryPhone,closeLibraryPhone,tickLibrary} from '../two-d/levels/library-model.js';
const advance=(s,seconds,input={})=>{for(let i=0;i<Math.ceil(seconds*60);i++)tickLibrary(s,input,1/60);};
function walk(s,x,y){for(const p of libraryPath(s,x,y)){for(let n=0;n<100&&Math.hypot(s.x-p.x,s.y-p.y)>.2;n++)tickLibrary(s,{target:p},1/60);}return s;}
test('library furniture is solid and all interaction points have routes from entrance',()=>{const s=newLibrary();for(const [x,y]of [[185,190],[180,109],[440,151],[360,251],[35,188]])assert.ok(libraryBlocked(s,x,y));for(const [x,y]of [[148,218],[403,160],[1610,138]])assert.ok(libraryPath(s,x,y).length);assert.ok(libraryBlocked(s,1610,98));});
test('phone has a real pickup stage and cannot be skipped during the voice line',()=>{const s=newLibrary();s.x=148;s.y=218;assert.equal(libraryAction(s,'phone'),'phone');assert.ok(answerLibraryPhone(s));assert.equal(answerLibraryPhone(s),false);assert.equal(closeLibraryPhone(s),false);advance(s,5.3);assert.ok(closeLibraryPhone(s));assert.equal(s.phase,'search');assert.equal(s.phoneAnswered,true);advance(s,.6);assert.equal(s.receiver,0);});
test('the jar breaks once after the call, then the worm emerges before chasing',()=>{const s=newLibrary(true);s.x=404;s.y=177;advance(s,.05);assert.equal(s.phase,'breaking');advance(s,1.3);assert.equal(s.jar,1);assert.equal(s.worm.phase,'emerge');advance(s,1.1);assert.equal(s.phase,'chase');assert.equal(s.worm.phase,'crawl');});
test('bile has an aim warning, a fixed target and is stopped by the desk',()=>{const s=newLibrary(true);s.phase='chase';s.x=292;s.y=170;s.worm={...s.worm,x:350,y:170,phase:'crawl',cooldown:0};advance(s,.02);assert.equal(s.worm.phase,'aim');const aim={...s.worm.aim};s.y=225;advance(s,.8);assert.equal(s.shots.length,0);assert.deepEqual(s.worm.aim,aim);advance(s,.3);assert.equal(s.shotCount,1);assert.equal(s.worm.phase,'spit');assert.equal(libraryLineClear(s,{x:170,y:145},{x:170,y:229}),false);s.shots=[{x:170,y:162,vx:0,vy:145,age:0}];s.x=170;s.y=220;s.worm.cooldown=100;s.worm.x=400;s.worm.y=130;const health=s.health;advance(s,.6);assert.equal(s.health,health);assert.equal(s.shots.length,0);assert.ok(s.puddles.length);});
test('worm navigation goes around the desk and cannot capture through its footprint',()=>{const s=newLibrary(true);s.phase='chase';s.x=182;s.y=216;s.worm.x=182;s.worm.y=160;s.worm.phase='crawl';s.worm.cooldown=100;const route=libraryPath(s,s.x,s.y,s.worm,6);assert.ok(route.some(p=>p.x<113||p.x>261));for(let i=0;i<100;i++){tickLibrary(s,{},1/60);assert.equal(libraryBlocked(s,s.worm.x,s.worm.y,6),false);}assert.equal(s.health,3);});
test('pause freezes lights, call, jar, worm and projectiles; retry has fresh encounter state',()=>{const s=newLibrary(true);s.phase='chase';s.worm.phase='crawl';s.shots=[{x:300,y:220,vx:145,vy:0,age:0}];s.paused=true;const before=structuredClone(s);advance(s,3,{right:true});assert.deepEqual(s,before);const retry=newLibrary(true);assert.equal(retry.phase,'search');assert.equal(retry.jar,0);assert.equal(retry.health,3);assert.equal(retry.shots.length,0);assert.equal(retry.worm.phase,'hidden');});
test('escape requires the released latch, opening animation and walking through the door',()=>{const s=newLibrary(true);s.phase='chase';s.phaseAge=6.1;s.worm.phase='crawl';s.worm.x=80;s.worm.y=230;s.worm.cooldown=100;s.x=1610;s.y=138;assert.equal(libraryAction(s,'exit'),'exit');assert.equal(libraryBlocked(s,1610,98),true);assert.equal(s.openingExit,false);advance(s,1);assert.equal(s.exit,0);advance(s,2.3);assert.equal(s.exit,1);walk(s,1610,90);assert.equal(s.phase,'escaped');});

test('long library has a continuous route, solid doorway posts and a following camera',()=>{const s=newLibrary();assert.equal(s.spriteHeight,68);assert.ok(libraryBlocked(s,65,260));assert.ok(libraryBlocked(s,90,287));assert.ok(libraryPath(s,148,218).length);s.x=500;s.y=220;const route=libraryPath(s,1610,138);assert.ok(route.length>160);advance(s,.5);assert.ok(s.cameraX>200);assert.ok(libraryBlocked(s,670,190));assert.ok(libraryBlocked(s,900,268));});

test('the painted entrance opening cannot be used as vertical floor',()=>{const s=newLibrary();for(const point of [[75,235],[78,250],[65,270],[90,287]])assert.ok(libraryBlocked(s,...point),point.join(','));const route=libraryPath(s,148,218);assert.ok(route.length);assert.ok(route.some(p=>p.x>=72&&p.x<=90&&p.y>=273));walk(s,148,218);assert.ok(Math.hypot(s.x-148,s.y-218)<8);});
test('shelf specimens warn, fall, aim, shoot twice and freeze on pause',()=>{const s=newLibrary(true);s.phase='chase';s.x=775;s.y=225;s.worm.phase='hidden';s.worm.x=400;s.worm.y=150;s.worm.cooldown=100;const a=s.ambushes[0];advance(s,.1);assert.equal(a.phase,'rattle');advance(s,.95);assert.equal(a.phase,'fall');advance(s,.7);assert.equal(a.phase,'emerge');advance(s,.7);assert.equal(a.phase,'crawl');advance(s,.65);assert.equal(a.phase,'aim');assert.equal(a.volleys,0);const aim={...a.aim};s.x=804;s.paused=true;const before=structuredClone(s);advance(s,1);assert.deepEqual(s,before);s.paused=false;advance(s,1.2);assert.equal(a.volleys,1);assert.deepEqual(a.aim,aim);assert.ok(s.shots.some(p=>p.source===a.id));advance(s,7);assert.equal(a.volleys,2);assert.equal(newLibrary(true).ambushes.every(a=>a.phase==='sealed'),true);});

test('all freestanding library shelves allow walking behind them but block their bases',()=>{
 for(const o of LIBRARY_AISLE_SHELVES){const s=newLibrary(),backY=o.y-o.baseDepth-12,left=o.x-o.w/2-12,right=o.x+o.w/2+12;s.x=left;s.y=backY;
  const route=libraryPath(s,right,backY);assert.ok(route.length,o.id);assert.ok(route.every(p=>Math.abs(p.y-backY)<7),o.id+' must not detour around the front');
  advance(s,(right-left)/82,{right:true});assert.ok(s.x>=right-2,o.id+' keyboard passage');
  assert.ok(!libraryBlocked(s,o.x,backY),o.id+' rear aisle');assert.ok(libraryBlocked(s,o.x,o.y-8),o.id+' solid base');
  assert.ok(libraryLineClear(s,{x:left,y:backY},{x:right,y:backY},6),o.id+' creature route behind');
  assert.equal(libraryLineClear(s,{x:o.x,y:backY},{x:o.x,y:o.y+12},2),false,o.id+' bile cannot cross base');
  s.x=o.x;s.y=backY;advance(s,1,{down:true});assert.ok(s.y<=o.y-o.baseDepth-6+.01,o.id+' front collision');
 }
});
test('the static phone can close earlier and specimen 087 wakes without a precise shelf approach',()=>{const s=newLibrary();s.inspection=true;assert.ok(answerLibraryPhone(s));advance(s,1.7);assert.ok(closeLibraryPhone(s));advance(s,1.25);assert.equal(s.phase,'breaking');assert.ok(s.notice.includes('087'));});
