import test from 'node:test';import assert from 'node:assert/strict';import {newLibrary,libraryBlocked,libraryPath,libraryLineClear,libraryAction,answerLibraryPhone,closeLibraryPhone,tickLibrary} from '../two-d/levels/library-model.js';
const advance=(s,seconds,input={})=>{for(let i=0;i<Math.ceil(seconds*60);i++)tickLibrary(s,input,1/60);};
function walk(s,x,y){for(const p of libraryPath(s,x,y)){for(let n=0;n<100&&Math.hypot(s.x-p.x,s.y-p.y)>.2;n++)tickLibrary(s,{target:p},1/60);}return s;}
test('library furniture is solid and all interaction points have routes from entrance',()=>{const s=newLibrary();for(const [x,y]of [[185,190],[180,109],[440,140],[360,251],[35,165]])assert.ok(libraryBlocked(s,x,y));for(const [x,y]of [[148,218],[403,160],[1610,138]])assert.ok(libraryPath(s,x,y).length);assert.ok(libraryBlocked(s,1610,98));});
test('phone has a real pickup stage and cannot be skipped during the voice line',()=>{const s=newLibrary();s.x=148;s.y=218;assert.equal(libraryAction(s,'phone'),'phone');assert.ok(answerLibraryPhone(s));assert.equal(answerLibraryPhone(s),false);assert.equal(closeLibraryPhone(s),false);advance(s,5.3);assert.ok(closeLibraryPhone(s));assert.equal(s.phase,'search');assert.equal(s.phoneAnswered,true);});
test('the jar breaks once after the call, then the worm emerges before chasing',()=>{const s=newLibrary(true);s.x=404;s.y=177;advance(s,.05);assert.equal(s.phase,'breaking');advance(s,1.3);assert.equal(s.jar,1);assert.equal(s.worm.phase,'emerge');advance(s,1.1);assert.equal(s.phase,'chase');assert.equal(s.worm.phase,'crawl');});
test('bile has an aim warning, a fixed target and is stopped by the desk',()=>{const s=newLibrary(true);s.phase='chase';s.x=292;s.y=170;s.worm={...s.worm,x:350,y:170,phase:'crawl',cooldown:0};advance(s,.02);assert.equal(s.worm.phase,'aim');const aim={...s.worm.aim};s.y=225;advance(s,.8);assert.equal(s.shots.length,0);assert.deepEqual(s.worm.aim,aim);advance(s,.3);assert.equal(s.shotCount,1);assert.equal(s.worm.phase,'spit');assert.equal(libraryLineClear(s,{x:170,y:145},{x:170,y:229}),false);s.shots=[{x:170,y:162,vx:0,vy:145,age:0}];s.x=170;s.y=220;s.worm.cooldown=100;s.worm.x=400;s.worm.y=130;const health=s.health;advance(s,.6);assert.equal(s.health,health);assert.equal(s.shots.length,0);assert.ok(s.puddles.length);});
test('worm navigation goes around the desk and cannot capture through its footprint',()=>{const s=newLibrary(true);s.phase='chase';s.x=182;s.y=216;s.worm.x=182;s.worm.y=160;s.worm.phase='crawl';s.worm.cooldown=100;const route=libraryPath(s,s.x,s.y,s.worm,6);assert.ok(route.some(p=>p.x<113||p.x>261));for(let i=0;i<100;i++){tickLibrary(s,{},1/60);assert.equal(libraryBlocked(s,s.worm.x,s.worm.y,6),false);}assert.equal(s.health,3);});
test('pause freezes lights, call, jar, worm and projectiles; retry has fresh encounter state',()=>{const s=newLibrary(true);s.phase='chase';s.worm.phase='crawl';s.shots=[{x:300,y:220,vx:145,vy:0,age:0}];s.paused=true;const before=structuredClone(s);advance(s,3,{right:true});assert.deepEqual(s,before);const retry=newLibrary(true);assert.equal(retry.phase,'search');assert.equal(retry.jar,0);assert.equal(retry.health,3);assert.equal(retry.shots.length,0);assert.equal(retry.worm.phase,'hidden');});
test('escape requires the released latch, opening animation and walking through the door',()=>{const s=newLibrary(true);s.phase='chase';s.phaseAge=6.1;s.worm.phase='crawl';s.worm.x=80;s.worm.y=230;s.worm.cooldown=100;s.x=1610;s.y=138;assert.equal(libraryAction(s,'exit'),'exit');assert.equal(libraryBlocked(s,1610,98),true);assert.equal(s.openingExit,false);advance(s,1);assert.equal(s.exit,0);advance(s,2.3);assert.equal(s.exit,1);walk(s,1610,90);assert.equal(s.phase,'escaped');});

test('long library has a continuous route, solid doorway posts and a following camera',()=>{const s=newLibrary();assert.equal(s.spriteHeight,68);assert.ok(libraryBlocked(s,65,260));assert.ok(libraryBlocked(s,92,268));assert.ok(libraryPath(s,148,218).length);s.x=500;s.y=220;const route=libraryPath(s,1610,138);assert.ok(route.length>160);advance(s,.5);assert.ok(s.cameraX>200);assert.ok(libraryBlocked(s,670,160));assert.ok(libraryBlocked(s,900,235));});
