import test from 'node:test';import assert from 'node:assert/strict';
import {newPlatform,tickPlatform,platformAction,retryPlatform,answerPowerRiddle,pullPowerLever,closePowerInspection,STAIRS,FLOOR_Y,hazards,platforms} from '../two-d/levels/platform-model.js';
function steps(s,input,n){for(let i=0;i<n;i++)tickPlatform(s,input,1/60);}
test('solid scenery blocks walking and can be jumped over',()=>{const s=newPlatform();s.x=460;steps(s,{right:true},80);assert.equal(s.x,486);s.invincible=0;steps(s,{right:true,jump:true},40);assert.ok(s.x>529);assert.ok(s.y<690);});
test('closed gate cannot be walked through; switch opens it',()=>{const s=newPlatform();s.x=630;steps(s,{right:true},50);assert.equal(s.x,650);s.x=360;platformAction(s);answerPowerRiddle(s,'clock');pullPowerLever(s);steps(s,{},70);closePowerInspection(s);assert.ok(s.power);s.x=640;steps(s,{right:true},20);assert.ok(s.x>674);});
test('stairs are movement driven, stop on release, reverse, and allow descent',()=>{const s=newPlatform();s.x=786;steps(s,{up:true},1);assert.equal(s.stair,null);s.power=true;s.fuses=[0];steps(s,{up:true},40);assert.ok(s.stair);const y=s.y;steps(s,{},30);assert.equal(s.y,y);steps(s,{down:true},12);assert.ok(s.y>y);steps(s,{up:true},200);assert.equal(s.floor,1);assert.equal(s.checkpoint,1);assert.equal(s.y,493);steps(s,{down:true},220);assert.equal(s.floor,0);assert.equal(s.y,690);});
test('wall riddle gates the real lever; inspection freezes world and pause freezes lever',()=>{const s=newPlatform();s.x=360;platformAction(s);const t=s.time;assert.equal(pullPowerLever(s),false);answerPowerRiddle(s,'mirror');assert.equal(s.riddleSolved,false);answerPowerRiddle(s,'clock');assert.ok(s.riddleSolved);assert.equal(s.power,false);pullPowerLever(s);steps(s,{right:true},25);assert.ok(s.lever>0&&s.lever<1);assert.equal(s.time,t);assert.equal(s.x,360);s.paused=true;const angle=s.lever;steps(s,{},20);assert.equal(s.lever,angle);s.paused=false;steps(s,{},60);assert.equal(s.power,true);assert.equal(s.lever,1);closePowerInspection(s);assert.equal(s.inspection,null);retryPlatform(s);assert.equal(s.riddleSolved,false);assert.equal(s.power,false);});
test('mirror spiders warn, lock their landing, leap and reset without a pendulum',()=>{const s=newPlatform(2);s.x=230;steps(s,{},1);const p=s.spiders[0];assert.equal(p.phase,'warning');const target=p.target;s.x=150;steps(s,{},54);assert.equal(p.phase,'leap');assert.equal(p.target,target);const y=p.y;steps(s,{},15);assert.ok(p.y<y);assert.ok(hazards(s).every(h=>h.kind!=='pendulum'));retryPlatform(s);assert.ok(s.spiders.every(p=>p.phase==='hidden'));});
test('pause freezes hazards, stair, flash and motion together',()=>{const s=newPlatform(2);steps(s,{right:true},8);s.paused=true;const before=structuredClone(s),p=platforms(s),h=hazards(s);steps(s,{right:true,jump:true,flash:true},120);assert.deepEqual(s,before);assert.deepEqual(platforms(s),p);assert.deepEqual(hazards(s),h);});
test('hazards have warnings, collide at drawn positions, and retry clears damage',()=>{const s=newPlatform(1);assert.ok(hazards(s)[0].warning);s.floorTime=2;s.invincible=0;const h=hazards(s)[0];s.x=h.x;s.y=493;tickPlatform(s,{},1/60);assert.equal(s.health,2);s.cooldown=3;retryPlatform(s);assert.equal(s.health,3);assert.equal(s.floorTime,0);assert.equal(s.cooldown,0);assert.equal(s.floor,1);});
test('flash creates chase breathing room and has cooldown; exit finishes trial',()=>{const s=newPlatform(3);s.x=500;s.chaser=600;tickPlatform(s,{flash:true},1/60);assert.ok(s.chaser>690);const pos=s.chaser;tickPlatform(s,{flash:true},1/60);assert.ok(s.chaser<=pos);assert.ok(s.cooldown>3);s.x=145;platformAction(s);assert.equal(s.status,'escaped');});
test('authored route can be completed with riddle, lever, walking stairs and jumps',()=>{const s=newPlatform();let lastJump=-2;for(let frame=0;frame<12000&&s.status==='playing';frame++){if(s.floor===0&&!s.power&&Math.abs(s.x-360)<20){platformAction(s);answerPowerRiddle(s,'clock');pullPowerLever(s);}if(s.inspection&&s.power)closePowerInspection(s);if(s.floor===3&&s.x<166)platformAction(s);const fuseX=[450,410,480][s.floor],need=s.floor<3&&!s.fuses.includes(s.floor);let dir=need?Math.sign(fuseX-s.x):(s.floor===0||s.floor===2?1:-1);if(need&&Math.abs(s.x-fuseX)<10)dir=0;const stairX=STAIRS[s.floor]?.x,nearStair=!need&&s.floor<3&&Math.abs(s.x-stairX)<75;if(!need&&s.floor<3)dir=Math.abs(s.x-stairX)<10?0:Math.sign(stairX-s.x);const jump=s.time-lastJump>.82&&(!need||Math.abs(s.x-fuseX)>65)&&!s.stair&&!nearStair;if(jump)lastJump=s.time;tickPlatform(s,{left:dir<0,right:dir>0,up:!!s.stair||(nearStair&&Math.abs(s.x-stairX)<15),jump,flash:s.floor===3},1/60);if(s.status==='caught'){retryPlatform(s);lastJump=-2;}}assert.equal(s.status,'escaped',JSON.stringify(s));assert.equal(s.fuses.length,3);assert.equal(s.checkpoint,3);});
test('a spider landing hurts only at its locked target, so moving away avoids it',()=>{for(const [x,health]of [[230,2],[305,3]]){const s=newPlatform(2);s.x=x;s.invincible=0;Object.assign(s.spiders[0],{phase:'leap',age:.79,target:230});tickPlatform(s,{},1/60);assert.equal(s.health,health);}});
