import test from 'node:test';import assert from 'node:assert/strict';
import {newPlatform,tickPlatform,platformAction,retryPlatform,FLOOR_Y,hazards,platforms} from '../two-d/levels/platform-model.js';
function steps(s,input,n){for(let i=0;i<n;i++)tickPlatform(s,input,1/60);}
test('solid scenery blocks walking and can be jumped over',()=>{const s=newPlatform();s.x=460;steps(s,{right:true},80);assert.equal(s.x,486);s.invincible=0;steps(s,{right:true,jump:true},40);assert.ok(s.x>529);assert.ok(s.y<690);});
test('closed gate cannot be walked through; switch opens it',()=>{const s=newPlatform();s.x=630;steps(s,{right:true},50);assert.equal(s.x,650);s.x=360;platformAction(s);assert.ok(s.power);s.x=640;steps(s,{right:true},20);assert.ok(s.x>674);});
test('stairs require fuse and power, transition continuously, and save safe landing',()=>{const s=newPlatform();s.x=866;platformAction(s);assert.equal(s.stair,null);s.power=true;s.fuses=[0];platformAction(s);assert.ok(s.stair);const y=s.y;steps(s,{},25);assert.ok(s.y<y&&s.y>493);steps(s,{},50);assert.equal(s.floor,1);assert.equal(s.checkpoint,1);assert.equal(s.y,493);});
test('pause freezes hazards, stair, flash and motion together',()=>{const s=newPlatform(2);steps(s,{right:true},8);s.paused=true;const before=structuredClone(s),p=platforms(s),h=hazards(s);steps(s,{right:true,jump:true,flash:true},120);assert.deepEqual(s,before);assert.deepEqual(platforms(s),p);assert.deepEqual(hazards(s),h);});
test('hazards have warnings, collide at drawn positions, and retry clears damage',()=>{const s=newPlatform(1);assert.ok(hazards(s)[0].warning);s.floorTime=2;s.invincible=0;const h=hazards(s)[0];s.x=h.x;s.y=493;tickPlatform(s,{},1/60);assert.equal(s.health,2);s.cooldown=3;retryPlatform(s);assert.equal(s.health,3);assert.equal(s.floorTime,0);assert.equal(s.cooldown,0);assert.equal(s.floor,1);});
test('flash creates chase breathing room and has cooldown; exit finishes trial',()=>{const s=newPlatform(3);s.x=500;s.chaser=600;tickPlatform(s,{flash:true},1/60);assert.ok(s.chaser>690);const pos=s.chaser;tickPlatform(s,{flash:true},1/60);assert.ok(s.chaser<=pos);assert.ok(s.cooldown>3);s.x=145;platformAction(s);assert.equal(s.status,'escaped');});
test('authored route is completable with ordinary movement jumps and actions',()=>{const s=newPlatform();let jumping=false;for(let frame=0;frame<9000&&s.status==='playing';frame++){const t=frame/60;const direction=s.floor===0||s.floor===2?1:-1;if(s.floor===0&&!s.power&&Math.abs(s.x-360)<20)platformAction(s);if((s.floor===0&&s.x>851)||(s.floor===1&&s.x<85)||(s.floor===2&&s.x>875)||(s.floor===3&&s.x<166))platformAction(s);jumping=t% .82<.12;tickPlatform(s,{left:direction<0,right:direction>0,jump:jumping,flash:s.floor===3},1/60);if(s.status==='caught')retryPlatform(s);}assert.equal(s.status,'escaped');assert.equal(s.fuses.length,3);assert.equal(s.checkpoint,3);});
