import test from 'node:test';import assert from 'node:assert/strict';import {newPlatform,tickPlatform,retryPlatform} from '../two-d/levels/platform-model.js';import {tickAmbush,arrowHits,arrowPoint,balloonY,ambushHazards} from '../two-d/levels/platform-ambush.js';
const tick=(s,n,input={})=>{for(let i=0;i<n;i++)tickPlatform(s,input,1/60);};
test('archer warns, locks aim before firing, and launches from the lower floor',()=>{const s=newPlatform(1);s.x=700;for(let i=0;i<121;i++){s.time+=1/60;tickAmbush(s,1/60);}assert.equal(s.ambush.archer.phase,'aim');assert.equal(s.ambush.arrows.length,0);const target=s.ambush.archer.targetX;s.x=400;for(let i=0;i<70;i++){s.time+=1/60;tickAmbush(s,1/60);}const a=s.ambush.arrows[0];assert.ok(a);assert.equal(a.targetX,target);assert.ok(a.startY>493);assert.ok(arrowPoint(a,.5).y<a.startY);assert.equal(arrowPoint(a,1).x,target);});
test('bomb fuse gives time to move; staying hurts and retreating avoids the blast',()=>{for(const retreat of [false,true]){const s=newPlatform();s.power=true;s.x=578;s.invincible=0;tick(s,1);assert.equal(s.ambush.balloons[0].phase,'fuse');tick(s,36);assert.equal(s.health,3);if(retreat)s.x=740;tick(s,20);assert.equal(s.health,retreat?3:2);tick(s,30);assert.equal(s.ambush.balloons[0].phase,'spent');}});
test('fast arrows use swept collision instead of skipping over the player',()=>{const actor={x:300,y:493},h={x:360,y:475,sweep:{x:240,y:475}};assert.ok(arrowHits(h,actor));assert.equal(arrowHits({...h,y:430,sweep:{x:240,y:430}},actor),false);});
test('pause and retry freeze and reset arrow and bomb states',()=>{const s=newPlatform(1);s.x=520;tick(s,35);s.paused=true;const frozen=structuredClone(s.ambush);tick(s,120);assert.deepEqual(s.ambush,frozen);retryPlatform(s);assert.equal(s.ambush.arrows.length,0);assert.equal(s.ambush.archer.phase,'rest');assert.ok(s.ambush.balloons.every(b=>b.phase==='idle'));});

test('balloons rise and fall on every floor with a wide clearance window',()=>{for(let floor=0;floor<4;floor++){const heights=Array.from({length:300},(_,i)=>balloonY(floor,i/60));assert.ok(Math.max(...heights)-Math.min(...heights)>67);assert.ok(heights.some((y,i)=>i&&y<heights[i-1]));assert.ok(heights.some((y,i)=>i&&y>heights[i-1]));}});
test('walking under a raised balloon does not light its fuse or hurt the player',()=>{const s=newPlatform();s.power=true;s.invincible=0;s.time=Math.PI/1.4-.4;s.x=520;tick(s,55,{right:true});assert.ok(s.x>630);assert.equal(s.health,3);assert.equal(s.ambush.balloons[0].phase,'idle');});
test('airborne explosion stays at the balloon position instead of damaging the floor below',()=>{const s=newPlatform();s.power=true;s.invincible=0;s.x=578;s.time=Math.PI/1.4;const b=s.ambush.balloons[0];b.phase='fuse';b.age=.79;tick(s,1);assert.equal(b.phase,'blast');const y=b.y;assert.equal(ambushHazards(s).find(h=>h.kind==='balloon-bomb').y,y);tick(s,10);assert.equal(b.y,y);assert.equal(s.health,3);});
