import {chromium} from '/Users/poli/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const dir=process.env.CAPTURE_DIR||'validation/platform-v15';await fs.mkdir(dir,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});const results=[];
try{for(const touch of [false,true]){const context=await browser.newContext({viewport:touch?{width:430,height:932}:{width:1280,height:1000},hasTouch:touch,isMobile:touch});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://localhost:8089/two-d/level-3.html');await page.waitForFunction(()=>window.frightPlatform?.running);await page.waitForTimeout(250);await page.screenshot({path:`${dir}/${touch?'touch':'desktop'}-start.png`});
const state=()=>page.evaluate(()=>window.frightPlatform);
if(!touch){await page.keyboard.down('ArrowRight');await page.waitForFunction(()=>window.frightPlatform.x>152);await page.keyboard.up('ArrowRight');await page.keyboard.press('e');await page.locator('[data-answer=mirror]').click();assert.equal((await state()).power,false);assert.ok(await page.locator('#pull-lever').isDisabled());await page.locator('[data-answer=clock]').click();await page.screenshot({path:dir+'/power-closeup.png'});await page.locator('#pull-lever').click();await page.waitForFunction(()=>window.frightPlatform.power);await page.waitForFunction(()=>!frightPlatform.inspection);assert.ok((await state()).power);await page.keyboard.down('ArrowRight');await page.waitForFunction(()=>window.frightPlatform.x>438);await page.keyboard.up('ArrowRight');assert.ok((await state()).fuses.includes(0));await page.keyboard.down('ArrowRight');await page.waitForTimeout(650);await page.keyboard.up('ArrowRight');assert.equal(Math.round((await state()).x),486);await page.keyboard.down('ArrowRight');await page.keyboard.press('Space');await page.waitForTimeout(550);await page.keyboard.up('ArrowRight');assert.ok((await state()).x>529);await page.keyboard.down('ArrowRight');await page.waitForFunction(()=>!!window.frightPlatform.stair);await page.keyboard.up('ArrowRight');const stairY=(await state()).y;await page.waitForTimeout(200);assert.equal((await state()).y,stairY);await page.keyboard.down('ArrowUp');await page.waitForFunction(()=>window.frightPlatform.floor===1);await page.keyboard.up('ArrowUp');}
else{const b=page.locator('[data-input="right"]'),box=await b.boundingBox();await page.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);const session=await context.newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});await page.waitForTimeout(600);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok((await state()).x>140);await page.locator('#checkpoint').selectOption('1');await page.locator('#load').click();}
await page.locator('#pause').click();const before=await state();await page.waitForTimeout(250);const after=await state();assert.equal(after.time,before.time);assert.deepEqual(after.hazards,before.hazards);await page.locator('#pause').click();
for(const floor of [1,2,3]){await page.locator('#checkpoint').selectOption(String(floor));await page.locator('#load').click();await page.waitForTimeout(floor===1?1600:500);await page.screenshot({path:`${dir}/${touch?'touch':'desktop'}-floor-${floor+1}.png`});assert.equal((await state()).floor,floor);}
assert.equal(await page.locator('#flash').count(),0);await page.keyboard.press('f');assert.equal((await state()).cooldown,0);await page.locator('#retry').click();assert.equal((await state()).health,3);assert.equal((await state()).cooldown,0);await page.reload();await page.locator('#start:not([disabled])').waitFor();assert.equal((await state()).floor,3);assert.deepEqual(errors,[]);await page.waitForTimeout(150);assert.ok((await state()).render.drawCalls>0,'3D props must actually render');results.push({touch,errors,render:(await state()).render});await context.close();}await fs.writeFile(`${dir}/controls-results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(results));}finally{await browser.close();}
