import {chromium} from '/Users/poli/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const out='/Users/poli/Projects/fright-house/validation/props3d';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const results=[];
for(const mobile of [false,true]){
 const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1200,height:1000},hasTouch:mobile,isMobile:mobile});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:8089/two-d/index.html');await page.locator('#start:not([disabled])').click();const state=()=>page.evaluate(()=>window.fright2d);
 async function click(x,y){const r=await page.locator('#game').boundingBox();const a=r.x+x*r.width/480,b=r.y+y*r.height/360;if(mobile)await page.touchscreen.tap(a,b);else await page.mouse.click(a,b);}
 await click(82,238);await page.waitForFunction(()=>window.fright2d.toyInspection.active);await page.waitForTimeout(200);const a=await state();await page.screenshot({path:out+`/${mobile?'touch':'desktop'}-toy.png`,fullPage:true});const view=await page.locator('#toy-canvas').boundingBox();
 if(mobile){const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:view.x+view.width*.45,y:view.y+100}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:view.x+view.width*.65,y:view.y+130}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 else{await page.mouse.move(view.x+100,view.y+140);await page.mouse.down();await page.mouse.move(view.x+180,view.y+155);await page.mouse.up();}
 if((await state()).toyInspection.yaw===a.toyInspection.yaw)throw Error('Drag failed');await page.locator('#toy-reset').click();await page.locator('#toy-right').click();if((await state()).toyInspection.yaw===a.toyInspection.yaw)throw Error('Rotation failed');await page.locator('#toy-in').click();await page.locator('#toy-wind').click();await page.waitForTimeout(350);if(!(await state()).toyInspection.angle)throw Error('Winding failed');await page.locator('#toy-open').click();await page.waitForFunction(()=>window.fright2d.toy);await page.locator('#toy-up').click();await page.locator('#toy-up').click();await page.screenshot({path:out+`/${mobile?'touch':'desktop'}-open.png`,fullPage:true});if((await state()).time!==a.time)throw Error('World moved during inspection');await page.locator('#toy-close').click();await page.waitForFunction(()=>!window.fright2d.dialog);const b=await state();if(b.x!==a.x||b.y!==a.y)throw Error('Position changed');
 // Closing a modal must not swallow the next path or choose the nearby toy instead.
 await click(92,208);await page.waitForFunction(()=>window.fright2d.inspection.object==='notices');await page.locator('#inspection-close').click();await click(63,242);await page.waitForFunction(()=>window.fright2d.inspection.object==='newspaper');await page.locator('#inspection-close').click();await click(143,269);await page.waitForFunction(()=>window.fright2d.inspection.object==='ticket');await page.locator('#inspection-close').click();
 await click(335,189);await page.waitForFunction(()=>window.fright2d.stall);await page.locator('#continue').click();await page.reload();await page.locator('#resume').click();if(!(await state()).toy||(await state()).notes.length!==5)throw Error('Clue did not persist');
 await page.screenshot({path:out+`/${mobile?'touch':'desktop'}-street.png`,fullPage:true});await click(239,147);await page.waitForFunction(()=>window.fright2d.gateProgress===1);await click(239,132);await page.waitForFunction(()=>window.fright2d.phase==='complete');await page.locator('#retry').click();if((await state()).toy||(await state()).notes.length||(await state()).gate)throw Error('Restart not reset');if(errors.length)throw Error(errors.join('\n'));results.push({mobile,realGeometry:a.toyInspection.triangles,draws:a.toyInspection.draws,drag:true,rotate:true,zoom:true,wind:true,hinge:true,clue:true,persist:true,freeze:true,closeReturnsToPosition:true,allInspections:true,turnstile:true,completed:true,restart:true,errors});await page.close();
}fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));console.log(results);await browser.close();
