import {chromium} from '/Users/poli/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const base=process.env.GAME_URL||'http://127.0.0.1:8097/',b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{const p=await b.newPage({viewport:{width:1100,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base);await p.waitForURL('**/two-d/');await p.locator('#start:not([disabled])').waitFor();assert.equal(await p.locator('.test-return').isVisible(),false);assert.equal(await p.locator('.opening-logo').innerText(),'FRIGHT HOUSE');await p.locator('#start').click();await p.waitForFunction(()=>document.querySelector('#veil').hidden);assert.equal((await p.request.get(base+'two-d/test.html')).status(),404);
for(let level=2;level<=12;level++){await p.goto(base+`two-d/level-${level}.html`);await p.waitForFunction(()=>document.body.classList.contains('room-ready'));assert.equal(await p.locator('.test-return').isVisible(),false);assert.equal(await p.locator('#veil').isVisible(),false);}
await p.route(/\/epilogue\.js(?:\?.*)?$/,async r=>{const res=await r.fetch();await r.fulfill({response:res,body:await res.text()+`\nwindow.__hint=branch=>{s.branch=branch;s.phase='ending-hint';s.age=0;tickEpilogue(s,{},.02);render();};`});});
await p.goto(base+'two-d/level-12.html?preview=arrest');await p.waitForFunction(()=>frightEpilogue?.running);for(const branch of ['arrest','escape']){await p.evaluate(branch=>__hint(branch),branch);await p.waitForFunction(()=>frightDialogue.overlay);await p.keyboard.press('Enter');assert.match(await p.locator('#story-overlay .story-text').textContent(),branch==='arrest'?/Alternative bad ending available/:/collect all the items/);}
assert.deepEqual(errors,[]);console.log('Release root starts playable game; all 12 rooms load without test navigation; both ending messages display.');}finally{await b.close();}
