import {chromium} from '/Users/poli/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';const out='/Users/poli/Projects/fright-house/validation/street';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const results=[];
for(const mobile of [false,true]){const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1200,height:1060},hasTouch:mobile,isMobile:mobile});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.url()+':'+r.status());});await page.goto('http://localhost:8089/two-d/index.html');await page.locator('#start:not([disabled])').waitFor();await page.screenshot({path:out+`/${mobile?'touch':'desktop'}-intro.png`,fullPage:true});await page.locator('#start').click();await page.waitForTimeout(200);const state=()=>page.evaluate(()=>window.fright2d);
async function click(x,y){const b=await page.locator('canvas').boundingBox(),px=b.x+x*b.width/480,py=b.y+y*b.height/360;if(mobile)await page.touchscreen.tap(px,py);else await page.mouse.click(px,py);}
async function at(x,y,dialog=true){await click(x,y);await page.waitForFunction(()=>window.fright2d.route===0,{},{timeout:15000});await page.waitForTimeout(120);if(dialog&&!(await state()).dialog)throw Error('No interaction at '+x+','+y+' '+JSON.stringify(await state()));}
const a=await state();if(mobile){await page.locator('[data-key="ArrowRight"]').dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch'});await page.waitForTimeout(150);await page.locator('[data-key="ArrowRight"]').dispatchEvent('pointerup',{pointerId:1,pointerType:'touch'});}else{await page.keyboard.down('ArrowRight');await page.waitForTimeout(150);await page.keyboard.up('ArrowRight');}if((await state()).x<=a.x)throw Error('wrong direction');
await at(63,242);await page.screenshot({path:out+`/${mobile?'touch':'desktop'}-newspaper.png`,fullPage:true});if(!(await state()).newspaper)throw Error('newspaper missing');await page.locator('#continue').click();await at(92,208);await page.locator('#continue').click();await at(143,269);await page.locator('#continue').click();await at(335,189);await page.locator('#continue').click();const before=await state();await page.waitForTimeout(450);const animated=await state();if(before.wheelAngle===animated.wheelAngle||before.bulbs[0]===animated.bulbs[0])throw Error('animation static');await page.screenshot({path:out+`/${mobile?'touch':'desktop'}-street.png`,fullPage:true});await page.locator('#pause').click();const paused=await state();await page.waitForTimeout(300);const frozen=await state();if(paused.time!==frozen.time||paused.wheelAngle!==frozen.wheelAngle||!frozen.audio.ambience.paused)throw Error('pause did not freeze');await page.locator('#pause').click();
await page.reload();await page.locator('#resume').click();if((await state()).notes.length!==4)throw Error('resume lost notes');await at(239,147,false);await page.waitForTimeout(800);if(!(await state()).gate)throw Error('turnstile closed');await click(239,132);await page.waitForFunction(()=>window.fright2d.phase==='complete',{},{timeout:8000});await page.locator('#retry').click();const reset=await state();if(reset.notes.length||reset.gate||reset.newspaper||reset.time>.1)throw Error('reset failed');results.push({mode:mobile?'touch':'keyboard-and-mouse',notes:4,newspaper:true,animatedWheel:true,animatedLights:true,pause:true,resume:true,completed:true,restart:true,errors});await page.close();}
fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));await browser.close();
