import test from 'node:test';import assert from 'node:assert/strict';
import {newStore,retryStore,storeBlocked,storePath,storeAction,windStoreToy,tickStore,moveStore} from '../two-d/levels/toystore-model.js';
import {newHallReactions,tickHallReactions} from '../two-d/levels/hall-reactions.js';import {hallBlocked} from '../two-d/levels/hall-model.js';
const tick=(s,seconds)=>{for(let i=0;i<seconds*60;i++)tickStore(s,{},1/60);};
function walk(s,x,y){const route=storePath(s,x,y);assert.ok(route.length,'reachable destination');for(let i=0;route.length&&i<3000;i++){const p=route[0];if(Math.hypot(p.x-s.x,p.y-s.y)<.2)route.shift();else tickStore(s,{target:p},1/60);}assert.ok(s.phase==='escaped'||route.length===0,JSON.stringify({x:s.x,y:s.y,target:[x,y],next:route[0],phase:s.phase,health:s.health}));}
function wind(s){assert.equal(storeAction(s,'music'),'music');for(let i=0;i<3;i++)assert.ok(windStoreToy(s));}
test('storeroom entry, props and closed exit are solid; interactions have paths',()=>{const s=newStore();assert.equal(storePath(s,415,127).length,0);walk(s,72,224);storeAction(s,'entry');tick(s,1);walk(s,167,171);assert.equal(storeAction(s,'drawing'),'drawing');walk(s,415,127);assert.equal(storeAction(s,'music'),'music');s.inspection=false;assert.ok(storeBlocked(s,280,170));assert.ok(storeBlocked(s,388,97));assert.equal(storePath(s,388,78).length,0);});
test('three winds freeze inspection then dim, black out and wake 24 original toys',()=>{const s=newStore(true);assert.equal(s.toys.length,24);assert.equal(new Set(s.toys.map(t=>t.kind)).size,6);assert.ok(s.toys.every(t=>!storeBlocked(s,t.spawnX,t.spawnY,3)));storeAction(s,'music');tick(s,1);assert.equal(s.time,0);windStoreToy(s);windStoreToy(s);assert.equal(s.phase,'explore');windStoreToy(s);tick(s,1);assert.ok(s.lights>0&&s.lights<1);tick(s,1.25);assert.equal(s.phase,'blackout');assert.equal(s.lights,0);tick(s,2.5);assert.equal(s.phase,'chase');assert.ok(s.toys.every(t=>t.phase==='chasing'));assert.ok(s.toys.every(t=>!storeBlocked(s,t.x,t.y,3)));});
test('a route around the cage survives the swarm and escapes only through the released door',()=>{const s=newStore(true);wind(s);walk(s,360,222);walk(s,192,222);walk(s,192,114);walk(s,390,114);storeAction(s,'exit');assert.equal(s.openingExit,false);while(s.phaseAge<7.6)tickStore(s,{},1/60);assert.ok(s.phaseAge>=7.5);assert.equal(s.phase,'chase');assert.equal(storeAction(s),'exit');assert.ok(s.openingExit);tick(s,.7);walk(s,388,78);assert.equal(s.phase,'escaped');assert.ok(s.health>0);});
test('pause freezes all gameplay and retry resets toy, door, damage and light state',()=>{const s=newStore(true);wind(s);tick(s,4);s.paused=true;const before=structuredClone(s);tick(s,10);assert.deepEqual(s,before);const r=retryStore();assert.equal(r.health,3);assert.equal(r.lights,1);assert.equal(r.phase,'explore');assert.equal(r.turns,0);assert.equal(r.exit,0);assert.ok(r.toys.every(t=>t.phase==='asleep'));});
test('idle player can be caught; toys cannot cross furniture while pursuing',()=>{const s=newStore(true);wind(s);for(let i=0;i<1800&&s.phase!=='caught';i++){tickStore(s,{},1/60);assert.ok(s.toys.filter(t=>t.phase==='chasing').every(t=>!storeBlocked(s,t.x,t.y,3)));}assert.equal(s.phase,'caught');assert.equal(s.health,0);});
test('hall balloons pop only once and approaching the teddy animates it',()=>{const s={x:69,y:146,reactions:newHallReactions()};const events=[];for(let i=0;i<90;i++)events.push(...tickHallReactions(s,1/60));assert.equal(events.filter(e=>e==='pop').length,2);assert.ok(s.reactions.balloons.every(b=>b.popped));s.x=85;s.y=206;tickHallReactions(s,.02);assert.ok(s.reactions.toy.awake);assert.ok(s.reactions.toy.age>0);assert.ok(hallBlocked(65,215));assert.ok(newHallReactions().balloons.every(b=>!b.popped));});
test('hall rat escapes in either direction without passing through walls or the teddy',()=>{for(const x of [180,220]){const s={x,y:200,reactions:newHallReactions()},events=[];for(let i=0;i<600;i++){events.push(...tickHallReactions(s,1/60));assert.ok(!hallBlocked(s.reactions.rat.x,s.reactions.rat.y,2));}assert.equal(events.filter(e=>e==='scurry').length,1);assert.equal(s.reactions.rat.phase,'gone');}});
