import {chromium} from '/Users/poli/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {workshopBlocked} from '../two-d/levels/workshop-model.js';
const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const results=[];await fs.mkdir('validation/workshop-v28',{recursive:true});
try{for(const mobile of [false,true]){const c=await b.newContext({viewport:mobile?{width:430,height:932}:{width:1200,height:1000},hasTouch:mobile,isMobile:mobile}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8089/two-d/level-8.html');await p.locator('#start:not([disabled])').click();const state=()=>p.evaluate(()=>frightWorkshop);let held=[];
async function hold(want){for(const k of held)if(!want.includes(k)){if(mobile)await p.locator(`[data-key="${k}"]`).dispatchEvent('pointerup',{pointerId:1});else await p.keyboard.up('Arrow'+k[0].toUpperCase()+k.slice(1));}for(const k of want)if(!held.includes(k)){if(mobile)await p.locator(`[data-key="${k}"]`).dispatchEvent('pointerdown',{pointerId:1});else await p.keyboard.down('Arrow'+k[0].toUpperCase()+k.slice(1));}held=want;}
async function press(id,key){if(mobile)await p.locator(id).click();else await p.keyboard.press(key);}
await hold(['up']);await p.waitForFunction(()=>frightWorkshop.y<390,null,{timeout:7000});await hold([]);assert.ok((await state()).y<390);await p.locator('#pause').click();const frozen=(await state()).time;await p.waitForTimeout(130);assert.equal((await state()).time,frozen);await p.locator('#pause').click();
let s=await state();const box=await p.locator('#game').boundingBox(),x=box.x+(207-s.cameraX)*box.width/480,y=box.y+(384-s.cameraY)*box.height/360;if(mobile)await p.touchscreen.tap(x,y);else await p.mouse.click(x,y);await p.waitForFunction(()=>frightWorkshop.fork,null,{timeout:8000});await hold([]);
let previous='',evade={x:190,y:350},captured=new Set(),seenBolts=false;
for(let i=0;i<1900;i++){s=await state();assert.notEqual(s.phase,'caught','Boss caught player '+JSON.stringify({health:s.health,mode:s.boss.mode,x:s.x,y:s.y,shorts:s.shorts}));if(s.phase==='defeated')break;const boss=s.boss,dist=Math.hypot(s.x-boss.x,s.y-boss.y);seenBolts||=s.shots.length>0;let target=null;
if(s.phase==='fight'){if(boss.mode!==previous){if(['grab-warn','charge'].includes(boss.mode)){const angle=Math.atan2(s.y-boss.y,s.x-boss.x);const options=[1,-1].map(sign=>({x:s.x+Math.cos(angle+sign*Math.PI/2)*62,y:s.y+Math.sin(angle+sign*Math.PI/2)*62})).filter(t=>!workshopBlocked(s,t.x,t.y));evade=options[0]||{x:170,y:230};}previous=boss.mode;}
if(['cooldown','recover'].includes(boss.mode)){if(dist<58&&s.attackCooldown===0)await press('#action','e');else if(dist>=58)target=boss;}else if(['grab-warn','grab','charge','shoot'].includes(boss.mode)){target=evade;if(boss.mode==='grab'&&s.dodgeCooldown===0)await press('#dodge','Space');}else if(boss.mode==='pursue'&&dist<98){const t={x:s.x+(s.x-boss.x)/dist*28,y:s.y+(s.y-boss.y)/dist*28};if(!workshopBlocked(s,t.x,t.y))target=t;}
let want=[];if(target){if(Math.abs(target.x-s.x)>4)want.push(target.x>s.x?'right':'left');if(Math.abs(target.y-s.y)>4)want.push(target.y>s.y?'down':'up');}await hold(want);
if(boss.phase===2&&s.flashCooldown===0){const m=s.moths.find(m=>m.scared<=0&&Math.hypot(m.x-s.x,m.y-s.y)<155);if(m){const dx=m.x-s.x,dy=m.y-s.y,dir=Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up';await hold([dir]);await p.waitForTimeout(30);await press('#flash','f');}}
if((boss.mode==='recover'||boss.mode==='transform')&&!captured.has(boss.phase)){captured.add(boss.phase);await p.screenshot({path:`validation/workshop-v28/${mobile?'touch':'desktop'}-phase-${boss.phase}.png`});}}
await p.waitForTimeout(30);if(i===1899)throw Error('Fight timeout '+JSON.stringify(await state()));}
await hold([]);s=await state();assert.equal(s.boss.hp,0);assert.ok(s.shorts===4);assert.ok(s.casingHits>=8);assert.ok(s.casingHits%2===0);assert.ok(seenBolts);const preExit=s;let r=await p.locator('#game').boundingBox();await p.mouse.click(r.x+(640-s.cameraX)*r.width/480,r.y+(82-s.cameraY)*r.height/360); // If exit is offscreen, walk through the clear eastern aisle first.
await hold(['right']);await p.waitForFunction(()=>frightWorkshop.x>580,null,{timeout:7000});await hold(['up']);await p.waitForFunction(()=>frightWorkshop.phase==='escaped',null,{timeout:12000});await hold([]);await p.screenshot({path:`validation/workshop-v28/${mobile?'touch':'desktop'}-escaped.png`});await p.waitForURL('**/level-9.html?arrival=workshop');await p.waitForFunction(()=>window.frightFall?.running);assert.ok(['opening','walking','blackout','fall'].includes(await p.evaluate(()=>frightFall.phase)));assert.deepEqual(errors,[]);results.push({mobile,entrance:true,escaped:true,health:preExit.health,shorts:preExit.shorts,casingHits:preExit.casingHits,ambientMoths:preExit.moths.length,seenBolts,sprites:preExit.sprites,errors});await c.close();}}
finally{await b.close();await fs.writeFile('validation/workshop-v28/results.json',JSON.stringify(results,null,2));}console.log(results);
