import test from 'node:test';import assert from 'node:assert/strict';import {newWorkshop,tickWorkshop,attackWorkshop,flashWorkshop,dodgeWorkshop,workshopPath,workshopBlocked,retryWorkshop,workshopReveal,REVEAL} from '../two-d/levels/workshop-model.js';
const advance=(s,seconds,input={})=>{for(let i=0;i<seconds*60;i++)tickWorkshop(s,input,1/60);};
test('bottom entrance connects without a narrow collision seam; operating platform is solid',()=>{const s=newWorkshop(),r=workshopPath(s,207,384);assert.ok(r.length);for(let i=0;i<900&&r.length;i++){const p=r[0];if(Math.hypot(p.x-s.x,p.y-s.y)<.4)r.shift();else tickWorkshop(s,{target:p},1/60);}assert.ok(s.fork);assert.ok(!r.length);assert.ok(workshopBlocked(s,360,310));assert.ok(!workshopBlocked(s,360,455));});
test('floor opens, platform rises fully, then the lying animatronic wakes',()=>{const s=newWorkshop();advance(s,1);assert.deepEqual(workshopReveal(s),{opening:0,lift:0,offset:135});advance(s,2);assert.ok(workshopReveal(s).opening>0);assert.equal(workshopReveal(s).lift,0);assert.equal(s.boss.mode,'dormant');advance(s,3);assert.equal(workshopReveal(s).opening,1);assert.ok(workshopReveal(s).lift>0&&workshopReveal(s).lift<1);assert.equal(s.boss.mode,'dormant');assert.ok(workshopBlocked(s,360,260));s.paused=true;const before=workshopReveal(s);advance(s,2);assert.deepEqual(workshopReveal(s),before);s.paused=false;advance(s,3);assert.equal(workshopReveal(s).lift,1);assert.equal(s.boss.mode,'dormant');advance(s,.5);assert.equal(s.boss.mode,'awakening');advance(s,4.6);assert.equal(s.phase,'arrival');s.y=390;advance(s,.1);assert.equal(s.phase,'fight');assert.ok(s.boss.y>360);const retry=retryWorkshop(s);assert.equal(workshopReveal(retry).lift,0);});
function combat(){const s=newWorkshop();s.phase='fight';s.fork=true;s.x=190;s.y=360;s.boss.x=190;s.boss.y=320;s.boss.mode='cooldown';return s;}
function strike(s){assert.ok(attackWorkshop(s));advance(s,.2);}
test('two landed casing hits open contacts; a third strike damages and the sequence repeats in both phases',()=>{const s=combat();for(let cycle=0;cycle<4;cycle++){
 if(cycle){advance(s,s.boss.mode==='transform'?2.45:.85);s.x=s.boss.x;s.y=s.boss.y+40;}
 const hp=s.boss.hp;strike(s);assert.equal(s.boss.armorHits,1);assert.equal(s.boss.hp,hp);assert.notEqual(s.boss.mode,'recover');assert.ok(s.boss.impact>0);
 advance(s,.37);strike(s);assert.equal(s.boss.armorHits,2);assert.equal(s.boss.mode,'recover');assert.equal(s.boss.hp,hp);
 advance(s,.37);strike(s);assert.equal(s.boss.hp,hp-3);assert.equal(s.boss.armorHits,0);assert.equal(s.shorts,cycle+1);
 if(cycle===1){assert.equal(s.boss.phase,2);assert.equal(s.boss.mode,'transform');}
 }assert.equal(s.phase,'defeated');assert.equal(s.casingHits,8);assert.equal(s.shorts,4);});
test('misses, pending swings, cooldown and inactive boss do not grant casing hits',()=>{const s=combat();s.x=105;strike(s);assert.equal(s.casingHits,0);advance(s,.37);s.x=190;assert.ok(attackWorkshop(s));assert.equal(s.casingHits,0);assert.equal(attackWorkshop(s),false);advance(s,.2);assert.equal(s.casingHits,1);advance(s,.37);s.phase='arrival';strike(s);assert.equal(s.casingHits,1);});
test('boss attacks never open contacts automatically; two hits persist until the chest opens and reseals',()=>{for(const mode of ['grab','shoot']){const s=combat();s.boss.mode=mode;s.boss.targetX=s.x;s.boss.targetY=s.y;advance(s,.45);assert.equal(s.boss.mode,'cooldown');assert.equal(s.boss.armorHits,0);advance(s,1.9);assert.notEqual(s.boss.mode,'recover');}
 const s=combat();strike(s);advance(s,.37);strike(s);s.paused=true;const frozen=structuredClone(s);advance(s,4);assert.deepEqual(s,frozen);s.paused=false;advance(s,2.45);assert.equal(s.boss.mode,'reseal');assert.equal(s.boss.armorHits,0);assert.equal(s.boss.hp,12);advance(s,.3);assert.equal(s.boss.mode,'pursue');const retry=retryWorkshop(s);assert.equal(retry.casingHits,0);assert.equal(retry.boss.armorHits,0);});
test('moths orbit lamps harmlessly rather than pursuing the player',()=>{const s=newWorkshop();advance(s,2);const before=s.moths.map(m=>({...m}));s.x=before[0].x;s.y=before[0].y;advance(s,1);assert.equal(s.health,4);assert.notEqual(s.moths[0].x,before[0].x);assert.equal(s.moths.length,12);});
test('dust footprints persist, fade over time, and all encounter state freezes while paused',()=>{const s=newWorkshop();advance(s,.8,{up:true});assert.ok(s.footprints.length);s.paused=true;const before=structuredClone(s);advance(s,3,{up:true});assert.deepEqual(s,before);s.paused=false;s.phase='defeated';advance(s,14.1);assert.equal(s.footprints.length,0);});
test('defeat stops projectiles, unlocks exit, retry retains only the recovered fork',()=>{const s=newWorkshop();s.phase='fight';s.fork=s.checkpoint=true;s.boss.hp=3;s.boss.mode='recover';s.x=s.boss.x;s.y=s.boss.y+40;attackWorkshop(s);advance(s,.2);assert.equal(s.phase,'defeated');advance(s,2);assert.equal(s.exit,1);assert.equal(s.moths.length,12);const r=retryWorkshop(s);assert.equal(r.health,4);assert.equal(r.boss.hp,12);assert.ok(r.fork);assert.equal(r.shorts,0);});

test('phase two lightning varies timing and fires twelve radial directions',()=>{const s=newWorkshop();s.phase='fight';s.boss.phase=2;s.boss.mode='pursue';s.boss.x=190;s.boss.y=250;s.x=220;s.y=365;s.boss.zapWait=0;advance(s,.02);assert.equal(s.boss.mode,'charge');const first=s.boss.zapWait;advance(s,s.boss.chargeTime+.02);assert.equal(s.shots.length,12);assert.ok(s.shots.some(b=>b.dx>100));assert.ok(s.shots.some(b=>b.dx< -100));assert.ok(s.shots.some(b=>b.dy>100));assert.ok(s.shots.some(b=>b.dy< -100));s.boss.mode='pursue';s.boss.zapWait=0;advance(s,.02);assert.notEqual(s.boss.zapWait,first);});
