import {emphasizeItem} from './item-highlight.js';
import {outlineInspection} from './inspection-style.js';
import * as THREE from '../vendor/three.module.js';import launcherAsset from './assets/three/paint-barrel-launcher.js';import drumAsset from './assets/three/paint-drum.js';import gateAsset from './assets/three/barrel-gate.js';
export function createBarrelProps(){const renderer=new THREE.WebGLRenderer({alpha:true,antialias:false});renderer.setSize(480,360,false);renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(0,480,360,0,.1,2000);camera.position.z=1000;scene.add(new THREE.HemisphereLight(0xc6ad89,0x191c22,1.5));const light=new THREE.DirectionalLight(0xffb971,2.2);light.position.set(-200,400,700);scene.add(light);let calls=0,tris=0;
function place(body,x,y,w,h,rx=.25,ry=-.12){const g=new THREE.Group(),posed=new THREE.Group();posed.add(body);posed.rotation.set(rx,ry,0);g.add(posed);posed.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(posed),sz=box.getSize(new THREE.Vector3()),c=box.getCenter(new THREE.Vector3());posed.scale.set(w/sz.x,h/sz.y,h/sz.y);posed.position.set(-c.x*posed.scale.x,-box.min.y*posed.scale.y,0);g.position.set(x,360-y,0);scene.add(g);return {g,body,depth:y};}
const launcher=place(launcherAsset(THREE),370,239,123,140,.35,-.20),gate=place(gateAsset(THREE),638,182,95,87,0,0);
const drumPool=Array.from({length:8},()=>{const d=drumAsset(THREE),spin=new THREE.Group(),g=new THREE.Group();d.position.y=-.4415;spin.add(d);spin.rotation.z=Math.PI/2;g.add(spin);g.scale.setScalar(31);scene.add(g);return {g,spin,d};});
const supply=place(drumAsset(THREE),234,238,20,31,.3,.1);supply.body.userData.setColors(0x354e77,0x32b6ac);
function update(s,front){emphasizeItem(gate.body.userData.wheel,!s.turns,s.time);camera.position.x=s.cameraX;camera.position.y=-s.cameraY;camera.updateMatrixWorld();const visible=depth=>(depth>s.y)===front;launcher.g.visible=visible(launcher.depth);supply.g.visible=visible(supply.depth);gate.g.visible=visible(gate.depth);gate.body.userData.lift.position.y=s.gate*2.05;gate.body.userData.wheel.rotation.z=-s.wheelAngle;launcher.body.userData.warningMaterial.emissiveIntensity=.1;launcher.body.userData.ram.position.z=-.42+(((s.cycleAge>=.55&&s.cycleAge<.85)||(s.cycle%2===1&&s.cycleAge>=.94))?Math.sin((s.cycleAge-(s.cycleAge>=.94?.94:.55))/.3*Math.PI)*.26:0);launcher.body.userData.latch.rotation.z=s.cycleAge>=.55?1.2:0;
 drumPool.forEach((o,i)=>{const b=s.barrels[i];o.g.visible=!!b&&visible(b.y);if(!b)return;o.g.position.set(b.x,360-b.y+11,3);o.g.rotation.set(.3,0,-b.heading+.05);o.spin.rotation.y=b.roll;o.d.userData.setColors(b.shell,b.color);});}
return {draw(ctx,s,front){if(!front){calls=0;tris=0;}update(s,front);renderer.render(scene,camera);calls+=renderer.info.render.calls;tris+=renderer.info.render.triangles;ctx.drawImage(renderer.domElement,0,0);},snapshot(){return {launcher3D:true,drums3D:true,gate3D:true,drawCalls:calls,triangles:tris};}};}
export function createGateInspection(canvas){const r=new THREE.WebGLRenderer({canvas,alpha:true,antialias:false});r.setSize(192,140,false);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,384/280,.1,30),asset=outlineInspection(gateAsset(THREE));scene.add(asset);scene.add(new THREE.HemisphereLight(0xeee0aa,0x212323,2));const l=new THREE.DirectionalLight(0xffbf74,3);l.position.set(2,4,6);scene.add(l);let yaw=.2;canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);canvas.dataset.drag=String(e.clientX);};canvas.onpointermove=e=>{if(canvas.hasPointerCapture(e.pointerId)){yaw+=(e.clientX-Number(canvas.dataset.drag))*.006;canvas.dataset.drag=String(e.clientX);}};return {draw(s){asset.userData.wheel.rotation.z=-s.wheelAngle;asset.userData.lift.position.y=s.turns>=1?1.8:0;camera.position.set(1.2+Math.sin(yaw)*2.8,1.6,Math.cos(yaw)*2.8);camera.lookAt(1,1.35,0);r.render(scene,camera);}};}
