import {drawSecretsOverlay} from './secrets-ui.js';
import {createRoomMusic} from './room-music.js';
import {enterRoom,leaveRoom} from './room-flow.js';
import {newBarrelRun,barrelRetry,barrelPath,barrelAction,turnBarrelWheel,tickBarrelRun,WHEEL} from './levels/barrel-model.js';import {createBarrelProps,createGateInspection} from './barrel-props.js';import {drawPlayer} from './levels/temporary-player.js';import {newCampaign,loadCampaign,saveCampaign,remember} from './campaign/state.js';
const $=q=>document.querySelector(q),canvas=$('#game'),ctx=canvas.getContext('2d'),bg=new Image(),keys=new Set(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;ctx.imageSmoothingEnabled=false;let s=newBarrelRun(),running=false,last=performance.now(),props,inspector,route=[],pending=false,muted=false,ac,previousLaunch=0,previousHits=0,previousWarning=false;const ambience=createRoomMusic(6);ambience.loop=true;ambience.volume=.13;
function tone(f,d=.2,type='triangle',volume=.04){if(muted||s.paused)return;try{ac||=new AudioContext();ac.resume();const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(f,ac.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(25,f*.4),ac.currentTime+d);g.gain.setValueAtTime(volume,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+d);}catch{}}
function release(){keys.clear();route=[];pending=false;}
function closeInspection(){s.inspection=false;$('#gate-inspection').close();release();canvas.focus();}
function start(retry=false){const next=retry?barrelRetry(s):newBarrelRun();closeInspection();s=next;running=true;previousLaunch=0;previousHits=0;previousWarning=false;$('#veil').hidden=true;$('#next-level').hidden=true;$('#pause').textContent='PAUSE';release();canvas.focus();if(!muted)ambience.play().catch(()=>{});}
function pause(force){if(!running||s.phase!=='explore')return;s.paused=force??!s.paused;release();$('#pause').textContent=s.paused?'RESUME':'PAUSE';if(s.paused){ambience.pause();ac?.suspend();}else{ac?.resume();if(!muted)ambience.play().catch(()=>{});}}
function inspect(){if(!running||s.paused)return;if(barrelAction(s)){release();$('#gate-inspection').showModal();$('#turn-wheel').focus();}}
$('#start').onclick=()=>start();$('#restart').onclick=()=>start();$('#retry').onclick=()=>start(true);$('#pause').onclick=()=>pause();$('#action').onclick=inspect;$('#close-inspection').onclick=closeInspection;$('#gate-inspection').addEventListener('cancel',e=>{e.preventDefault();closeInspection();});$('#turn-wheel').onclick=()=>{if(turnBarrelWheel(s)){tone(165,.25,'sawtooth',.025);if(s.turns>=1)closeInspection();}};$('#sound').onclick=()=>{muted=!muted;ambience.muted=muted;if(muted)ac?.suspend();else if(!s.paused)ac?.resume();$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';};
const mapping={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};
window.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(s.inspection){if(k==='e')closeInspection();return;}if(mapping[k]||k===' ')e.preventDefault();if(e.repeat)return;if(k==='Escape')pause();else if(k==='e'||k===' ')inspect();else if(mapping[k]){keys.add(mapping[k]);route=[];pending=false;}});window.addEventListener('keyup',e=>keys.delete(mapping[e.key.length===1?e.key.toLowerCase():e.key]));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);route=[];pending=false;};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));}
canvas.onpointerdown=e=>{if(!running||s.paused||s.inspection||s.phase!=='explore')return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*480/r.width+s.cameraX,y=(e.clientY-r.top)*360/r.height+s.cameraY;pending=(Math.hypot(x-WHEEL.x,y-WHEEL.y)<26||(x>663&&x<696&&y>118&&y<184))&&s.gate<.95;const aim=pending?WHEEL:{x,y};route=barrelPath(s,aim.x,aim.y);if(pending&&Math.hypot(s.x-WHEEL.x,s.y-WHEEL.y)<WHEEL.r){pending=false;inspect();}};
function glow(x,y,r,color,alpha){ctx.save();ctx.globalAlpha=alpha;const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,2*r,2*r);ctx.restore();}
function paint(){for(const p of s.splashes){ctx.save();ctx.globalAlpha=Math.min(1,16-p.age)*.85;ctx.fillStyle=p.color;for(let i=0;i<9;i++){const a=i*2.4+p.seed,r=i*1.5;ctx.beginPath();ctx.ellipse(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r*.4,6+i%3,2+i%2,0,0,7);ctx.fill();}if(p.age<.85)for(let i=0;i<24;i++){const a=i*2.4+p.seed,t=p.age,x=p.x+Math.cos(a)*t*(17+i%6*8),y=p.y+Math.sin(a)*t*19-Math.sin(t/.85*Math.PI)*(10+i%4*4);ctx.fillRect(x,y,2,2);}ctx.restore();}}
function render(){ctx.clearRect(0,0,480,360);ctx.save();ctx.translate(-s.cameraX,-s.cameraY);ctx.drawImage(bg,0,0,720,480);paint();for(const b of s.barrels){ctx.fillStyle='#09090bbb';ctx.beginPath();ctx.ellipse(b.x,b.y+1,15,4,0,0,7);ctx.fill();}ctx.restore();props.draw(ctx,s,false);ctx.save();ctx.translate(-s.cameraX,-s.cameraY);if(running){ctx.globalAlpha=s.invincible&&Math.floor(s.time*12)%2===0?.5:1;drawPlayer(ctx,s,s.moving&&!s.paused&&!s.inspection);ctx.globalAlpha=1;}ctx.restore();props.draw(ctx,s,true);ctx.save();ctx.translate(-s.cameraX,-s.cameraY);for(const [x,y]of [[105,269],[467,108],[560,132],[595,57],[684,55]])glow(x,y,28,'#e8a74c',.15+Math.sin(s.time*1.7+x)*.015);glow(319,72,34,'#a52614',.07);
ctx.globalAlpha=.05;ctx.fillStyle='#d2c6ae';for(let i=0;i<5;i++){ctx.beginPath();ctx.ellipse(180+i*105+Math.sin(reduced?0:s.time*.15+i)*20,307-i*16,65,8,0,0,7);ctx.fill();}ctx.restore();
if(s.paint>0){ctx.save();ctx.globalAlpha=s.paint*.08;ctx.fillStyle=s.paintColor;ctx.fillRect(0,0,480,360);ctx.restore();}if(s.paused){ctx.fillStyle='#020507b8';ctx.fillRect(0,0,480,360);ctx.fillStyle='#e0c59e';ctx.font='16px monospace';ctx.fillText('PAUSED',207,178);}
$('#health').textContent='● '.repeat(Math.max(0,s.health))+'○ '.repeat(3-Math.max(0,s.health));$('#warning').textContent=s.active?'MACHINERY RUNNING':'MACHINERY IDLE';$('#gate-status').textContent=s.gate>=.95?'GATE OPEN':s.turns>=1?'GATE RISING':'GATE LOCKED';$('#notice').textContent=s.noticeAge>0?s.notice:' ';$('#hint').textContent=!s.paused&&!s.inspection&&s.gate<.95&&Math.hypot(s.x-WHEEL.x,s.y-WHEEL.y)<WHEEL.r?'E · EXAMINE HANDWHEEL':'';$('#objective').textContent=s.gate>=.95?'Climb the stairs beyond the gate.':'Dodge the steel drums. Reach the brass gate wheel at the far end.';
if(s.inspection){inspector.draw(s);$('#ratchet').textContent=s.turns?'CHAIN RELEASED':'CHAIN LOCKED';$('#turn-wheel').disabled=s.turns>=1||s.paused;$('#wheel-result').hidden=s.turns<1;$('#wheel-result').textContent=s.turns>=1?'The chain is free. Return to the passage and climb the stairs.':'';}}
function complete(){release();ambience.pause();$('#veil').hidden=false;const won=s.phase==='escaped';$('#veil h1').textContent=won?'ABOVE THE BARRELS':'NO MORE ROLLING AROUND';$('#intro').textContent=won?'The gate drops behind you. A child’s muddy footprints continue toward the moving-floor mezzanine. Level 6 complete.':'The drums keep coming. Find a gap between bursts and step out of their path.';$('#start').textContent=won?'PLAY AGAIN':'RETRY';$('#start').onclick=()=>start(!won);$('#next-level').hidden=!won;if(won){leaveRoom('./level-7.html?arrival=barrels');let c;try{c=loadCampaign(localStorage.getItem('fright-house-2d-campaign-v1'));}catch{}c||=newCampaign();remember(c,'barrel-run','The maintenance passage is still running. Paint drums fire from a roller rack. A child’s footprints lead up to the mezzanine.');c.area='barrel-passage';try{localStorage.setItem('fright-house-2d-campaign-v1',saveCampaign(c));localStorage.setItem('fright-house-barrel-run-v1','complete');}catch{}}}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running){let input=Object.fromEntries([...keys].map(k=>[k,true]));if(!keys.size&&route.length&&!s.paused&&!s.inspection){const p=route[0];if(Math.hypot(p.x-s.x,p.y-s.y)<.25)route.shift();else input={target:p};}tickBarrelRun(s,input,dt);if(!route.length&&pending&&!s.paused){pending=false;inspect();}if(s.warning&&!previousWarning)tone(420,.16,'triangle',.02);previousWarning=s.warning;if(s.launchCount!==previousLaunch){tone(90,.3,'sawtooth',.035);previousLaunch=s.launchCount;}if(s.hitCount!==previousHits){tone(170,.4,'triangle',.07);previousHits=s.hitCount;}if(s.phase!=='explore'&&$('#veil').hidden)complete();}if(props&&bg.complete)render();drawSecretsOverlay();requestAnimationFrame(frame);}
bg.onload=()=>{try{props=createBarrelProps();inspector=createGateInspection($('#gate-view'));$('#start').disabled=false;$('#start').textContent='ENTER THE PASSAGE';enterRoom(()=>start(),()=>{if(!s.paused&&!muted){ambience.play().catch(()=>{});ac?.resume();}});}catch(e){$('#intro').textContent='The 3D passage could not load. Enable WebGL and reload.';console.error(e);}};bg.onerror=()=>$('#intro').textContent='The artwork could not load. Please reload.';bg.src='./assets/barrel-passage-clean.png';Object.defineProperty(window,'frightBarrelRun',{get:()=>({...structuredClone(s),running,route:route.length,render:props?.snapshot()})});requestAnimationFrame(frame);
