import {requestGameFrame,configureTelemetry,resetTelemetryMotion} from './runtime-telemetry.js';
import {createAlleySound} from './alley-sound.js';
import {drawPixelTitle} from './pixel-title.js';
import {enterRoom} from './room-flow.js';
import {newEpilogue,tickEpilogue,bedroomPose,policePose,policeBeacon,ALLEY,ARREST,BEDROOM} from './levels/epilogue-model.js';
import {readEvidence,SECRETS} from './campaign/secrets.js';
import {drawEvidence} from './evidence-icons.js';
import {drawPlayer} from './levels/temporary-player.js';
import {loadEndingSheet,drawEndingSprite} from './ending-sprites.js';
import {createEpilogueProps} from './epilogue-props.js';
import {createPoliceSiren} from './police-siren.js';
import {createSunriseMusic} from './sunrise-music.js';
const $=q=>document.querySelector(q),canvas=$('#game'),ctx=canvas.getContext('2d'),preview=new URLSearchParams(location.search).get('preview')||'',keys=new Set();let s,props,art,running=false,last=performance.now(),target=null,ac,master,music,siren,alleySound,muted=false,musicOn=false,lastLamp=true,lastCuff=false,handheldBeat=-1,handheldNotes=0;const handheldVoices=new Set();
function unlock(){if(!ac){ac=new AudioContext();master=ac.createGain();master.gain.value=muted?0:.3;master.connect(ac.destination);music=createSunriseMusic(ac,master);siren=createPoliceSiren(ac,master);alleySound=createAlleySound(ac,master);}if(!s?.paused)ac.resume();}
function fx(hz,seconds,volume=.2){if(!ac||ac.state!=='running')return;const o=ac.createOscillator(),g=ac.createGain();o.type='triangle';o.frequency.setValueAtTime(hz,ac.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,hz/4),ac.currentTime+seconds);g.gain.setValueAtTime(volume,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+seconds);o.connect(g).connect(master);o.start();o.stop(ac.currentTime+seconds);o.onended=()=>{o.disconnect();g.disconnect();};}
function stopHandheld(){for(const voice of handheldVoices){try{voice.stop();}catch{}}handheldVoices.clear();}
function handheldSound(){if(s.phase!=='bedroom'||s.age>=13||muted){stopHandheld();return;}if(!ac||ac.state!=='running')return;const beat=Math.floor(s.age/.22);if(beat===handheldBeat)return;handheldBeat=beat;const melody=[659,784,988,784,587,740,880,740,523,659,784,659,587,740,880,1047];function note(frequency,duration,volume,type){const o=ac.createOscillator(),g=ac.createGain(),filter=ac.createBiquadFilter();o.type=type;o.frequency.value=frequency;filter.type='lowpass';filter.frequency.value=2600;g.gain.setValueAtTime(.001,ac.currentTime);g.gain.linearRampToValueAtTime(volume,ac.currentTime+.004);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(filter).connect(g).connect(master);handheldVoices.add(o);o.start();o.stop(ac.currentTime+duration);o.onended=()=>{handheldVoices.delete(o);o.disconnect();filter.disconnect();g.disconnect();};handheldNotes++;}note(melody[beat%melody.length],.16,.095,'square');if(beat%4===0)note(melody[beat%melody.length]/4,.18,.13,'triangle');if(beat%8===5)note(2093,.045,.065,'square');}
function start(){resetTelemetryMotion();alleySound?.reset();siren?.stop();stopHandheld();handheldBeat=-1;handheldNotes=0;s=newEpilogue(readEvidence(),preview);running=true;target=null;keys.clear();lastLamp=true;lastCuff=false;music?.stop();musicOn=false;$('#veil').hidden=true;$('#pause').textContent='PAUSE';unlock();canvas.focus();}
function pause(force){if(!s)return;s.paused=force??!s.paused;keys.clear();target=null;$('#pause').textContent=s.paused?'RESUME':'PAUSE';if(s.paused)ac?.suspend();else unlock();}
$('#start').onclick=start;$('#retry').onclick=start;$('#restart').onclick=start;$('#pause').onclick=()=>pause();$('#sound').onclick=()=>{muted=!muted;if(master)master.gain.value=muted?0:.3;$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';};
const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};window.addEventListener('keydown',e=>{if(map[e.key]){e.preventDefault();keys.add(map[e.key]);target=null;unlock();}if(e.key==='Escape')pause();});window.addEventListener('keyup',e=>keys.delete(map[e.key]));for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);target=null;unlock();};for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys.delete(b.dataset.key));}window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});canvas.onpointerdown=e=>{unlock();const r=canvas.getBoundingClientRect();target={x:(e.clientX-r.left)*480/r.width,y:(e.clientY-r.top)*360/r.height+s.cameraY};};
function leaves(){for(const [i,l]of s.leaves.entries()){ctx.save();ctx.translate(l.x,l.y-s.cameraY-l.z);ctx.rotate(l.angle);ctx.scale(1,Math.max(.3,Math.abs(Math.cos(l.age*4))));ctx.fillStyle=['#b75b2b','#b68635','#703923'][i%3];ctx.beginPath();ctx.moveTo(0,-3);ctx.lineTo(1,-1);ctx.lineTo(4,-2);ctx.lineTo(2,1);ctx.lineTo(3,3);ctx.lineTo(0,2);ctx.lineTo(-3,3);ctx.lineTo(-2,0);ctx.lineTo(-3,-2);ctx.closePath();ctx.fill();ctx.restore();}}
function fog(strength=.1){for(let i=0;i<7;i++){const x=(i*91+s.time*5)%620-70,y=110+(i%3)*87,g=ctx.createRadialGradient(x,y,4,x,y,105);g.addColorStop(0,`rgba(172,188,196,${strength})`);g.addColorStop(1,'rgba(172,188,196,0)');ctx.fillStyle=g;ctx.fillRect(x-105,y-105,210,210);}}
function alley(){ctx.drawImage(art.alley,0,-s.cameraY,480,1440);leaves();props.draw(ctx,'alley',s);if(s.phase!=='unload'||s.age>.8)drawPlayer(ctx,{...s,y:s.y-s.cameraY},s.moving);ctx.fillStyle=`rgba(2,6,20,${.7*(1-s.dawn)})`;ctx.fillRect(0,0,480,360);ctx.fillStyle=`rgba(255,186,115,${s.dawn*.08})`;ctx.fillRect(0,0,480,360);fog(.07);if(s.branch==='arrest'&&!s.tapeBroken&&s.cameraY<220){ctx.save();ctx.font='5px monospace';ctx.fillStyle='#191b1a';ctx.textAlign='center';ctx.fillText('POLICE  •  DO NOT CROSS',242,144-s.cameraY);ctx.restore();}}
function headlight(x,y){const g=ctx.createLinearGradient(x,y,x+160,y);g.addColorStop(0,'#ffedb84d');g.addColorStop(1,'#ffedb800');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+160,y-25);ctx.lineTo(x+160,y+40);ctx.closePath();ctx.fill();}
function title(alpha=1){drawPixelTitle(ctx,'THE END',alpha);}
function parking(){ctx.drawImage(art.park,0,0,480,360);const police=s.branch==='arrest',driving=s.phase==='police-drive',drive=driving?s.age:s.phase==='escape'?Math.max(0,s.age-8.5):0,x=322+drive*drive*15,y=282,door=['escort','crouch'].includes(s.phase)?1:0;headlight(x+94,y+5);if(!police&&s.age<5.5){const p=Math.min(1,s.age/5.5);drawPlayer(ctx,{x:160+p*125,y:187+p*82,spriteHeight:68,face:'right',walk:s.age*9},true);}props.draw(ctx,police?'police':'car',s,{x,y,door,wheel:drive*9});if(police){const officerFrame=Math.floor(s.time*7)%4;
 if(s.phase==='approach'){drawPlayer(ctx,{x:ARREST.gateX,y:ARREST.gateY,face:s.age<2?'right':'left',spriteHeight:70,walk:0},false);if(s.age<2)drawEndingSprite(ctx,art.police,officerFrame,ARREST.gateX-70+Math.min(1,s.age/2)*29,ARREST.gateY,70);else drawEndingSprite(ctx,art.warning,policePose(s).frame,ARREST.gateX-41+Math.max(0,s.age-11.2)*20,ARREST.gateY,70);}
 if(s.phase==='cuff')drawEndingSprite(ctx,art.police,4+Math.min(3,Math.floor(s.age/1.05)),ARREST.gateX,ARREST.gateY,70);
 if(s.phase==='reaction')drawEndingSprite(ctx,art.escort,policePose(s).reactionFrame,ARREST.gateX,ARREST.gateY,70);
 if(s.phase==='escort'){const p=policePose(s);ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(p.escortX,p.escortY-1,23,3,0,0,Math.PI*2);ctx.fill();drawEndingSprite(ctx,art.escort,p.escortFrame,p.escortX,p.escortY,p.escortHeight);}
 if(s.phase==='crouch'){const f=Math.min(3,Math.floor(s.age/.9));ctx.save();if(f>=2){ctx.beginPath();ctx.rect(0,0,305,360);ctx.clip();}drawEndingSprite(ctx,art.crouch,f,ARREST.seatX+f*3,ARREST.seatY,76,false,art.crouch.maxHeight/1.03);ctx.restore();}
 for(const drop of s.spilled){const item=SECRETS.find(i=>i.id===drop.id);ctx.fillStyle='#0006';ctx.fillRect(drop.x-3,drop.y+2,6,2);ctx.save();ctx.translate(drop.x,drop.y-drop.z);ctx.rotate(drop.angle);drawEvidence(ctx,item,0,0,.8);ctx.restore();}
 if(s.phase!=='arrest-end'&&s.phase!=='complete'){const pulse=policeBeacon(s);ctx.save();ctx.globalCompositeOperation='screen';ctx.fillStyle=`rgba(220,18,29,${.025+pulse*.14})`;ctx.fillRect(0,0,480,360);const glow=ctx.createRadialGradient(x,y-38,15,x,y-38,560);glow.addColorStop(0,`rgba(255,33,39,${pulse*.19})`);glow.addColorStop(1,'rgba(210,12,23,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,480,360);ctx.restore();}if(s.phase==='arrest-end'){ctx.fillStyle='#000';ctx.fillRect(0,0,480,360);title(Math.min(1,s.age));}}
 fog(.055);}
function bedroom(){const p=bedroomPose(s);ctx.drawImage(art.bedroom,0,0,480,360);if(p.clownAlpha>0){ctx.save();ctx.beginPath(); // Clip to the panes, keeping the authored window frame in front.
 ctx.rect(378,13,42,34);ctx.rect(428,20,47,33);ctx.rect(378,56,42,59);ctx.rect(428,63,46,61);ctx.clip();ctx.globalAlpha=p.clownAlpha;drawEndingSprite(ctx,art.girl,4+p.clownFrame,414,117,79,false,Math.max(...art.girl.frames.slice(4).map(f=>f.h)));ctx.restore();}
 if(s.lampOn){const glow=ctx.createRadialGradient(BEDROOM.lampX,BEDROOM.lampY-24,3,BEDROOM.lampX,BEDROOM.lampY-24,115);glow.addColorStop(0,'#ffd48c70');glow.addColorStop(.45,'#ffc67621');glow.addColorStop(1,'#ffbc7800');ctx.fillStyle=glow;ctx.fillRect(0,0,285,250);}props.draw(ctx,'bedroom',s);ctx.fillStyle='#16121c55';ctx.beginPath();ctx.ellipse(p.girlX,p.girlY-2,19,3,0,0,Math.PI*2);ctx.fill();drawEndingSprite(ctx,art.reach,p.frame,p.girlX,p.girlY,p.girlHeight);ctx.fillStyle=`rgba(0,2,8,${p.darkness})`;ctx.fillRect(0,0,480,360);if(p.darkness>.5){ // Tiny fixed eye catches remain outside the glass after the lamp goes off.
 ctx.fillStyle='#c9d6a2';ctx.fillRect(417,92,2,1);ctx.fillRect(433,84,2,1);ctx.fillStyle='#dfe8bf40';ctx.fillRect(416,91,4,3);ctx.fillRect(432,83,4,3);}
 if(s.phase==='bedroom-end'){ctx.fillStyle='#000';ctx.fillRect(0,0,480,360);title(Math.min(1,s.age/2));}}
function render(){ctx.imageSmoothingEnabled=false;ctx.fillStyle='#000';ctx.fillRect(0,0,480,360);if(['unload','alley'].includes(s.phase))alley();else if(['bedroom','bedroom-end'].includes(s.phase))bedroom();else if(s.phase==='ending-hint'){/* Let the final message precede the title on black. */}else if(s.phase==='complete')title();else parking();const fade=s.phase==='alley'?Math.max(0,(120-s.y)/31):['approach','escape','bedroom'].includes(s.phase)?Math.max(0,1-s.age/.7):0;if(fade){ctx.fillStyle=`rgba(0,0,0,${Math.min(1,fade)})`;ctx.fillRect(0,0,480,360);}$('#notice').textContent=s.notice;if(!s.notice&&$('#story-overlay'))$('#story-overlay').hidden=true;const label=$('#story-overlay .speaker');if(label)label.textContent=s.speaker;$('#objective').textContent='';$('#touch').hidden=s.phase!=='alley';if(s.paused){ctx.fillStyle='#000a';ctx.fillRect(0,0,480,360);ctx.fillStyle='#eee';ctx.font='18px FrightPixel,monospace';ctx.textAlign='center';ctx.fillText('PAUSED',240,180);}}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running){tickEpilogue(s,{...Object.fromEntries([...keys].map(k=>[k,true])),target},dt);alleySound?.tick(s,muted);if(!s.paused){siren?.tick(s,muted);handheldSound();if(s.spilledOnce&&!lastCuff){lastCuff=true;fx(1600,.15);}if(lastLamp&&!s.lampOn){fx(800,.07);lastLamp=false;}if(s.phase==='escape'&&s.age>8.5&&!musicOn){unlock();music.play();musicOn=true;}if(s.phase==='bedroom'&&musicOn){music.stop();musicOn=false;}if(s.phase==='complete'){$('#veil').hidden=false;$('#veil h1').textContent='THE END';$('#intro').textContent=s.branch==='arrest'?'The evidence is no longer in your pockets.':'Outside her window, something is still awake.';$('#start').textContent='REPLAY THIS SCENE';}}render();}requestGameFrame(frame);}
const image=url=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error(url));i.src=url;});Promise.all([image('./assets/park-alley-v1.png'),image('./assets/park-sunrise.png'),image('./assets/bedroom-dark-v1.png'),loadEndingSheet('./assets/characters/police-arrest-v1.png',4,3),loadEndingSheet('./assets/characters/police-car-entry-v1.png',4,1),loadEndingSheet('./assets/characters/girl-shadow-clown-v2.png',4,2,[0,500,887]),loadEndingSheet('./assets/characters/girl-seated-lamp-v4.png',4,2,null,true),loadEndingSheet('./assets/characters/police-warning-v1.png',4,2,null,true),loadEndingSheet('./assets/characters/police-escort-v2.png',4,2)]).then(([alley,park,bedroom,police,crouch,girl,reach,warning,escort])=>{art={alley,park,bedroom,police,crouch,girl,reach,warning,escort};props=createEpilogueProps();$('#start').disabled=false;enterRoom(start,unlock);}).catch(e=>{console.error(e);$('#intro').textContent='The epilogue could not load. Reload to retry.';});Object.defineProperty(window,'frightEpilogue',{get:()=>s?({...structuredClone(s),running,pose:bedroomPose(s),policePose:policePose(s),beacon:policeBeacon(s),alleySound:alleySound?.snapshot()??null,siren:siren?.snapshot()??{playing:false,level:0},handheld:{notes:handheldNotes,playing:s.phase==='bedroom'&&s.age<13&&!s.paused&&!muted&&ac?.state==='running'},render:props?.snapshot(),sprites:{escort:8,warning:8,police:12,crouch:4,girl:4,clown:4,reach:8}}):null});requestGameFrame(frame);

configureTelemetry({room:12,state:()=>s,running:()=>running,position:s=>{
 let x=s.x||0,y=s.y||0;
 if(['approach','cuff','reaction'].includes(s.phase)){x=ARREST.gateX;y=ARREST.gateY;}
 else if(s.phase==='escort'){const p=policePose(s);x=p.escortX;y=p.escortY;}
 else if(s.phase==='crouch'){x=ARREST.seatX;y=ARREST.seatY;}
 else if(s.phase==='police-drive'){x=322+s.age*s.age*15;y=282;}
 else if(s.phase==='escape'){const t=Math.min(1,s.age/5.5);x=s.age<5.5?160+t*125:322+Math.max(0,s.age-8.5)**2*15;y=s.age<5.5?187+t*82:282;}
 else if(['bedroom','bedroom-end'].includes(s.phase)){x=BEDROOM.girlX;y=BEDROOM.girlY;}
 return [x/40,y/40];
}});
