import * as THREE from '../vendor/three.module.js';
import makeWeb from './assets/three/fall-web.js';import makeStone from './assets/three/fall-stone.js';
import makeDoor from './assets/three/fall-door.js';import makeBeam from './assets/three/fall-obstacle.js';import makeWeight from './assets/three/fall-weight.js';import makePipe from './assets/three/fall-pipe.js';import makeBones from './assets/three/fall-bones.js';
import {FALL_OBSTACLES,obstaclePose,SHAFT} from './levels/fall-model.js';
export function createFallProps(){const renderer=new THREE.WebGLRenderer({alpha:true,antialias:false});renderer.setSize(480,360,false);renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(0,480,360,0,.1,2000);camera.position.z=1000;scene.add(new THREE.HemisphereLight(0xadb7a0,0x151e1c,1.5));const light=new THREE.DirectionalLight(0xffce8d,2.3);light.position.set(-150,420,750);scene.add(light);
function fit(body,w,h){const pose=new THREE.Group();pose.add(body);pose.rotation.x=.23;pose.rotation.y=-.12;pose.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(pose),size=bounds.getSize(new THREE.Vector3()),c=bounds.getCenter(new THREE.Vector3());const root=new THREE.Group();pose.scale.set(w/size.x,h/size.y,w/size.x);pose.position.set(-c.x*pose.scale.x,-c.y*pose.scale.y,0);root.add(pose);scene.add(root);return {root,body};}
const door=fit(makeDoor(THREE),89,131),bones=fit(makeBones(THREE),248,77);door.root.position.set(240,360-137,0);bones.root.position.set(240,360-(SHAFT.landing+22),0);const obstacles=FALL_OBSTACLES.map(o=>({...o,...fit((o.kind==='web'?makeWeb:o.kind==='weight'?makeWeight:o.kind==='pipe'?makePipe:makeBeam)(THREE),obstaclePose(o,0).w,obstaclePose(o,0).h)}));
const stones=Array.from({length:8},()=>fit(makeStone(THREE),22,22));for(const stone of stones)stone.root.visible=false;const chains=new Map();for(const o of obstacles)if(o.kind==='weight'){const iron=new THREE.MeshStandardMaterial({color:0x596052,metalness:.7,roughness:.8}),links=new THREE.InstancedMesh(new THREE.TorusGeometry(2.1,.7,4,8),iron,32),mount=new THREE.Mesh(new THREE.BoxGeometry(15,8,12),iron);links.frustumCulled=false;scene.add(links,mount);chains.set(o.id,{links,mount});}const dummy=new THREE.Object3D();
return {draw(ctx,s){camera.position.y=-s.cameraY;camera.updateMatrixWorld();const inEntry=['entry','opening','walking','blackout'].includes(s.phase);door.root.visible=inEntry;door.body.userData.hinge.rotation.y=-s.door*1.45;const impact=['landing','complete'].includes(s.phase)?s.landAge:0;for(const [i,bone]of bones.body.userData.loose.entries()){bone.position.copy(bone.userData.rest);if(impact>0&&impact<2){const t=impact;bone.position.x+=Math.sin(i*2.399)*Math.min(.15,t*.12);bone.position.y+=Math.max(0,Math.sin(Math.min(1,t/1.6)*Math.PI))*(.06+i%3*.025);bone.rotation.z+=.02*Math.exp(-t);}}bones.root.visible=SHAFT.landing-s.cameraY<440;for(const o of obstacles){const p=obstaclePose(o,s.time);o.root.visible=!inEntry&&Math.abs(p.y-s.cameraY-180)<270;o.root.position.set(p.x,360-p.y,0);o.root.rotation.z=-p.angle;const chain=chains.get(o.id);if(chain){const ax=o.side<0?118:362,ay=o.y-112,bx=p.x,by=p.y-p.h/2+7;chain.links.visible=chain.mount.visible=!inEntry&&Math.abs(p.y-s.cameraY-180)<370;chain.mount.position.set(ax,360-ay,0);for(let i=0;i<32;i++){const t=i/31;dummy.position.set(ax+(bx-ax)*t,360-(ay+(by-ay)*t),0);dummy.rotation.set(0,i%2?Math.PI/2:0,Math.atan2(bx-ax,by-ay));dummy.updateMatrix();chain.links.setMatrixAt(i,dummy.matrix);}chain.links.instanceMatrix.needsUpdate=true;}}for(const [i,prop]of stones.entries()){const rock=s.stones[i];prop.root.visible=!!rock&&!inEntry&&Math.abs(rock.y-s.cameraY-180)<235;if(rock){prop.root.position.set(rock.x,360-rock.y,10);prop.root.rotation.set(rock.age*1.7,rock.age*2.3,rock.age);prop.root.scale.setScalar(rock.r/11);}}renderer.render(scene,camera);ctx.drawImage(renderer.domElement,0,0);},snapshot:()=>({door3D:true,movingObstacles3D:obstacles.length,hangingWebs3D:4,fallingStones3D:stones.filter(o=>o.root.visible).length,bonePile3D:true,bones:76,skulls:13,calls:renderer.info.render.calls,triangles:renderer.info.render.triangles})};}
