import {newFall,fallBlackout,tickFall,openFallDoor,SHAFT,FALL_OBSTACLES,obstaclePose} from './levels/fall-model.js';import {createFallProps} from './fall-props.js';import {createFallSprites} from './fall-sprites.js';import {createFallSound} from './fall-sound.js';
const $=x=>document.querySelector(x),canvas=$('#game'),ctx=canvas.getContext('2d'),bg=new Image(),sound=createFallSound(),keys=new Set();ctx.imageSmoothingEnabled=false;let s=newFall(),running=false,last=performance.now(),props,sprites,muted=false,dragging=false;
function release(){keys.clear();dragging=false;}function start(){s=newFall();running=true;release();sound.start();$('#veil').hidden=true;$('#pause').textContent='PAUSE';canvas.focus();if(new URLSearchParams(location.search).has('arrival'))openFallDoor(s);}function pause(force){if(!running)return;s.paused=force??!s.paused;release();$('#pause').textContent=s.paused?'RESUME':'PAUSE';s.paused?sound.pause():sound.resume();}function action(){openFallDoor(s);}
$('#start').onclick=start;$('#retry').onclick=start;$('#restart').onclick=start;$('#pause').onclick=()=>pause();$('#action').onclick=action;$('#sound').onclick=()=>{muted=!muted;sound.mute(muted);$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';};
const blackout=document.createElement('div');blackout.id='transition-blackout';blackout.setAttribute('aria-hidden','true');$('#stage').append(blackout);
const map={a:'left',ArrowLeft:'left',d:'right',ArrowRight:'right'};window.addEventListener('keydown',e=>{if(map[e.key]||e.key===' ')e.preventDefault();if(e.repeat)return;if(map[e.key])keys.add(map[e.key]);if(e.key.toLowerCase()==='e'||e.key===' ')action();if(e.key==='Escape')pause();});window.addEventListener('keyup',e=>keys.delete(map[e.key]));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));}
function steer(e){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*480;keys.delete('left');keys.delete('right');if(Math.abs(x-s.x)>7)keys.add(x<s.x?'left':'right');}canvas.onpointerdown=e=>{if(!running||s.paused)return;if(s.phase==='entry'){action();return;}dragging=true;canvas.setPointerCapture(e.pointerId);steer(e);};canvas.onpointermove=e=>{if(dragging)steer(e);};canvas.onpointerup=canvas.onpointercancel=()=>release();
function render(){ctx.fillStyle='#040707';ctx.fillRect(0,0,480,360);ctx.save();ctx.translate(0,-s.cameraY);const tile=720;for(let y=Math.floor(s.cameraY/tile)*tile;y<s.cameraY+360;y+=tile)ctx.drawImage(bg,0,y,480,tile);if(['entry','opening','walking','blackout'].includes(s.phase)){
// A continuous boarded room floor reaches the doorway threshold and the foreground.
ctx.fillStyle='#29271f';ctx.fillRect(0,63,480,142);for(let i=0;i<24;i++){const x=i*21;ctx.fillStyle=i%3?'#393126':'#42382a';ctx.fillRect(x,66,19,137);ctx.fillStyle='#201f19';ctx.fillRect(x+18,66,2,137);}ctx.fillStyle='#191e19';ctx.fillRect(0,194,480,10);ctx.fillStyle='#665037';ctx.fillRect(0,202,480,4);ctx.fillStyle='#0a0d0d';ctx.fillRect(195,67,90,138);
for(let row=0;row<11;row++){const y=205+row*15;for(let col=-1;col<8;col++){const x=col*76+(row%2)*38;ctx.fillStyle=['#55432e','#604b33','#493e2d'][(row+col+9)%3];ctx.fillRect(x,y,75,14);ctx.fillStyle='#2b281e';ctx.fillRect(x,y+13,75,1);ctx.fillStyle='#796047';ctx.fillRect(x+3,y+2,69,1);for(let grain=0;grain<4;grain++){ctx.fillStyle=grain%2?'#4b3d2b':'#6b5439';ctx.fillRect(x+7+(grain*17+row*3)%30,y+4+grain*2,17+(grain*7)%22,1);}ctx.fillStyle='#28261e';ctx.fillRect(x+4,y+6,1,2);ctx.fillRect(x+70,y+6,1,2);}}
ctx.fillStyle='#393025';ctx.fillRect(193,202,94,5);
}
if(s.cameraY>SHAFT.landing-360){ctx.fillStyle='#171814';ctx.fillRect(110,SHAFT.landing+38,260,250);for(let i=0;i<420;i++){const x=112+(i*73)%256,y=SHAFT.landing+40+(i*47)%210;ctx.fillStyle=i%3?'#292b23':'#3a392d';ctx.fillRect(x,y,2+i%4,1+i%2);}}ctx.restore();props.draw(ctx,s);ctx.save();ctx.translate(0,-s.cameraY);if(running)sprites.draw(ctx,s);for(const p of s.dust){const t=p.age/p.life;ctx.fillStyle=`rgba(187,178,149,${(1-t)*.22})`;ctx.beginPath();ctx.ellipse(p.x,p.y,p.r*(1+t*2.5),p.r*(.7+t),0,0,7);ctx.fill();}for(let i=0;i<60;i++){const x=115+(i*73.1)%251,y=s.cameraY+(i*31+s.time*(2+i%5))%360;ctx.fillStyle=`rgba(182,174,139,${.05+(i%4)*.02})`;ctx.fillRect(x,y,1,1);}ctx.restore();const shade=ctx.createLinearGradient(0,0,480,0);shade.addColorStop(0,'#010404b0');shade.addColorStop(.3,'transparent');shade.addColorStop(.7,'transparent');shade.addColorStop(1,'#010404b0');ctx.fillStyle=shade;ctx.fillRect(0,0,480,360);
blackout.style.opacity=fallBlackout(s);if(['opening','walking','blackout'].includes(s.phase)){const story=$('#story-overlay');if(story)story.hidden=true;}
if(s.paused){ctx.fillStyle='#020606c0';ctx.fillRect(0,0,480,360);ctx.fillStyle='#e2d6bb';ctx.font='18px monospace';ctx.textAlign='center';ctx.fillText('PAUSED',240,170);}$('#health').textContent='● '.repeat(s.health)+'○ '.repeat(4-s.health);$('#depth').textContent=['entry','opening','walking','blackout'].includes(s.phase)?'BEYOND THE WORKSHOP':`DEPTH ${Math.max(0,Math.floor((s.y-220)/12))} m`;$('#hint').textContent=s.phase==='entry'?'E · OPEN THE DOOR':'';$('#action').disabled=s.phase!=='entry';$('#notice').textContent=s.noticeAge>0?s.notice:'';$('#objective').textContent='';}
function finish(){release();sound.pause();$('#veil').hidden=false;const win=s.phase==='complete';$('#veil h1').textContent=win?'BENEATH THE FUNHOUSE':'LOST IN THE SHAFT';$('#intro').textContent=win?'The bones settle beneath you. The air tastes of dust. Level 9 complete.':'The shaft is still waiting. Steer left and right between the moving machinery.';$('#start').textContent=win?'FALL AGAIN':'RETRY THE FALL';if(win)setTimeout(()=>{if(s.phase==='complete')location.href='./level-10.html?arrival=bones';},900);}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running){tickFall(s,Object.fromEntries([...keys].map(k=>[k,true])),dt);sound.tick(s);if(['caught','complete'].includes(s.phase)&&$('#veil').hidden)finish();}if(props&&sprites&&bg.complete)render();requestAnimationFrame(frame);}
Promise.all([new Promise((r,j)=>{bg.onload=r;bg.onerror=j;bg.src='./assets/fall-shaft.png';}),createFallSprites()]).then(([,art])=>{sprites=art;props=createFallProps();$('#start').disabled=false;$('#start').textContent='STEP BEYOND THE DOOR';if(new URLSearchParams(location.search).has('arrival'))start();}).catch(e=>{$('#intro').textContent='The shaft assets could not load. Reload to retry.';console.error(e);});Object.defineProperty(window,'frightFall',{get:()=>({...structuredClone(s),running,blackout:fallBlackout(s),obstacles:FALL_OBSTACLES.map(o=>({...o,...obstaclePose(o,s.time)})),sprites:sprites?.snapshot(),render:props?.snapshot()})});requestAnimationFrame(frame);
