import {ITEMS,initial,blocked,move,near,tick} from './model.js';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d');canvas.height=360;ctx.imageSmoothingEnabled=false;
const bg=new Image();bg.src='./assets/foyer-l.png';let ready=false,s=initial(),running=false,paused=false,muted=false,dialog=null,after=null,last=performance.now(),keys=new Set(),wallAngle=0;
const sound={ambience:new Audio('../audio/ambience.mp3'),whisper:new Audio('../audio/monsterCall.m4a'),wall:new Audio('../audio/wall.mp3'),laugh:new Audio('../audio/laughter.mp3')};sound.ambience.loop=true;sound.ambience.volume=.18;sound.whisper.volume=.78;sound.whisper.playbackRate=.85;sound.wall.volume=.35;sound.laugh.volume=.22;
const musicResume=new Set();function play(id){if(muted||paused)return;const a=sound[id];a.currentTime=0;a.play().catch(()=>{});}function stopAll(){musicResume.clear();for(const a of Object.values(sound)){a.pause();a.currentTime=0;}}
function say(name,text,then){keys.clear();dialog={name,text};after=then;$('#speaker').textContent=name;$('#line').textContent=text;$('#dialog').hidden=false;}
function dismiss(){if(!dialog||paused)return;dialog=null;$('#dialog').hidden=true;const cb=after;after=null;cb?.();}
function begin(){if(!ready)return;stopAll();s=initial();wallAngle=0;running=true;paused=false;dialog=null;after=null;keys.clear();$('#veil').hidden=true;$('#dialog').hidden=true;$('#pause').textContent='PAUSE';play('ambience');say('SEPTEMBER, 1987','The ticket counter is empty. Three belongings are still here. Follow the narrow corridor to the service exit.');}
function pause(){if(!running)return;paused=!paused;keys.clear();$('#pause').textContent=paused?'RESUME':'PAUSE';if(paused){for(const [id,a]of Object.entries(sound)){if(!a.paused)musicResume.add(id);a.pause();}}else{for(const id of musicResume)if(!muted)sound[id].play().catch(()=>{});musicResume.clear();}}
function ending(won){running=false;stopAll();$('#veil').hidden=false;$('#veil h1').innerHTML=won?'YOU FOUND<br>THE WAY OUT':'STAY A<br>LITTLE LONGER';$('#veil .eyebrow').textContent=won?'2D SCENE COMPLETE':'THE HOUSE KEEPS WHAT IT FINDS';$('#veil p:not(.eyebrow)').innerHTML=won?'The corridor leads deeper into the park.<br>The rest of the 2D adaptation is still to come.':'The clown caught up with you.<br>Open the wall before collecting the last belonging.';$('#start').textContent='PLAY AGAIN';}
function interact(){if(paused||!running)return;if(dialog){dismiss();return;}const target=near(s);if(!target)return;if(target.kind==='item'){s.collected.push(target.item.id);say(target.item.title.toUpperCase(),target.item.text,()=>{if(s.collected.length===3){s.phase='chase';say('SOMETHING IN THE DARK','Come here, darling…',()=>{});play('whisper');}});}else if(target.kind==='lever'){s.wallOpen=!s.wallOpen;play('wall');}else if(s.collected.length===3){s.phase='escaped';ending(true);}else say('SERVICE EXIT','The lock is old. A small brass key might fit. Find all three belongings first.');}
$('#start').onclick=begin;$('#retry').onclick=begin;$('#pause').onclick=pause;$('#continue').onclick=dismiss;$('#action').onclick=interact;$('#light').onclick=()=>{if(running&&!paused&&!dialog)s.light=!s.light;};$('#sound').onclick=()=>{muted=!muted;for(const a of Object.values(sound))a.muted=muted;$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';$('#sound').setAttribute('aria-label',muted?'Unmute sound':'Mute sound');};
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLButtonElement&&e.key==='Enter')return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.repeat)return;if(e.key==='Escape'){pause();return;}if(['e','E','Enter',' '].includes(e.key)){interact();return;}if(e.key.toLowerCase()==='f'){if(running&&!paused&&!dialog)s.light=!s.light;return;}keys.add(e.key.toLowerCase());});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function release(){keys.clear();document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));}window.addEventListener('blur',()=>{release();if(running&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)pause();});
for(const b of document.querySelectorAll('[data-key]')){const key=b.dataset.key.toLowerCase();b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(key);b.classList.add('held');};for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>{keys.delete(key);b.classList.remove('held');});}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}function ellipse(x,y,rx,ry,c){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function player(){const x=Math.round(s.x),y=Math.round(s.y),bob=keys.size&&!dialog&&!paused?Math.sin(s.walk)*.7:0,feet=keys.size?Math.sin(s.walk)*2:0;ellipse(x,y+1,8,3,'#09080bb0');rect(x-5,y-7,4,7+feet,'#242e37');rect(x+1,y-7,4,7-feet,'#293641');rect(x-6,y-13+bob,12,9,'#372429');rect(x-5,y-14+bob,10,8,'#775b40');rect(x-5,y-14+bob,2,7,'#a27b51');rect(x-4,y-23+bob,9,9,'#372524');rect(x-3,y-22+bob,7,7,s.face==='up'?'#42312b':'#c5976a');rect(x-5,y-23+bob,10,4,'#302326');rect(x-6,y-21+bob,3,5,'#302326');if(s.face!=='up'){rect(x+(s.face==='left'?-3:2),y-19+bob,1,2,'#171a21');rect(x,y-15+bob,4,1,'#8e573f');}const dir=s.face==='left'?-1:1;rect(x+dir*6-2,y-12+bob,4,5,'#8a6846');rect(x+dir*8-2,y-10+bob,5,3,'#252a2e');rect(x+dir*10,y-10+bob,2,3,s.light?'#f8dea2':'#74634e');}
function panel(){const x=405,y=214,dx=Math.cos(wallAngle)*29,dy=Math.sin(wallAngle)*29;ellipse(x,y,30,5,'#07070966');ctx.fillStyle='#355b60';ctx.beginPath();ctx.moveTo(x-dx,y-dy);ctx.lineTo(x+dx,y+dy);ctx.lineTo(x+dx,y+dy-17);ctx.lineTo(x-dx,y-dy-17);ctx.closePath();ctx.fill();for(let i=0;i<7;i++){const t=i/7,u=(i+1)/7;ctx.fillStyle=i%2?'#27464b':'#9b9373';ctx.beginPath();ctx.moveTo(x-dx+2*dx*t,y-dy+2*dy*t-16);ctx.lineTo(x-dx+2*dx*u,y-dy+2*dy*u-16);ctx.lineTo(x-dx+2*dx*Math.max(0,u-.05),y-dy+2*dy*Math.max(0,u-.05)-2);ctx.lineTo(x-dx+2*dx*Math.max(0,t-.05),y-dy+2*dy*Math.max(0,t-.05)-2);ctx.closePath();ctx.fill();}ctx.strokeStyle='#ac8954';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-dx,y-dy-17);ctx.lineTo(x+dx,y+dy-17);ctx.stroke();rect(346,171,10,14,'#25252a');rect(348,173,6,11,'#716040');ctx.strokeStyle='#b69a61';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(351,178);ctx.lineTo(s.wallOpen?357:347,165);ctx.stroke();ellipse(s.wallOpen?357:347,165,3,3,'#9d3931');}
function item(i){const y=i.y+Math.sin(s.time*2+i.x)*.8;ellipse(i.x,y+1,6,2,'#07080966');if(i.id==='ticket'){rect(i.x-5,y-5,10,5,'#cdb889');rect(i.x-3,y-4,5,1,'#814636');rect(i.x-5,y-2,1,1,'#2b2429');}else if(i.id==='ribbon'){rect(i.x-5,y-5,4,5,'#438499');rect(i.x+1,y-5,4,5,'#528f9e');rect(i.x-2,y-3,4,2,'#aec2b3');}else{ctx.strokeStyle='#ddae60';ctx.lineWidth=2;ctx.beginPath();ctx.arc(i.x-3,y-4,2,0,Math.PI*2);ctx.moveTo(i.x-1,y-4);ctx.lineTo(i.x+5,y-1);ctx.stroke();rect(i.x+4,y-2,2,3,'#c9934d');}if(Math.floor(s.time*2+i.x)%5===0){rect(i.x+7,y-9,1,5,'#dbc697');rect(i.x+5,y-7,5,1,'#dbc697');}}
function monster(){const x=s.monster.x,y=s.monster.y,t=s.time;for(let i=0;i<8;i++){const a=i*2.4+t*.25;ellipse(x+Math.sin(a)*12,y-8+Math.cos(a)*8,10+Math.sin(a)*3,7,'#06050966');}ctx.strokeStyle='#302d2c';ctx.lineWidth=3;for(let i=0;i<6;i++){const side=i<3?-1:1,k=i%3,reach=20+k*4;ctx.beginPath();ctx.moveTo(x+side*3,y-14);ctx.lineTo(x+side*reach,y-32+k*15+Math.sin(t*3+k)*3);ctx.lineTo(x+side*(reach+8),y-13+k*7);ctx.stroke();ctx.strokeStyle='#7c7460';ctx.lineWidth=1;ctx.lineTo(x+side*(reach+3),y-7+k*7);ctx.stroke();ctx.strokeStyle='#302d2c';ctx.lineWidth=3;}rect(x-8,y-31,16,14,'#2d2327');for(let i=0;i<5;i++){rect(x-12-i%2,y-30+i*3,5,5,'#8b3d26');rect(x+8,y-30+i*3,5,6,'#713323');}ellipse(x,y-26,8,12,'#b5a886');rect(x-6,y-30,5,5,'#27252a');rect(x+2,y-30,5,5,'#27252a');rect(x-4+Math.sign(s.x-x),y-29,2,2,'#fff0c0');rect(x+3+Math.sign(s.x-x),y-29,2,2,'#fff0c0');ellipse(x,y-23,2.5,2,'#912c2c');ellipse(x,y-18,5,4+Math.sin(t*7),'#21151e');for(let i=0;i<4;i++)rect(x-4+i*2,y-21,1,2,'#d7c196');}
function render(){ctx.clearRect(0,0,480,360);if(ready)ctx.drawImage(bg,0,0,480,360);panel();for(const i of ITEMS)if(!s.collected.includes(i.id))item(i);rect(383,347,45,5,s.collected.length===3?'#477269':'#3b2c29');ctx.fillStyle='#d4b98c';ctx.font='5px monospace';ctx.fillText('SERVICE EXIT',385,345);if(s.phase==='chase'&&s.monster.y<s.y)monster();player();if(s.phase==='chase'&&s.monster.y>=s.y)monster();const alpha=s.phase==='chase'?.38:.15;ctx.fillStyle=`rgba(4,5,13,${alpha})`;ctx.fillRect(0,0,480,360);if(s.light){ctx.save();ctx.globalCompositeOperation='screen';const angles={up:-Math.PI/2,down:Math.PI/2,left:Math.PI,right:0},a=angles[s.face],x=s.x,y=s.y-8,g=ctx.createRadialGradient(x,y,1,x,y,94);g.addColorStop(0,'#a1844144');g.addColorStop(1,'#d4b67600');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(x,y);ctx.arc(x,y,94,a-.48,a+.48);ctx.closePath();ctx.fill();ctx.restore();}if(paused){ctx.fillStyle='#050508ba';ctx.fillRect(0,0,480,360);ctx.fillStyle='#e1ceb0';ctx.font='16px monospace';ctx.textAlign='center';ctx.fillText('PAUSED',240,166);ctx.textAlign='left';}$('#count').textContent=`BELONGINGS ${s.collected.length}/3`;$('#hint').textContent=running&&!dialog&&!paused?(near(s)?.label||''):'';$('#objective').textContent=s.phase==='chase'?'Get to the service exit. Do not wait for him.':s.collected.length?'Find the remaining belongings. The brass lever opens the corridor.':'Find what the children left behind.';}
function frame(now){const dt=Math.min((now-last)/1000,.04);last=now;if(running&&!paused&&!dialog){const dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dy=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));move(s,dx,dy,dt);tick(s,dt);wallAngle+=( (s.wallOpen?Math.PI/2:0)-wallAngle)*Math.min(1,dt*7);if(s.phase==='caught')ending(false);}render();requestAnimationFrame(frame);}bg.onload=()=>{ready=true;$('#start').disabled=false;$('#start').textContent='ENTER THE HOUSE';};bg.onerror=()=>{$('#start').textContent='ART FAILED TO LOAD — RELOAD';};
Object.defineProperty(window,'fright2d',{get:()=>JSON.parse(JSON.stringify({...s,paused,dialog:dialog?.name||null,running,ready}))});requestAnimationFrame(frame);
