import {newHallReactions,tickHallReactions} from './levels/hall-reactions.js';
import {createHallReactionProps} from './hall-reaction-props.js';
import {createForecourt} from './forecourt.js';
import hallGeometry from './hall-geometry.js';
import {newHall,HALL_OBJECTS,hallBlocked,moveHall,hallNear,hallPath} from './levels/hall-model.js';
import {drawPlayer} from './levels/temporary-player.js';
import {newCampaign,loadCampaign,saveCampaign,remember,checkpoint} from './campaign/state.js';
const $=q=>document.querySelector(q),canvas=$('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;const key='fright-house-2d-campaign-v1';
let campaign;try{campaign=loadCampaign(localStorage.getItem(key));}catch{}campaign||=newCampaign();campaign.area='ticket-hall';campaign.paused=false;campaign.story=null;
let layers=null,reactive=null,popAudio=null;
let s={...newHall(),...campaign.hall},running=false,paused=false,dialog=null,route=[],pending=null,keys=new Set(),last=performance.now();const bg=new Image();const audio=new Audio('../audio/ambience.mp3');audio.loop=true;audio.volume=.15;let muted=false;
s.reactions||=newHallReactions();
function reactionSound(kind){if(muted)return;try{popAudio||=new AudioContext();popAudio.resume();const o=popAudio.createOscillator(),g=popAudio.createGain();o.type=kind==='pop'?'sawtooth':'triangle';o.frequency.setValueAtTime(kind==='pop'?330:750,popAudio.currentTime);o.frequency.exponentialRampToValueAtTime(45,popAudio.currentTime+.12);g.gain.setValueAtTime(kind==='pop'?.055:.015,popAudio.currentTime);g.gain.exponentialRampToValueAtTime(.001,popAudio.currentTime+.13);o.connect(g).connect(popAudio.destination);o.start();o.stop(popAudio.currentTime+.14);}catch{}}
function save(){campaign.hall={...s};checkpoint(campaign);try{localStorage.setItem(key,saveCampaign(campaign));}catch{}}
function release(){keys.clear();route=[];pending=null;}
function say(title,text){release();dialog=title;$('#speaker').textContent=title;$('#line').textContent=text;$('#headline').hidden=true;$('#portrait').textContent='…';$('#dialog').hidden=false;}
function dismiss(){dialog=null;$('#dialog').hidden=true;}
function start(reset=false){if(reset){s=newHall();s.reactions=newHallReactions();campaign.journal=campaign.journal.filter(n=>!['hall-ledger','hall-note'].includes(n.id));}running=true;paused=false;dismiss();release();$('#veil').hidden=true;$('#pause').textContent='PAUSE';canvas.focus();if(!muted)audio.play().catch(()=>{});save();}
function pause(){paused=!paused;release();$('#pause').textContent=paused?'RESUME':'PAUSE';if(paused){audio.pause();popAudio?.suspend();}else if(!muted){audio.play().catch(()=>{});popAudio?.resume();}}
function interact(id){if(!running||paused)return;if(dialog){dismiss();return;}const o=typeof id==='string'?HALL_OBJECTS.find(o=>o.id===id&&Math.hypot(o.x-s.x,o.y-s.y)<o.r):hallNear(s);if(!o)return;
 if(o.id==='ledger'){s.ledger=true;remember(campaign,'hall-ledger','October 17: three admissions entered after closing. The attendant’s signature has been scratched out.');say('THE TICKET LEDGER','OCTOBER 17, 1987\nThree admissions, entered after closing. The attendant’s signature has been scratched out.\n\nA pencil arrow points to “UPPER ATTRACTION”.');}
 if(o.id==='lamp'){s.lamp=!s.lamp;release();}
 if(o.id==='drawer'){s.drawer=true;remember(campaign,'hall-note','A staff note: “If you hear the mechanism after closing, use the upper stairs. Do not go back through the mouth.”');say('LOST-PROPERTY DRAWER','A crumpled staff note lies beneath a torn glove:\n\n“If you hear the mechanism after closing, use the upper stairs. Do not go back through the mouth.”');}
 if(o.id==='staff-door'){s.door=true;say('THE RED STAFF DOOR','Locked from the other side. Behind the wired glass, something softly taps twice.');}
 if(o.id==='onward'){if(s.ledger&&s.drawer){save();location.href='./level-3.html';return;}say('THE UPPER ATTRACTION','Search the ledger and lost-property drawer before leaving the hall.');}save();
}
$('#start').onclick=()=>start();$('#resume').hidden=true;$('#retry').onclick=()=>start(true);$('#pause').onclick=pause;$('#continue').onclick=dismiss;$('#action').onclick=()=>interact();$('#journal').onclick=()=>say('FIELD NOTES',campaign.journal.map(n=>n.text).join('\n\n'));$('#light').onclick=()=>s.light=!s.light;$('#sound').onclick=()=>{muted=!muted;audio.muted=muted;$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';};
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.repeat)return;if(e.key==='Escape'){pause();return;}if(['e','E',' '].includes(e.key)){interact();return;}keys.add(e.key.toLowerCase());route=[];pending=null;});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{if(running&&!paused)pause();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)pause();});
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key.toLowerCase());route=[];};for(const n of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(n,()=>keys.delete(b.dataset.key.toLowerCase()));}
canvas.onpointerdown=e=>{if(!running||paused||dialog)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*480/r.width,y=(e.clientY-r.top)*360/r.height;let o=HALL_OBJECTS.find(o=>Math.hypot(o.x-x,o.y-y)<18);if(x>72&&x<150&&y>70&&y<134)o=HALL_OBJECTS[0];if(x>393&&x<428&&y>66&&y<130)o=HALL_OBJECTS[3];const aim=o||{x,y};route=hallPath(s,aim.x,aim.y);pending=o?.id||null;if(o&&Math.hypot(o.x-s.x,o.y-s.y)<o.r)interact(o.id);};
function render(){ctx.drawImage(bg,0,0,480,360);reactive?.draw(ctx,s,false);layers?.draw(ctx,s,false);if(!s.lamp){ctx.fillStyle='#060a10aa';ctx.fillRect(73,73,76,58);}else{ctx.fillStyle='#e0b55122';ctx.beginPath();ctx.ellipse(129,96,21,13,0,0,Math.PI*2);ctx.fill();}if(s.drawer){ctx.fillStyle='#201613';ctx.fillRect(84,121,18,8);ctx.fillStyle='#8d6743';ctx.fillRect(84,127,18,4);}ctx.fillStyle='#bca578';ctx.fillRect(112,99,9,5);ctx.fillStyle='#3e3426';ctx.fillRect(113,100,7,1);drawPlayer(ctx,s,(keys.size||route.length)&&!dialog&&!paused);reactive?.draw(ctx,s,true);layers?.draw(ctx,s,true);for(const [i,x,y]of [[0,81,19],[1,128,18],[2,181,13],[3,228,18],[4,276,19],[5,401,43],[6,440,43]]){ctx.fillStyle=`rgba(232,179,93,${.09+.05*Math.sin(s.time+i)})`;ctx.beginPath();ctx.arc(x,y,6,0,7);ctx.fill();}if(paused){ctx.fillStyle='#030606bf';ctx.fillRect(0,0,480,360);ctx.fillStyle='#ddd0a8';ctx.font='16px monospace';ctx.fillText('PAUSED',210,176);}$('#hint').textContent=!dialog&&!paused?(hallNear(s)?.label||''):'';$('#count').textContent='FIELD NOTES '+campaign.journal.length;$('#objective').textContent=s.ledger&&s.drawer?'Follow the narrow corridor to the attraction stairs.':'Search the ticket ledger and lost-property drawer.';}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running&&!paused&&!dialog){let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dy=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));if(!dx&&!dy&&route.length){dx=route[0].x-s.x;dy=route[0].y-s.y;if(Math.hypot(dx,dy)<2){route.shift();dx=dy=0;}}moveHall(s,dx,dy,dt);s.time+=dt;const reactions=tickHallReactions(s,dt);reactions.forEach(reactionSound);if(reactions.length)save();if(!route.length&&pending){interact(pending);pending=null;}}if(bg.complete&&bg.naturalWidth)render();requestAnimationFrame(frame);}
bg.onload=()=>{layers=createForecourt(bg,hallGeometry);reactive=createHallReactionProps();$('#start').disabled=false;$('#start').textContent='ENTER THE TICKET HALL';if(new URLSearchParams(location.search).has('arrival'))start();};bg.src='./assets/foyer-reactive-clean.png';Object.defineProperty(window,'fright2d',{get:()=>({...s,area:'ticket-hall',foreground:layers?.snapshot(),reactiveProps:reactive?.snapshot(),running,paused,dialog,route:route.length,notes:campaign.journal.map(n=>n.id)})});requestAnimationFrame(frame);
