import {drawEvidence} from './evidence-icons.js';
import {drawSecretsOverlay} from './secrets-ui.js';
import {createRoomMusic} from './room-music.js';
import {showCollectedInstruction} from './instructions-ui.js';
import {takeInstruction} from './campaign/instructions.js';
import {enterRoom,leaveRoom} from './room-flow.js';
import {createLibraryBackdrop} from './library-backdrop.js';
import {createForecourt} from './forecourt.js';import libraryGeometry from './library-geometry.js';
import {newLibrary,libraryAction,libraryNear,libraryCanInteract,libraryPath,answerLibraryPhone,closeLibraryPhone,tickLibrary,LIBRARY_OBJECTS} from './levels/library-model.js';import {createLibraryProps} from './library-props.js';import {createLibraryInspection} from './library-inspection.js';import {createLibrarySound} from './library-sound.js';import {drawPlayer} from './levels/temporary-player.js';import {drawWorm,wormReady} from './worm-sprites.js';import {newCampaign,loadCampaign,saveCampaign,remember} from './campaign/state.js';
const $=q=>document.querySelector(q),canvas=$('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;let s=newLibrary(),running=false,props,layers,backdrop,last=performance.now(),keys=new Set(),route=[],pending=null,muted=false,previousPhase='ringing',previousShots=0,previousJar=0,ambushPhases=[];const bg=new Image(),sound=createLibrarySound(),audio=createRoomMusic(5);audio.loop=true;audio.volume=.09;let campaign;try{campaign=loadCampaign(localStorage.getItem('fright-house-2d-campaign-v1'));}catch{}campaign||=newCampaign();
function release(){keys.clear();route=[];pending=null;}function save(){remember(campaign,'library-phone','A dead telephone line hissed with static. The telephone is marked SPECIMEN 087.');campaign.area='specimen-library';try{localStorage.setItem('fright-house-2d-campaign-v1',saveCampaign(campaign));localStorage.setItem('fright-house-library-v1','phone');}catch{}}
const inspector=createLibraryInspection({state:()=>s,pause:()=>pause(),pickup:()=>{if(answerLibraryPhone(s)){sound.call();save();}},close:()=>{if(closeLibraryPhone(s)){release();inspector.sync();canvas.focus();}}});
function start(checkpoint=false){sound.reset();sound.unlock();sound.resume();s=newLibrary(checkpoint);if(new URLSearchParams(location.search).get('test')==='book'){Object.assign(s,{x:539,y:220,phase:'chase',phoneAnswered:true,cameraX:319});s.worm.phase='crawl';s.worm.x=431;s.worm.y=211;s.book.falling=true;s.book.z=95;}previousPhase=s.phase;previousShots=0;previousJar=0;ambushPhases=[];running=true;release();$('#veil').hidden=true;$('#next-level').hidden=true;$('#pause').textContent='PAUSE';$('#dialog').hidden=true;inspector.sync();canvas.focus();if(!muted)audio.play().catch(()=>{});}
function pause(force){if(!running||['caught','escaped'].includes(s.phase))return;s.paused=force??!s.paused;release();$('#pause').textContent=s.paused?'RESUME':'PAUSE';if(s.paused){audio.pause();sound.pause();}else{sound.resume();if(!muted)audio.play().catch(()=>{});}}
function action(id){if(!running||s.paused)return;const result=libraryAction(s,id);if(result==='phone'){release();inspector.sync();}if(result==='book'){takeInstruction('book');release();showCollectedInstruction('book');}if(result==='exit')sound.tone(72,.25,.06);}
$('#start').onclick=()=>start();$('#restart').onclick=()=>{try{localStorage.removeItem('fright-house-library-v1');}catch{}start();};$('#retry').onclick=()=>start(s.phoneAnswered);$('#ready').onclick=()=>start(true);$('#pause').onclick=()=>pause();$('#action').onclick=()=>action();$('#continue').onclick=()=>$('#dialog').hidden=true;$('#sound').onclick=()=>{muted=!muted;sound.mute(muted);audio.muted=muted;$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';};
const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};window.addEventListener('keydown',e=>{if(s.inspection)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(map[k]||k===' ')e.preventDefault();if(e.repeat)return;if(k==='Escape')pause();else if(k==='e'||k===' ')action();else if(map[k]){keys.add(map[k]);route=[];pending=null;}});window.addEventListener('keyup',e=>keys.delete(map[e.key.length===1?e.key.toLowerCase():e.key]));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);route=[];pending=null;};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));}
canvas.onpointerdown=e=>{if(!running||s.paused||s.inspection)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*480/r.width+s.cameraX,y=(e.clientY-r.top)*360/r.height;if(s.book.landed&&!s.book.collected&&Math.hypot(x-s.book.x,y-s.book.y)<28){route=libraryPath(s,s.book.x,s.book.y);pending='book';if(Math.hypot(s.x-s.book.x,s.y-s.book.y)<35){action('book');pending=null;}return;}if(x>51&&x<112&&y>210&&y<300){const goal=s.x<92?{x:126,y:252}:{x:60,y:306};route=libraryPath(s,goal.x,goal.y);pending=null;return;}let o=LIBRARY_OBJECTS.find(o=>Math.hypot(o.x-x,o.y-y)<15);if(x>131&&x<163&&y>127&&y<160)o=LIBRARY_OBJECTS[0];if(x>402&&x<437&&y>119&&y<178&&s.phase!=='chase')o=LIBRARY_OBJECTS[1];if(x>1587&&x<1638&&y>25&&y<115&&s.exit<.9)o=LIBRARY_OBJECTS[2];const goal=o||{x,y};route=libraryPath(s,goal.x,goal.y);pending=o?.id||null;if(o&&libraryCanInteract(s,o)){action(o.id);pending=null;}};
function pool(x,y,r,color,alpha){ctx.save();ctx.globalAlpha=alpha;const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.restore();}
function render(){const quiet=['breaking','chase'].includes(s.phase);if(document.body.hasAttribute('data-quiet-notices')!==quiet)document.body.toggleAttribute('data-quiet-notices',quiet);ctx.clearRect(0,0,480,360);ctx.save();ctx.translate(-s.cameraX,0);ctx.drawImage(backdrop,0,0);for(const a of s.ambushes){if(['emerge','crawl','aim','spit'].includes(a.phase)){ctx.fillStyle='#b9c5a2';for(let i=0;i<8;i++)ctx.fillRect(a.x+Math.sin(i*2.4)*12,a.y+Math.cos(i*1.8)*5,2,1);}}for(const p of s.puddles){ctx.fillStyle=`rgba(103,135,31,${Math.max(0,.75-p.age*.2)})`;ctx.beginPath();ctx.ellipse(p.x,p.y,8,4,0,0,Math.PI*2);ctx.fill();}const ordered=[...layers.snapshot().layers.map(o=>({name:o.name,depth:o.depth})),{name:'player',depth:s.y},{name:'worm',depth:s.worm.y},...s.ambushes.filter(a=>['emerge','crawl','aim','spit'].includes(a.phase)).map(a=>({name:a.id,depth:a.y}))].sort((a,b)=>a.depth-b.depth);let lo=-Infinity;for(const o of ordered){props.drawRange(ctx,s,lo,o.depth);if(o.name==='player'){ctx.save();ctx.globalAlpha=s.invincible&&Math.floor(s.time*12)%2===0?.45:1;drawPlayer(ctx,s,s.moving&&!s.paused&&!s.inspection);ctx.restore();}else if(o.name==='worm')drawWorm(ctx,s.worm);else if(o.name.startsWith('jar-'))drawWorm(ctx,s.ambushes.find(a=>a.id===o.name));else layers.drawLayer(ctx,o.name);lo=o.depth;}props.drawRange(ctx,s,lo,Infinity);
for(const p of s.shots){pool(p.x,p.y-5,9,'#b3cb37',.45);ctx.fillStyle='#b4bc44';ctx.beginPath();ctx.ellipse(p.x,p.y-4,4,3,Math.atan2(p.vy,p.vx),0,Math.PI*2);ctx.fill();ctx.fillStyle='#e7e791';ctx.fillRect(p.x-1,p.y-6,2,2);}

const wave=.18+Math.sin(s.time*1.7)*.018+Math.sin(s.time*4.3)*.008;pool(220,142,67,'#bbd169',wave);for(const [x,y]of [[146,35],[312,35],[27,231]])pool(x,y,36,'#ecb158',.12+Math.sin(s.time*1.4+x)*.012);pool(383,20,22,'#d64032',.17);if(s.phase==='ringing'&&s.time%3<1){ctx.strokeStyle='#d1c18f';ctx.beginPath();ctx.arc(148,136,14,3.5,5.8);ctx.stroke();}
ctx.font='6px monospace';ctx.fillStyle='#9b8975';ctx.fillText('SEALED',369,115);for(const [i,x]of [500,700,910,1140,1380,1580].entries())pool(x,42,38,i%2?'#97b97a':'#d5ac60',.11+Math.sin(s.time*1.3+i)*.018);pool(1610,28,28,'#d74a39',.18);ctx.restore();
if(s.book.falling&&!s.book.collected){const b=s.book,x=b.x-s.cameraX;ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(x,b.y+3,10,3,0,0,7);ctx.fill();ctx.save();ctx.translate(x,b.y-b.z);ctx.rotate(b.landed?-.15:b.age*4);drawEvidence(ctx,{kind:'book'},0,0,1,true,s.time);ctx.restore();}
if(s.paused){ctx.fillStyle='#030609bb';ctx.fillRect(0,0,480,360);ctx.fillStyle='#ddc394';ctx.font='16px monospace';ctx.fillText('PAUSED',207,180);}$('#health').textContent='● '.repeat(Math.max(0,s.health))+'○ '.repeat(3-Math.max(0,s.health));$('#awake').textContent=s.phase==='ringing'?'PHONE RINGING':s.phase==='chase'?'SPECIMEN 087 · LOOSE':'THE LINE IS DEAD';$('#bolt').hidden=!s.unlocking&&!s.openingExit;$('#bolt').textContent=s.openingExit?'EXIT OPEN':'EXIT OPENS · '+Math.max(0,2.4-s.unlockAge).toFixed(1)+'s';$('#notice').textContent=s.noticeAge>0?s.notice:' ';$('#hint').textContent=!s.paused&&!s.inspection?(libraryNear(s)?.label||''):'';$('#objective').textContent=s.phase==='ringing'?'Pick up the ringing phone on the desk.':s.phase==='search'?'Find specimen 087 in the right-hand library.':s.phase==='chase'?'Run to the far end of the library. Dodge bile, weave around the shelves, then work the exit latch.':'Something is moving inside the glass.';}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running){let input=Object.fromEntries([...keys].map(k=>[k,true]));if(!keys.size&&route.length&&!s.paused&&!s.inspection){while(route.length&&Math.hypot(route[0].x-s.x,route[0].y-s.y)<.2)route.shift();if(route.length)input={target:route[0]};}tickLibrary(s,input,dt);if(!route.length&&pending){const id=pending;pending=null;action(id);}sound.tick(s);if(previousPhase!==s.phase){if(s.phase==='breaking'){route=[];pending=null;sound.tone(360,.2,.05);}previousPhase=s.phase;}if(s.jar===1&&previousJar<1)sound.glass();previousJar=s.jar;s.ambushes.forEach((a,i)=>{if(a.phase==='emerge'&&ambushPhases[i]!=='emerge')sound.glass();if(a.phase==='rattle'&&ambushPhases[i]!=='rattle')sound.tone(720,.3,.04);ambushPhases[i]=a.phase;});if(s.shotCount!==previousShots){sound.spit();previousShots=s.shotCount;}
if(['caught','escaped'].includes(s.phase)&&$('#veil').hidden){release();audio.pause();sound.pause();$('#veil').hidden=false;$('#veil h1').textContent=s.phase==='escaped'?'THE LIBRARY IS BEHIND YOU':'EATEN BY A BOOKWORM';$('#intro').textContent=s.phase==='escaped'?'The door slams. Something wet scrapes against the other side. Level 5 complete.':'Retry after the telephone call. Move sideways when the worm raises its head; the desk blocks its bile.';$('#start').textContent='RETRY AT LIBRARY';$('#start').onclick=()=>start(true);$('#next-level').hidden=s.phase!=='escaped';if(s.phase==='escaped'){leaveRoom('./level-6.html?arrival=library');remember(campaign,'specimen-087','Jar 087 broke. A human-faced worm crawled out and spat bile. I escaped through the red door.');try{localStorage.setItem('fright-house-2d-campaign-v1',saveCampaign(campaign));}catch{}}}}
if(bg.complete&&bg.naturalWidth&&props)render();inspector.sync();drawSecretsOverlay();requestAnimationFrame(frame);}
bg.onload=()=>{try{backdrop=createLibraryBackdrop(bg);props=createLibraryProps();layers=createForecourt(bg,libraryGeometry);$('#start').disabled=false;$('#start').textContent='ENTER THE LIBRARY';enterRoom(()=>start(new URLSearchParams(location.search).get('test')==='jar'),()=>{if(!s.paused&&!muted){audio.play().catch(()=>{});sound.resume();}});}catch(e){$('#intro').textContent='The 3D library could not start. Enable WebGL and reload.';console.error(e);}};bg.onerror=()=>$('#intro').textContent='The library artwork could not load. Reload to retry.';bg.src='./assets/library-clean.png';Object.defineProperty(window,'frightLibrary',{get:()=>({...structuredClone(s),running,route:route.length,render:props?.snapshot(),inspectionView:inspector.snapshot(),audio:sound.snapshot(),wormSpritesReady:wormReady(),foreground:layers?.snapshot()})});requestAnimationFrame(frame);
