import {SHELF_AMBUSHES,LIBRARY_AISLE_SHELVES} from './levels/library-model.js';
import {mergeGeometries} from '../vendor/addons/utils/BufferGeometryUtils.js';
import * as THREE from '../vendor/three.module.js';
import deskAsset from './assets/three/library-desk.js';import shelfAsset from './assets/three/specimen-library.js';import phoneAsset from './assets/three/library-phone.js';import doorAsset from './assets/three/archer-entry-door.js';
export function createLibraryProps(){const renderer=new THREE.WebGLRenderer({alpha:true,antialias:false});renderer.setSize(480,360,false);renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-240,240,180,-180,.1,2000);camera.position.z=1000;scene.add(new THREE.HemisphereLight(0xb3a080,0x191b17,1.4));const key=new THREE.DirectionalLight(0xffc47c,2.1);key.position.set(-200,300,450);scene.add(key);const glow=new THREE.PointLight(0xb9d863,600,100,1.4);glow.position.set(-21,47,70);scene.add(glow);const all=[];
function fit(body,x,y,w,h,rx=.28,ry=.05){const g=new THREE.Group(),posed=new THREE.Group();posed.add(body);posed.rotation.set(rx,ry,0);g.add(posed);posed.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(posed),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());posed.scale.set(w/size.x,h/size.y,h/size.y);posed.position.set(-center.x*posed.scale.x,-box.min.y*posed.scale.y,0);g.position.set(x-240,180-y,0);scene.add(g);const o={g,body,depth:y};all.push(o);return o;}
function shelf(){const body=shelfAsset(THREE),batches=new Map(),remove=[];body.updateMatrixWorld(true);body.traverse(m=>{if(!m.isMesh||m.material.transparent)return;const geometry=m.geometry.toNonIndexed().applyMatrix4(m.matrixWorld);if(!batches.has(m.material))batches.set(m.material,[]);batches.get(m.material).push(geometry);remove.push(m);});for(const m of remove)m.removeFromParent();for(const [mat,geometries]of batches){body.add(new THREE.Mesh(mergeGeometries(geometries),mat));for(const g of geometries)g.dispose();}return body;}

const desk=fit(deskAsset(THREE),188,208,140,88,.44,.03),phone=fit(phoneAsset(THREE),148,150,20,15,.48,.12),backA=fit(shelf(),180,117,101,104,.15,.04),backB=fit(shelf(),280,117,101,104,.15,-.04),right=fit(shelf(),449,162,34,134,.18,.58),display=fit(shelf(),362,265,94,49,.48,.05);phone.depth=208;phone.g.position.z=65;
const lowerRight=fit(shelf(),449,265,31,35,.3,.2);for(const [i,x]of [550,750,970,1190,1410,1530].entries())fit(shelf(),x,122,98+(i%3)*3,96+(i%2)*4,.16,(i%2?.035:-.035));for(const {x,y,w,h}of LIBRARY_AISLE_SHELVES)fit(shelf(),x,y,w,h,.4,.04);
const cabinet=fit(shelf(),35,198,29,71,.3,.2);
const source=shelfAsset(THREE),jarBody=source.userData.jars[5];jarBody.removeFromParent();jarBody.position.set(0,0,0);const jar=fit(jarBody,417,162,20,29,.2,.1);jar.depth=162;
const ambushJars=SHELF_AMBUSHES.map(a=>{const source=shelfAsset(THREE),body=source.userData.jars[5];body.removeFromParent();body.position.set(0,0,0);const o=fit(body,a.x,116,19,28,.2,.05);o.g.position.z=40;return o;});

fit(doorAsset(THREE,{frame:false}),379,110,39,82,0,0);const door=fit(doorAsset(THREE,{frame:false}),1610,110,43,84,0,0);const hinge=door.body.getObjectByName('hinge');
// Actual fragments fall from the same jar position used by the encounter.
const shards=[];const material=new THREE.MeshStandardMaterial({color:0xc5d8af,metalness:.25,roughness:.22,transparent:true,opacity:.75});for(let i=0;i<14;i++){const body=new THREE.Mesh(new THREE.ConeGeometry(.8+i%3*.2,2+i%4,3),material);body.rotation.z=i*1.7;scene.add(body);shards.push(body);}let calls=0,tris=0,peakCalls=0,peakTris=0;
return {drawRange(ctx,s,lo,hi){if(lo===-Infinity){calls=0;tris=0;}camera.position.x=s.cameraX;camera.updateMatrixWorld();const strength=.88+.06*Math.sin(s.time*1.7)+.025*Math.sin(s.time*4.3);glow.intensity=600*strength;key.intensity=1.65+Math.sin(s.time*.9)*.09;door.depth=s.exit>=.85?s.y-1:110;for(const o of all)o.g.visible=o.depth>=lo&&o.depth<hi;
phone.body.userData.setReceiver(s.receiver);phone.g.rotation.z=s.phase==='ringing'?Math.sin(s.time*44)*(s.time%3<1?.025:0):0;
for(let i=0;i<ambushJars.length;i++){const o=ambushJars[i],a=s.ambushes[i],fall=a.phase==='fall'?Math.min(1,a.age/.7):0;o.depth=116+fall*29;o.g.visible=['sealed','rattle','fall'].includes(a.phase)&&o.depth>=lo&&o.depth<hi;o.g.position.y=180-116-fall*29;o.g.rotation.z=a.phase==='rattle'?Math.sin(a.age*39)*.13:fall*1.5;}
hinge.rotation.y=-s.exit*1.55;jar.g.visible=jar.g.visible&&s.jar<1;jar.g.position.set(417-240-s.jar*7,180-162-s.jar*14,2);jar.g.rotation.z=-s.jar*1.3;
shards.forEach((p,i)=>{p.visible=s.jar===1&&176>=lo&&176<hi;const t=Math.min(1,Math.max(0,s.phase==='breaking'?s.phaseAge-1.1:1));p.position.set(410-240+Math.cos(i*2.4)*t*(6+i%4*3),180-176+Math.sin(i*2.4)*t*7+Math.sin(t*Math.PI)*9,2);p.rotation.z=i+t*4;});
renderer.render(scene,camera);calls+=renderer.info.render.calls;tris+=renderer.info.render.triangles;if(hi===Infinity){peakCalls=Math.max(calls,peakCalls);peakTris=Math.max(tris,peakTris);}ctx.drawImage(renderer.domElement,s.cameraX,0);},depths:[117,162,208,260,265],snapshot(){return {doorFramesVisible:false,desk3D:true,lamp3D:true,phone3D:true,shelves3D:16,specimenJars:101,drawCalls:peakCalls,triangles:peakTris};}};
}
