import {readInstructions,MACHINE_PAGES} from './campaign/instructions.js';
import {enterRoom,leaveRoom} from './room-flow.js';
import {newMezzanine,retryMezzanine,tickMezzanine,mezzPath,mezzAction,setMezzLever,engageMezzBrake,CONSOLES,ROWS,RIDDLES,steamVents} from './levels/mezzanine-model.js';import {createMezzanineProps,createMezzanineInspector} from './mezzanine-props.js';import {createFactorySound} from './factory-sound.js';import {drawPlayer} from './levels/temporary-player.js';import {newCampaign,loadCampaign,saveCampaign,remember} from './campaign/state.js';
const $=q=>document.querySelector(q),canvas=$('#game'),ctx=canvas.getContext('2d'),bg=new Image(),keys=new Set(),sound=createFactorySound();ctx.imageSmoothingEnabled=false;let s=newMezzanine(),running=false,last=performance.now(),route=[],pending=false,props,inspector,muted=false,lastHits=0;
function release(){keys.clear();route=[];pending=false;}function close(){s.inspection=false;$('#gate-inspection').close();release();if(!s.paused)sound.resume();canvas.focus();}function start(retry=false){const n=retry?retryMezzanine(s):newMezzanine();close();s=n;running=true;lastHits=0;release();sound.start();sound.reset();$('#veil').hidden=true;$('#next-level').hidden=true;$('#pause').textContent='PAUSE';canvas.focus();}
function pause(force){if(!running||s.phase!=='explore')return;s.paused=force??!s.paused;release();$('#pause').textContent=s.paused?'RESUME':'PAUSE';s.paused?sound.pause():sound.resume();}
const pagesButton=document.createElement('button');pagesButton.textContent='READ COLLECTED PAGES';pagesButton.onclick=()=>window.dispatchEvent(new Event('fright-read-instructions'));$('#riddle').after(pagesButton);
function inspect(){if(mezzAction(s)){release();$('#gate-inspection').showModal();sound.pause();$('#engage-brake').focus();}}
$('#start').onclick=()=>start();$('#retry').onclick=()=>start(true);$('#restart').onclick=()=>start();$('#pause').onclick=()=>pause();$('#action').onclick=inspect;$('#close-inspection').onclick=close;$('#gate-inspection').addEventListener('cancel',e=>{e.preventDefault();close();});for(const b of document.querySelectorAll('[data-lever]'))b.onclick=()=>setMezzLever(s,Number(b.dataset.lever));$('#engage-brake').onclick=()=>{const ok=engageMezzBrake(s);$('#wheel-result').textContent=ok?'LOCKED FOR 15 SECONDS. Cross before it releases.':s.notice;if(ok)close();};$('#sound').onclick=()=>{muted=!muted;sound.mute(muted);$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';};
const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};window.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(s.inspection){if(k==='e')close();return;}if(map[k]||k===' ')e.preventDefault();if(e.repeat)return;if(k==='Escape')pause();else if(k==='e'||k===' ')inspect();else if(map[k]){keys.add(map[k]);route=[];pending=false;}});window.addEventListener('keyup',e=>keys.delete(map[e.key.length===1?e.key.toLowerCase():e.key]));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);route=[];};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));}
canvas.onpointerdown=e=>{if(!running||s.paused||s.inspection||s.phase!=='explore')return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*480/r.width+s.cameraX,y=(e.clientY-r.top)*360/r.height+s.cameraY;const o=CONSOLES.find((o,i)=>i<=s.stage&&!s.banks[i].completed&&Math.hypot(o.x-x,o.y-15-y)<34);route=mezzPath(s,(o||{x}).x,(o||{y}).y);pending=!!o;if(o&&Math.hypot(s.x-o.x,s.y-o.y)<o.r){pending=false;inspect();}};
function render(){ctx.clearRect(0,0,480,360);ctx.save();ctx.translate(-s.cameraX,-s.cameraY);ctx.drawImage(bg,0,0,720,480);ctx.restore();props.draw(ctx,s,false);ctx.save();ctx.translate(-s.cameraX,-s.cameraY);if(!s.scarf){ctx.strokeStyle='#9b2c38';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(497,218);ctx.lineTo(505,226);ctx.lineTo(500,234);ctx.stroke();}if(running){ctx.globalAlpha=s.invincible&&Math.floor(s.time*12)%2===0?.5:1;drawPlayer(ctx,s,s.moving&&!s.paused&&!s.inspection);ctx.globalAlpha=1;}ctx.restore();props.draw(ctx,s,true);ctx.save();ctx.translate(-s.cameraX,-s.cameraY);for(const v of steamVents(s)){if(v.active){for(let i=0;i<18;i++){const a=(v.phase-.9+i*.037)% .7,r=4+a*11,x=v.x+Math.sin(i*2.1+s.time*3)*a*12,y=v.y-a*61;ctx.fillStyle=`rgba(198,208,191,${(1-a/.7)*.25})`;ctx.beginPath();ctx.ellipse(x,y,r,r*.7,0,0,7);ctx.fill();}}}for(let i=0;i<3;i++){const o=CONSOLES[i];ctx.fillStyle=s.banks[i].timer>0||s.banks[i].completed?'#a2bc77':'#c05536';ctx.fillRect(o.x-2,o.y-39,4,3);}ctx.restore();if(s.paused){ctx.fillStyle='#040608bb';ctx.fillRect(0,0,480,360);ctx.fillStyle='#ead7ad';ctx.font='16px monospace';ctx.fillText('PAUSED',207,178);}
$('#health').textContent='● '.repeat(Math.max(0,s.health))+'○ '.repeat(3-Math.max(0,s.health));$('#warning').textContent=`STAGE ${Math.min(3,s.stage+1)} / 3`;const bank=s.banks[Math.min(2,s.stage)];$('#gate-status').textContent=s.stage===3?'WORKSHOP OPEN':bank.timer>0?`BRAKE · ${Math.ceil(bank.timer)}s`:'BRAKE RELEASED';$('#notice').textContent=s.noticeAge>0?s.notice:' ';$('#objective').textContent=s.stage===3?'Climb to the workshop door.':'Set the three levers, engage the brake, then cross between steam bursts.';$('#hint').textContent=!s.inspection&&s.stage<3&&Math.hypot(s.x-CONSOLES[s.stage].x,s.y-CONSOLES[s.stage].y)<33?'E · BRAKE CONSOLE':'';
if(s.inspection){inspector.draw(s);$('#riddle').textContent=readInstructions().includes(MACHINE_PAGES[s.inspected].id)?'Refer to the maintenance page in your INSTRUCTIONS.':'The instruction plate is missing. Its page was hidden elsewhere in the house.';for(const b of document.querySelectorAll('[data-lever]')){const i=Number(b.dataset.lever);b.textContent=['FEED','DRIVE','VENT'][i]+' '+s.banks[s.inspected].settings[i];}$('#engage-brake').disabled=s.paused;}}
function finish(){release();sound.pause();$('#veil').hidden=false;const won=s.phase==='escaped';$('#veil h1').textContent=won?'THE WORKSHOP WAITS':'THE FLOOR TAKES YOU';$('#intro').textContent=won?'The machinery trembles behind you. Beyond the workshop door, something answers its rhythm. Level 7 complete.':'Retry from the last fixed landing. Set the levers and wait for the steam to subside.';$('#start').textContent=won?'PLAY AGAIN':'RETRY LANDING';$('#start').onclick=()=>start(!won);$('#next-level').hidden=!won;if(won){leaveRoom('./level-8.html?arrival=mezzanine');let c;try{c=loadCampaign(localStorage.getItem('fright-house-2d-campaign-v1'));}catch{}c||=newCampaign();c.area='mezzanine';remember(c,'mezzanine-scarf',s.scarf?'A red scarf was caught in the machinery. The footprints continued to the workshop.':'The moving floor led to a workshop. Something inside tapped in time with the machines.');try{localStorage.setItem('fright-house-2d-campaign-v1',saveCampaign(c));}catch{}}}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running){let input=Object.fromEntries([...keys].map(k=>[k,true]));if(!keys.size&&route.length&&!s.paused&&!s.inspection){const p=route[0];if(Math.hypot(p.x-s.x,p.y-s.y)<.25)route.shift();else input={target:p};}tickMezzanine(s,input,dt);if(s.hits!==lastHits){lastHits=s.hits;release();}if(!route.length&&pending&&!s.paused){pending=false;inspect();}sound.tick(s);if(s.phase!=='explore'&&$('#veil').hidden)finish();}if(props&&bg.complete)render();requestAnimationFrame(frame);}
bg.onload=()=>{try{props=createMezzanineProps();inspector=createMezzanineInspector($('#gate-view'));$('#start').disabled=false;$('#start').textContent='ENTER THE MEZZANINE';enterRoom(()=>start(),()=>{if(!s.paused)sound.resume();});}catch(e){$('#intro').textContent='The 3D room could not load. Enable WebGL and reload.';console.error(e);}};bg.onerror=()=>$('#intro').textContent='The artwork could not load. Reload to retry.';bg.src='./assets/mezzanine-clean.png';Object.defineProperty(window,'frightMezzanine',{get:()=>({...structuredClone(s),running,route:route.length,render:props?.snapshot(),audio:sound.snapshot()})});requestAnimationFrame(frame);
