import {PLAYER_DRAW_HEIGHT} from './levels/platform-layout.js';
import {archerOrigin} from './levels/platform-ambush.js';
import {createPowerInspection} from './power-inspection.js';
import {STAIR_PATHS} from './levels/platform-stairs.js';
import {newPlatform,tickPlatform,platformAction,retryPlatform,answerPowerRiddle,pullPowerLever,closePowerInspection,FLOOR_Y,STAIRS,platforms,hazards} from './levels/platform-model.js';
import {createPlatformProps} from './platform-props.js';
import {drawPlayer,preloadJumpSprites} from './levels/temporary-player.js';
preloadJumpSprites();
const $=q=>document.querySelector(q),canvas=$('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;const SAVE='fright-house-platform-v1';let saved=0;try{saved=Number(localStorage.getItem(SAVE))||0;}catch{}let s=newPlatform(saved),running=false,last=performance.now(),keys=new Set(),pendingJump=false,props=null,muted=false,ac=null;const bg=new Image();const ambience=new Audio('../audio/ambience.mp3');ambience.loop=true;ambience.volume=.14;let previousFloor=s.floor,previousHits=0,previousAttack='';
const inspection=createPowerInspection({getState:()=>s,answer:value=>{answerPowerRiddle(s,value);beep(value==='clock'?280:75,.12);},pull:()=>{if(pullPowerLever(s))beep(120,.4);},close:()=>{closePowerInspection(s);release();inspection.sync();canvas.focus();}});
function beep(freq=150,duration=.12){if(muted)return;try{ac||=new AudioContext();ac.resume();const o=ac.createOscillator(),g=ac.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,ac.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.45,ac.currentTime+duration);g.gain.setValueAtTime(.045,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+duration);}catch{}}
function release(){keys.clear();pendingJump=false;}function save(){try{localStorage.setItem(SAVE,String(s.checkpoint));}catch{}}
function start(floor=null){if(floor!==null)s=newPlatform(floor);else if(s.status==='escaped')s=newPlatform();else if(s.status!=='playing')retryPlatform(s);running=true;s.paused=false;release();$('#veil').hidden=true;$('#pause').textContent='PAUSE';if(!muted)ambience.play().catch(()=>{});ac?.resume();canvas.focus();save();}
function pause(force){if(!running||s.status!=='playing')return;s.paused=force??!s.paused;release();$('#pause').textContent=s.paused?'RESUME':'PAUSE';if(s.paused){ambience.pause();ac?.suspend();}else if(!muted){ambience.play().catch(()=>{});ac?.resume();}}
function action(){if(!running||s.paused)return;platformAction(s);if(s.inspection)release();inspection.sync();}
$('#start').onclick=()=>start();$('#pause').onclick=()=>pause();$('#retry').onclick=()=>{retryPlatform(s);start();};$('#restart').onclick=()=>start(0);$('#load').onclick=()=>start(Number($('#checkpoint').value));$('#action').onclick=action;$('#flash').onclick=()=>{if(running&&!s.paused&&!s.inspection){keys.add('flash');setTimeout(()=>keys.delete('flash'),100);}};$('#sound').onclick=()=>{muted=!muted;ambience.muted=muted;if(muted)ac?.suspend();else if(!s.paused)ac?.resume();$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';};
const keyMap={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',' ':'jump',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',f:'flash'};window.addEventListener('keydown',e=>{if(s.inspection)return;if(keyMap[e.key]||e.key==='Escape')e.preventDefault();if(e.repeat)return;if(e.key==='Escape')pause();else if(e.key.toLowerCase()==='e')action();else if(keyMap[e.key]){keys.add(keyMap[e.key]);if(keyMap[e.key]==='jump')pendingJump=true;}});window.addEventListener('keyup',e=>keys.delete(keyMap[e.key]));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});for(const b of document.querySelectorAll('[data-input]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.input);if(b.dataset.input==='jump')pendingJump=true;};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.input));}
function text(txt,x,y,color='#f0d19c',size=11){ctx.font=`bold ${size}px Courier New`;ctx.textAlign='center';ctx.fillStyle='#08090bed';ctx.fillRect(x-ctx.measureText(txt).width/2-5,y-size-2,ctx.measureText(txt).width+10,size+7);ctx.fillStyle=color;ctx.fillText(txt,x,y);}
function glow(x,y,color,r=25,strength=.2){const g=ctx.createRadialGradient(x,y,1,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.globalAlpha=strength;ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.globalAlpha=1;}
function render(){ctx.drawImage(bg,0,0,960,720);props.drawBackground(ctx,s);
 // Original staircase/rail is in front of the recessed service doorway.
 ctx.save();ctx.beginPath();ctx.moveTo(778,622);ctx.lineTo(897,520);ctx.lineTo(911,579);ctx.lineTo(788,682);ctx.closePath();ctx.clip();ctx.drawImage(bg,0,0,960,720);ctx.restore();
 // Scenery is a backdrop. These separately rendered platforms form the traversable surfaces.
 if(s.floor===2){ctx.fillStyle='#080a0e';ctx.fillRect(528,FLOOR_Y[2]-8,239,22);for(const p of platforms(s)){ctx.strokeStyle='#625139';ctx.lineWidth=2;for(const x of [p.x+9,p.x+p.w-9]){ctx.beginPath();ctx.moveTo(x,283);ctx.lineTo(x,p.y);ctx.stroke();}}}
 for(const [i,x,y]of [[0,145,47],[1,714,47],[2,134,226],[3,260,217],[4,591,242],[5,650,226],[6,81,386],[7,277,392],[8,259,523],[9,693,527]])glow(x,y,i%3?'#ffbd52':'#e83237',32,.24+.1*Math.sin(s.time*2+i));
 if(s.power){ctx.fillStyle='#ac242422';ctx.fillRect(0,0,960,720);}if(s.floor===3){const x=s.chaser;for(let i=0;i<9;i++){ctx.fillStyle=`rgba(4,5,8,${.36+i*.04})`;ctx.beginPath();ctx.ellipse(x+i*7,FLOOR_Y[3]-25+Math.sin(s.time*4+i)*5,20,29,0,0,7);ctx.fill();}ctx.fillStyle='#edcbb1';ctx.fillRect(x-9,FLOOR_Y[3]-38,3,3);ctx.fillRect(x,FLOOR_Y[3]-38,3,3);}
 if(s.floor===2){for(const p of s.spiders){ctx.fillStyle='#090a0b';ctx.beginPath();ctx.ellipse(p.nest,FLOOR_Y[2]-4,12,5,0,0,7);ctx.fill();if(p.phase==='warning'){glow(p.nest,FLOOR_Y[2]-10,'#d9a15d',17,.35);ctx.strokeStyle='#edb572';ctx.beginPath();ctx.ellipse(p.target,FLOOR_Y[2]-1,15,4,0,0,7);ctx.stroke();}}}
 if(s.power&&s.ambush){const a=s.ambush.archer;if(s.floor>0&&a.phase==='aim'){const o=archerOrigin(s.floor,s.clown);ctx.save();ctx.strokeStyle='#e9ac7399';ctx.lineWidth=2;ctx.setLineDash([5,8]);ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.quadraticCurveTo(o.x,FLOOR_Y[s.floor]-180,a.targetX,a.targetY);ctx.stroke();ctx.restore();text('ARROW · MOVE',a.targetX,FLOOR_Y[s.floor]-62,'#e6a16c');}for(const b of s.ambush.balloons){if(b.phase==='fuse'){glow(b.x,b.y,'#ff733c',40,.25+.18*Math.sin(b.age*20));ctx.strokeStyle='#dc915f';ctx.beginPath();ctx.ellipse(b.x,FLOOR_Y[s.floor]-2,38,5,0,0,7);ctx.stroke();text('POP IN '+Math.max(0,1.6-b.age).toFixed(1),b.x,b.y-33,'#efb579');}if(b.phase==='blast'){glow(b.x,FLOOR_Y[s.floor]-10,'#ffb461',48,1-b.age/.3);for(let i=0;i<10;i++){const angle=i*.628,dist=b.age*150;ctx.fillStyle=i%2?'#b9422d':'#ead290';ctx.fillRect(b.x+Math.cos(angle)*dist,FLOOR_Y[s.floor]-10+Math.sin(angle)*dist,4,4);}}}}
 props.draw(ctx,s);for(const h of hazards(s)){if(h.warning)text(h.kind==='spider'?'SKITTER…':h.kind==='barrel'?'⚠ BARREL →':'⚠ PRESS',h.kind==='barrel'?120:h.x,h.y-29,'#edab64');}
 if(s.floor<3&&!s.fuses.includes(s.floor)){const x=[450,410,480][s.floor],y=FLOOR_Y[s.floor]-18;glow(x,y,'#f7cf67',23,.6);ctx.fillStyle='#dcc271';ctx.fillRect(x-4,y-7,8,12);ctx.fillStyle='#745732';ctx.fillRect(x-3,y-4,6,6);}
 if(s.floor===0){glow(360,580,s.power?'#81ac75':'#e4be7b',28,.22);text(s.power?'E · MAINS ON':'E · WALL RIDDLE',360,549);}
 ctx.save();ctx.translate(s.x,s.y);ctx.globalAlpha=s.invincible&&Math.floor(s.time*12)%2===0?.65:1;drawPlayer(ctx,{...s,x:0,y:0,spriteHeight:PLAYER_DRAW_HEIGHT},Math.abs(s.vx)>0&&s.grounded&&!s.paused&&!s.inspection&&s.status==='playing');ctx.restore();if(s.flash>0){ctx.fillStyle=`rgba(232,239,244,${s.flash*.9})`;ctx.fillRect(0,0,960,720);}
 if(s.paused){ctx.fillStyle='#06070bcc';ctx.fillRect(0,0,960,720);text('PAUSED',480,360,'#eed6af',24);}const stair=STAIRS[s.floor];if(stair)text('↑ · WALK UP',stair.x,FLOOR_Y[s.floor]-34);if(s.floor>0){const a=STAIR_PATHS[s.floor-1],top=a.points.at(-1);text('↓ · WALK DOWN',top[0],top[1]-40);}if(s.floor===3)text('E · EXIT',145,148,'#b7d99c');
 $('#health').textContent='● '.repeat(s.health)+'○ '.repeat(3-s.health);$('#floor').textContent='FLOOR '+(s.floor+1)+' / 4';$('#fuses').textContent='FUSES '+s.fuses.length+' / 3';$('#notice').textContent=s.noticeAge>0?s.notice:' ';$('#objective').textContent=['Solve the wall riddle, pull the red lever, then walk up the right stairs.','Run left. Dodge arrows and bomb balloons. Jump the barrels and motor. Collect the fuse and climb the left stairs.','Dodge arrows, bomb balloons and spiders, then cross the moving floor.','RUN LEFT TO THE EXIT. F / FLASH pushes the shadow back.'][s.floor];$('#hint').textContent=s.floor===3?'FLASH '+(s.cooldown>0?s.cooldown.toFixed(1)+'s':'READY'):(s.stair?'↑ / ↓ · CLIMB OR REVERSE · RELEASE TO STOP':'');}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running){const input=Object.fromEntries([...keys].map(k=>[k,true]));if(pendingJump)input.jump=true;tickPlatform(s,input,dt);pendingJump=false;if(s.floor!==previousFloor){previousFloor=s.floor;save();beep(330,.2);}const attack=s.ambush.archer.shots+':'+s.ambush.balloons.map(b=>b.phase).join();if(attack!==previousAttack){if(s.ambush.balloons.some(b=>b.phase==='blast'))beep(65,.28);else if(s.ambush.archer.phase==='release')beep(480,.1);previousAttack=attack;}if(s.hits!==previousHits){previousHits=s.hits;beep(80,.25);}if(s.status!=='playing'&&$('#veil').hidden){release();ambience.pause();$('#veil').hidden=false;$('#veil h1').innerHTML=s.status==='escaped'?'YOU MADE IT<br>UPSTAIRS':'CAUGHT IN<br>THE MACHINERY';$('#intro').textContent=s.status==='escaped'?'Three fuses. A trail through the attraction. The upper exit opens into an abandoned toy storeroom.':'Retry from the last safe landing. Watch the warning lamps and use your jump.';$('#start').textContent=s.status==='escaped'?'ENTER LEVEL 4':'RETRY CHECKPOINT';$('#start').onclick=s.status==='escaped'?()=>location.href='./level-4.html?arrival=upper':()=>start();}}if(bg.complete&&bg.naturalWidth&&props)render();inspection.sync();requestAnimationFrame(frame);}
bg.onload=()=>{try{props=createPlatformProps();$('#start').disabled=false;$('#start').textContent=saved?'CONTINUE FROM LANDING':'ENTER THE ATTRACTION';const floor=new URLSearchParams(location.search).get('floor');if(floor!==null&&/^[0-3]$/.test(floor))start(Number(floor));}catch(e){$('#error').hidden=false;$('#error').textContent='The 3D renderer could not start. Enable WebGL and reload.';console.error(e);}};bg.onerror=()=>{$('#error').hidden=false;$('#error').textContent='The level artwork could not load. Reload to retry.';};bg.src='./assets/platform-clean.png';Object.defineProperty(window,'frightPlatform',{get:()=>({...structuredClone(s),running,hazards:hazards(s),platforms:platforms(s),render:props?.snapshot(),inspectionView:inspection.snapshot()})});requestAnimationFrame(frame);
