import {CLOWN_DRAW_HEIGHT} from './levels/platform-layout.js';
import {clownSpritesReady,drawClowns} from './clown-sprites.js';
import entryDoor from './assets/three/archer-entry-door.js';import {clownEntrance} from './levels/clown-entrance.js';
import machinery from './assets/three/backstage-machinery.js';import {machineryPose} from './levels/machinery-motion.js';
import * as THREE from '../vendor/three.module.js';
import generate from './assets/three/attraction-obstacles.js';
import spider from './assets/three/leaping-spider.js';
import clown from './assets/three/clown-archer.js';
import bomb from './assets/three/balloon-bomb.js';
import arrow from './assets/three/carnival-arrow.js';
import {archerOrigin,newAmbush,balloonY} from './levels/platform-ambush.js';
import wallLever from './assets/three/wall-power-lever.js';
import {FLOOR_Y,POWER_LEVER,SOLIDS,platforms,hazards} from './levels/platform-model.js';
export function createPlatformProps(){const renderer=new THREE.WebGLRenderer({alpha:true,antialias:false});renderer.setSize(480,360,false);renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-480,480,360,-360,.1,2000);camera.position.set(0,0,1000);scene.add(new THREE.HemisphereLight(0xd7c5ad,0x252e30,2));const key=new THREE.DirectionalLight(0xffc88b,2.8);key.position.set(-300,500,800);scene.add(key);const source={entryDoor:entryDoor(THREE),...generate(THREE).userData.parts,spider:spider(THREE),lever:wallLever(THREE),clown:clown(THREE),bomb:bomb(THREE),arrow:arrow(THREE)},objects=new Map();const machine=machinery(THREE);machine.scale.setScalar(79);machine.position.set(435-480,360-124,0);scene.add(machine);let machinePose=machineryPose(0,false),backgroundCalls=0,backgroundTriangles=0,previousState=null,previousTime=-1;let floorAmbushes=Array.from({length:4},(_,i)=>newAmbush(i));
function put(id,type,x,y,w,h,rotation=0){let m=objects.get(id);if(!m){m=new THREE.Group();const body=source[type].clone(true);body.position.set(0,0,0);m.add(body);m.userData.body=body;scene.add(m);objects.set(id,m);}m.visible=true;m.rotation.z=0;m.position.set(0,0,0);const b=m.userData.body;b.rotation.set(0,0,0);b.scale.set(1,1,1);b.position.set(0,0,0);if(type==='barrel'){b.rotation.z=Math.PI/2;b.rotation.x=rotation;}else b.rotation.y=type==='spider'?.7:.12;if(type==='entryDoor')b.getObjectByName('hinge').rotation.y=-rotation*1.3;if(type==='arrow')m.rotation.z=-rotation;if(type==='clown'){b.rotation.y=x>480?-.65:.65;b.getObjectByName('bow-arm').rotation.z=-.7-rotation*.55;b.getObjectByName('draw-arm').rotation.z=.65+rotation*.5;b.getObjectByName('bow').rotation.z=.8;b.getObjectByName('head').rotation.z=-.1-rotation*.12;}if(type==='lever')b.getObjectByName('lever-pivot').rotation.x=.2+rotation*2.4;if(type==='spider'){b.traverse(node=>{if(node.name.startsWith('leg-'))node.rotation.x=Math.sin(rotation+Number(node.name.at(-1))*1.7)*.3;});}const doorAngle=type==='entryDoor'?b.getObjectByName('hinge').rotation.y:0;if(type==='entryDoor')b.getObjectByName('hinge').rotation.y=0;b.updateWorldMatrix(true,true);const bounds=new THREE.Box3().setFromObject(b),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());b.scale.set(w/size.x,h/size.y,Math.min(w,h)/Math.max(size.z,.1));b.position.set(-center.x*b.scale.x,-bounds.min.y*b.scale.y,0);if(type==='entryDoor')b.getObjectByName('hinge').rotation.y=doorAngle;m.position.set(x-480,360-y,0);}
return {drawBackground(ctx,s){for(const o of objects.values())o.visible=false;const entrance=clownEntrance(s);put('archer-door','entryDoor',832,661,52,99,entrance.door);machine.visible=true;machinePose=machineryPose(s.time,s.power);for(const name of ['flywheel','idler','drive','pulley','crank'])machine.getObjectByName(name).rotation.z=machinePose[name];machine.getObjectByName('piston').position.y=machinePose.piston;for(let i=0;i<24;i++){const a=i*Math.PI*2/24+machinePose.beltPhase,b=machine.getObjectByName('belt-'+i);b.position.x=.05+.27*Math.cos(a);b.position.y=.72+.48*Math.sin(a);b.rotation.z=-a;}renderer.render(scene,camera);backgroundCalls=renderer.info.render.calls;backgroundTriangles=renderer.info.render.triangles;ctx.save();ctx.beginPath();ctx.rect(799,558,70,108);ctx.clip();ctx.drawImage(renderer.domElement,0,0,960,720);ctx.restore();ctx.save();ctx.beginPath();for(const [x,w] of [[300,93],[404,73],[489,69]])ctx.rect(x,36,w,80);ctx.clip();ctx.fillStyle='#101918';ctx.fillRect(295,32,270,90);ctx.drawImage(renderer.domElement,0,0,960,720);const shade=ctx.createLinearGradient(0,36,0,116);shade.addColorStop(0,'#05090799');shade.addColorStop(.45,'#95622c18');shade.addColorStop(1,'#05090780');ctx.fillStyle=shade;ctx.fillRect(295,32,270,90);ctx.restore();machine.visible=false;},draw(ctx,s){for(const o of objects.values())o.visible=false;const entrance=clownEntrance(s);// Fixed room fixtures stay visible on every landing, before and after power.
if(previousState!==s||s.time<previousTime)floorAmbushes=Array.from({length:4},(_,i)=>newAmbush(i));previousState=s;previousTime=s.time;floorAmbushes[s.floor]=s.ambush;
put('wall-power','lever',POWER_LEVER.x,POWER_LEVER.y,25,39,s.lever);
for(const o of SOLIDS){const opened=o.id==='gate'?Math.min(1,(s.powerAge||0)/.7):o.id==='exit-gate'?Math.min(1,(s.exitGateAge||0)/.7):0;put(o.id,o.id.includes('gate')?'press':'crate',o.x+o.w/2,FLOOR_Y[o.floor]-opened*(o.h+10),o.w,o.h);}
for(const p of platforms(s))put(p.id,'lift',p.x+p.w/2,p.y+7,p.w,13);
for(const ambush of floorAmbushes)for(const b of ambush.balloons)if(['idle','fuse'].includes(b.phase))put(b.id,'bomb',b.x,(ambush===s.ambush?b.y:balloonY(ambush.floor,s.time))+24,23,48);
if(s.power&&s.ambush){const a=s.ambush.archer;if(s.floor>0&&!clownSpritesReady()){const origin=archerOrigin(s.floor);put('clown-archer','clown',origin.x,FLOOR_Y[s.floor-1],48,CLOWN_DRAW_HEIGHT,a.phase==='aim'?Math.min(1,a.age/1.15):0);}}
const current=hazards(s);const barrel=current.find(h=>h.kind==='barrel')||{x:69,y:FLOOR_Y[1]-14,r:14};put('barrel','barrel',barrel.x,barrel.y+barrel.r,28,28,s.floor===1?s.floorTime*8:0);
const press=current.find(h=>h.kind==='press')||{x:350,y:FLOOR_Y[3]-66,r:19};put('press','press',press.x,press.y+press.r,38,38);
for(const p of s.spiders)put(p.id,'spider',p.x,p.y+9,30,18,p.phase==='hidden'?0:s.floorTime*8);
renderer.render(scene,camera);ctx.drawImage(renderer.domElement,0,0,960,720);drawClowns(ctx,s);},snapshot(){return {drawCalls:renderer.info.render.calls+backgroundCalls,triangles:renderer.info.render.triangles+backgroundTriangles,machinery:{real3D:true,behindWall:true,...machinePose},objects:[...objects].filter(([,m])=>m.visible).map(([id])=>id)};}};}
