let paintOverlay=()=>{};
export function drawSecretsOverlay(){paintOverlay(performance.now());}
import {SECRETS,readEvidence,collectEvidence} from './campaign/secrets.js';
import {drawEvidence} from './evidence-icons.js';
export function installSecrets(){const game=document.querySelector('#game'),stage=document.querySelector('#stage');if(!game||!stage)return;const match=location.pathname.match(/level-(\d+)/),level=match?+match[1]:1;const hud=document.querySelector('#hud');if(hud){const old=hud.lastElementChild;if(old&&!old.matches('#health,.hud-center'))old.style.setProperty('display','none','important');const counter=document.createElement('span');counter.id='secret-count';counter.style.cssText='margin-left:auto;white-space:nowrap';counter.setAttribute('aria-label','Secret items collected');hud.append(counter);const sync=()=>{counter.textContent=`SECRETS ${readEvidence().length} / ${SECRETS.length}`;};sync();window.addEventListener('fright-evidence',sync);window.addEventListener('storage',sync);}if(level>11)return;const item=SECRETS.find(i=>i.level===level),globals=['','fright2d','fright2d','frightPlatform','frightStore','frightLibrary','frightBarrelRun','frightMezzanine','frightWorkshop','frightFall','frightFinale','frightFinale'];const overlay=document.createElement('canvas');overlay.id='secret-items-overlay';overlay.width=game.width;overlay.height=game.height;overlay.style.cssText='position:absolute;pointer-events:none;z-index:2;image-rendering:pixelated';overlay.setAttribute('aria-hidden','true');stage.append(overlay);const c=overlay.getContext('2d');const pocket=document.createElement('button');pocket.textContent='POCKETS';document.querySelector('footer div')?.append(pocket);const modal=document.createElement('dialog');modal.id='pockets-menu';modal.style.cssText='background:#090a0b;color:#eee;border:2px solid #ddd;max-width:440px;font:18px FrightPixel,monospace';const title=document.createElement('h2');title.textContent='COAT POCKETS';const list=document.createElement('div'),close=document.createElement('button');close.textContent='CLOSE';modal.append(title,list,close);document.body.append(modal);let near=false,pausedByUs=false;
function available(s=window[globals[level]]){return !!s?.running&&!s.paused&&!s.dialog&&s.inspection!==true&&!s.inspection?.open&&!s.inspection?.active&&!document.querySelector('dialog[open]')&&!readEvidence().includes(item.id)&&(!item.drawer||s.drawer)&&!['caught','escaped','complete'].includes(s.phase||s.status)&&(level!==11||s.phase==='ride')&&(level!==9||s.phase==='fall');}
function pickup(){const s=window[globals[level]],p=s?.cart?{x:s.cart.x+s.cart.lane,y:s.cart.y}:s;if(!available(s)||Math.hypot(p.x-item.x,p.y-item.y)>=(item.contact?32:35)||!collectEvidence(item.id))return false;near=false;window.dispatchEvent(new CustomEvent('fright-story',{detail:{text:item.text,speaker:'DETECTIVE'}}));window.dispatchEvent(new CustomEvent('fright-evidence',{detail:item.id}));return true;}
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e'&&!e.repeat&&!document.querySelector('#story-overlay:not([hidden]),#dialog:not([hidden])')&&pickup()){e.preventDefault();e.stopImmediatePropagation();}},true);
// The touch action button has the same pickup priority as the keyboard's E key.
// Consume only a successful pickup so doors, puzzles, books and combat still work.
document.addEventListener('click',e=>{if(e.target.closest?.('#action')&&pickup()){e.preventDefault();e.stopImmediatePropagation();}},true);
pocket.onclick=()=>{const s=window[globals[level]],items=readEvidence();pausedByUs=!!s?.running&&!s.paused;if(pausedByUs){modal.dataset.keepMusic='true';document.querySelector('#pause')?.click();}list.replaceChildren();if(!items.length)list.textContent='Nothing in here yet.';for(const id of items){const def=SECRETS.find(x=>x.id===id),p=document.createElement('p');p.textContent=def.name+' — '+def.text;list.append(p);}modal.showModal();};close.onclick=()=>modal.close();modal.addEventListener('close',()=>{if(pausedByUs)document.querySelector('#pause')?.click();delete modal.dataset.keepMusic;pausedByUs=false;});
function frame(time){const rect=game.getBoundingClientRect(),base=stage.getBoundingClientRect();Object.assign(overlay.style,{left:(rect.left-base.left)+'px',top:(rect.top-base.top)+'px',width:rect.width+'px',height:rect.height+'px'});c.clearRect(0,0,overlay.width,overlay.height);const s=window[globals[level]];near=false;if(!available(s))return;const p=s.cart?{x:s.cart.x+s.cart.lane,y:s.cart.y}:s,cx=s.cameraX||0,cy=s.cameraY||0;drawEvidence(c,item,item.x-cx,item.y-cy,level===3?1.5:1,true,time/1000);near=Math.hypot(p.x-item.x,p.y-item.y)<(item.contact?32:35);if(near&&item.contact)pickup();}paintOverlay=frame;Object.defineProperty(window,'frightSecrets',{get:()=>({items:readEvidence(),level,item:item.id,near})});}
