import {newStore,retryStore,STORE_OBJECTS,storeAction,storeNear,storePath,windStoreToy,closeStoreInspection,tickStore} from './levels/toystore-model.js';import {createStoreProps} from './toystore-props.js';import {createStoreInspection} from './store-inspection.js';import {createForecourt} from './forecourt.js';import geometry from './toystore-geometry.js';import {drawPlayer} from './levels/temporary-player.js';import {newCampaign,loadCampaign,saveCampaign,remember} from './campaign/state.js';
const $=q=>document.querySelector(q),canvas=$('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;let s=newStore(),running=false,props,layers,last=performance.now(),keys=new Set(),route=[],pending=null,dialog=false,muted=false,ac=null,previousPhase='explore',lastNote=-1;const bg=new Image(),mask=document.createElement('canvas');mask.width=480;mask.height=360;const mx=mask.getContext('2d');const audio=new Audio('../audio/ambience.mp3');audio.loop=true;audio.volume=.12;const checkpointKey='fright-house-toystore-v1',campaignKey='fright-house-2d-campaign-v1';let campaign;try{campaign=loadCampaign(localStorage.getItem(campaignKey));}catch{}campaign||=newCampaign();campaign.area='toy-store';campaign.paused=false;campaign.story=null;
function rememberDrawing(){remember(campaign,'toy-drawing','The children drew the same little wind-up rabbit. Under it: “They wake up when the song stops.”');try{localStorage.setItem(campaignKey,saveCampaign(campaign));}catch{}}
function tone(f=220,d=.12,volume=.035){if(muted)return;try{ac||=new AudioContext();ac.resume();const o=ac.createOscillator(),g=ac.createGain();o.type='triangle';o.frequency.setValueAtTime(f,ac.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(25,f*.82),ac.currentTime+d);g.gain.setValueAtTime(volume,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+d);}catch{}}
function release(){keys.clear();route=[];pending=null;}function checkpoint(){try{localStorage.setItem(checkpointKey,'ready');}catch{}}
const inspector=createStoreInspection({state:()=>s,wind:()=>{if(windStoreToy(s)){tone(520-s.turns*70,.16);if(!s.inspection){release();inspector.sync();canvas.focus();}}},close:()=>{closeStoreInspection(s);release();inspector.sync();canvas.focus();}});
function dismiss(){dialog=false;$('#dialog').hidden=true;release();}function start(prepared=false){s=prepared?retryStore():newStore();previousPhase='explore';lastNote=-1;running=true;dismiss();$('#veil').hidden=true;$('#pause').textContent='PAUSE';$('#start').onclick=()=>start();inspector.sync();canvas.focus();if(!muted)audio.play().catch(()=>{});}
function pause(force){if(!running||['caught','escaped'].includes(s.phase))return;s.paused=force??!s.paused;release();$('#pause').textContent=s.paused?'RESUME':'PAUSE';if(s.paused){audio.pause();ac?.suspend();}else if(!muted){audio.play().catch(()=>{});ac?.resume();}}
function action(id){if(!running||s.paused)return;if(dialog){dismiss();return;}const result=storeAction(s,id);if(result==='music'){release();checkpoint();inspector.sync();}if(result==='drawing'){rememberDrawing();dialog=true;release();$('#line').textContent='A little rabbit stands in a room full of toys. Every face looks toward it.\n\nIn shaky handwriting: “They wake up when the song stops.”\n\nThe drawing is copied into your field notes.';$('#dialog').hidden=false;}if(result==='entry'||result==='exit')tone(95,.2);}
$('#start').onclick=()=>{let prepared=false;try{prepared=localStorage.getItem(checkpointKey)==='ready';}catch{}start(prepared);};$('#retry').onclick=()=>start(true);$('#ready').onclick=()=>start(true);$('#restart').onclick=()=>{try{localStorage.removeItem(checkpointKey);}catch{}start();};$('#pause').onclick=()=>pause();$('#action').onclick=()=>action();$('#continue').onclick=dismiss;$('#sound').onclick=()=>{muted=!muted;audio.muted=muted;if(muted)ac?.suspend();else if(!s.paused)ac?.resume();$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';};
const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};window.addEventListener('keydown',e=>{if(s.inspection)return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(map[key]||key===' ')e.preventDefault();if(e.repeat)return;if(key==='Escape')pause();else if(key==='e'||key===' ')action();else if(map[key]){keys.add(map[key]);route=[];pending=null;}});window.addEventListener('keyup',e=>keys.delete(map[e.key.length===1?e.key.toLowerCase():e.key]));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);route=[];pending=null;};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));}
canvas.onpointerdown=e=>{if(!running||s.paused||s.inspection||dialog)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*480/r.width,y=(e.clientY-r.top)*360/r.height;let o=STORE_OBJECTS.find(o=>Math.hypot(o.x-x,o.y-y)<18);if(x>419&&x<456&&y>54&&y<112)o=STORE_OBJECTS[1];if(x>365&&x<410&&y<102)o=s.exit>=.9?null:STORE_OBJECTS[3];if(x>82&&x<110&&y>186&&y<248&&s.entry<.85)o=STORE_OBJECTS[0];if(x>99&&x<158&&y>135&&y<172)o=STORE_OBJECTS[2];const goal=o||{x,y};route=storePath(s,goal.x,goal.y);pending=o?.id||null;if(o&&Math.hypot(s.x-o.x,s.y-o.y)<o.r){action(o.id);pending=null;}};
function lightPool(x,y,r,color,alpha){ctx.save();ctx.globalAlpha=alpha;const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.restore();}
function darkness(){const amount=1-s.lights;if(amount<=0)return;mx.clearRect(0,0,480,360);mx.fillStyle=`rgba(1,3,7,${amount*.96})`;mx.fillRect(0,0,480,360);mx.globalCompositeOperation='destination-out';const radius=s.phase==='blackout'?16:69,g=mx.createRadialGradient(s.x,s.y-9,7,s.x,s.y-9,radius);g.addColorStop(0,s.phase==='blackout'?'rgba(0,0,0,.45)':'rgba(0,0,0,.88)');g.addColorStop(1,'transparent');mx.fillStyle=g;mx.fillRect(s.x-radius,s.y-radius-9,radius*2,radius*2);const exit=mx.createRadialGradient(387,105,1,387,105,33);exit.addColorStop(0,'rgba(0,0,0,.48)');exit.addColorStop(1,'transparent');mx.fillStyle=exit;mx.fillRect(354,72,66,66);mx.globalCompositeOperation='source-over';ctx.drawImage(mask,0,0);}
function render(){ctx.drawImage(bg,0,0,480,360);const ordered=[...layers.snapshot().layers.map(layer=>({depth:layer.depth,name:layer.name})),{depth:s.y,name:'player'}].sort((a,b)=>a.depth-b.depth);let low=-Infinity;for(const layer of ordered){props.drawRange(ctx,s,low,layer.depth);if(layer.name==='player'){ctx.save();ctx.globalAlpha=s.invincible&&Math.floor(s.time*12)%2===0?.5:1;drawPlayer(ctx,s,keys.size>0||route.length>0);ctx.restore();}else layers.drawLayer(ctx,layer.name);low=layer.depth;}props.drawRange(ctx,s,low,Infinity);
if(s.entry<.85&&s.phase==='explore'){ctx.fillStyle='#020306';ctx.fillRect(97,0,383,247);ctx.fillStyle='#bb9966';ctx.font='10px monospace';ctx.fillText('E · OPEN',34,214);}
for(const [x,y,c]of [[121,16,'#ed4b3b'],[167,17,'#e8bd59'],[250,16,'#6e9de6'],[337,17,'#d14b37'],[437,43,'#ffd18a']])lightPool(x,y,15,c,s.lights*(.13+.03*Math.sin(s.time*3+x)));darkness();if(s.lights<.8){for(const eye of props.eyes(s)){lightPool(eye.x,eye.y,4,'#bcdf91',(1-s.lights)*.55);ctx.fillStyle=`rgba(225,241,172,${(1-s.lights)*.95})`;ctx.fillRect(Math.round(eye.x),Math.round(eye.y),1,1);}}if(s.phase==='chase'){ctx.fillStyle=s.phaseAge>=7.5?'#e2cf9f':'#bc7060';ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillText(s.phaseAge>=7.5?'EXIT · E':'BOLT RELEASING',388,105);ctx.textAlign='left';}
if(s.paused){ctx.fillStyle='#030608c9';ctx.fillRect(0,0,480,360);ctx.fillStyle='#ddc394';ctx.font='16px monospace';ctx.fillText('PAUSED',207,180);}$('#health').textContent='● '.repeat(s.health)+'○ '.repeat(3-s.health);const awake=s.toys.filter(t=>t.phase!=='asleep').length;$('#awake').textContent=awake?'TOYS AWAKE · '+awake+' / 24':'TOYS ASLEEP · 24';$('#bolt').textContent=s.phase==='chase'?(s.phaseAge<7.5?'BOLT · '+Math.ceil(7.5-s.phaseAge)+'s':'EXIT READY'):'RED DOOR LOCKED';$('#notice').textContent=s.noticeAge>0?s.notice:' ';$('#hint').textContent=!dialog&&!s.paused&&!s.inspection?(storeNear(s)?.label||''):'';$('#objective').textContent=s.phase==='explore'?'Inspect the wind-up toy beside the red door.':s.phase==='chase'?'Avoid the toys. Open the red door when the bolt releases, then walk through.':'The lights are dying. Get ready to move.';}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running&&!dialog){let input=Object.fromEntries([...keys].map(k=>[k,true]));if(!keys.size&&route.length&&!s.inspection&&!s.paused){const p=route[0];if(Math.hypot(p.x-s.x,p.y-s.y)<.2)route.shift();else{input={target:p};}}tickStore(s,input,dt);if(!route.length&&pending){const id=pending;pending=null;action(id);}if(previousPhase!==s.phase){previousPhase=s.phase;if(s.phase==='blackout')tone(55,.45,.08);if(s.phase==='chase')tone(78,.28,.05);}if(!s.paused&&s.phase==='dimming'){const n=Math.floor(s.phaseAge*4);if(n!==lastNote){lastNote=n;tone([660,587,523,392][n%4]*(1-s.phaseAge*.18),.23);}}
if(['caught','escaped'].includes(s.phase)&&$('#veil').hidden){release();audio.pause();$('#veil').hidden=false;$('#veil h1').textContent=s.phase==='escaped'?'YOU GOT OUT':'THE TOYS FOUND YOU';$('#intro').textContent=s.phase==='escaped'?'You slam the red door. The little footsteps keep tapping on the other side. Level 4 is complete.':'Retry from beside the wind-up toy. Keep moving while the door bolt releases.';$('#start').textContent=s.phase==='escaped'?'PLAY LEVEL AGAIN':'RETRY AT TOY';$('#start').onclick=()=>start(s.phase==='caught');if(s.phase==='escaped'){remember(campaign,'awakened-toys','The wind-up rabbit killed the lights. Every toy moved. I escaped through the red door.');try{localStorage.setItem(campaignKey,saveCampaign(campaign));localStorage.setItem(checkpointKey,'escaped');}catch{}}}}
if(bg.complete&&bg.naturalWidth&&props&&layers)render();inspector.sync();requestAnimationFrame(frame);}
bg.onload=()=>{try{props=createStoreProps();layers=createForecourt(bg,geometry);$('#start').disabled=false;$('#start').textContent='ENTER THE STOREROOM';if(new URLSearchParams(location.search).get('test')==='toy')start(true);}catch(e){$('#intro').textContent='The 3D room could not start. Enable WebGL and reload.';console.error(e);}};bg.onerror=()=>$('#intro').textContent='The storeroom artwork could not load. Please reload.';bg.src='./assets/toystore-clean.png';Object.defineProperty(window,'frightStore',{get:()=>({...structuredClone(s),running,dialog,route:route.length,awake:s.toys.filter(t=>t.phase!=='asleep').length,render:props?.snapshot(),foreground:layers?.snapshot(),inspectionView:inspector.snapshot()})});requestAnimationFrame(frame);
