import {enterRoom,leaveRoom} from './room-flow.js';
import {createForkSprites} from './fork-sprites.js';
import {newWorkshop,retryWorkshop,tickWorkshop,attackWorkshop,dodgeWorkshop,flashWorkshop,workshopPath,workshopReveal,HATCH,REVEAL,FORK} from './levels/workshop-model.js';
import {createWorkshopProps} from './workshop-props.js';import {createWorkshopSprites} from './workshop-sprites.js';import {createWorkshopSound} from './workshop-sound.js';import {drawPlayer} from './levels/temporary-player.js';
const $=q=>document.querySelector(q),canvas=$('#game'),ctx=canvas.getContext('2d'),bg=new Image(),keys=new Set(),sound=createWorkshopSound();ctx.imageSmoothingEnabled=false;let s=newWorkshop(),props,sprites,forkSprites,running=false,last=performance.now(),route=[],muted=false;
const input=()=>Object.fromEntries([...keys].map(k=>[k,true]));function release(){keys.clear();route=[];}function start(retry=false){s=retry?retryWorkshop(s):newWorkshop();running=true;release();sound.start();$('#veil').hidden=true;$('#next-level').hidden=true;$('#pause').textContent='PAUSE';canvas.focus();}function pause(force){if(!running||['caught','escaped'].includes(s.phase))return;s.paused=force??!s.paused;release();$('#pause').textContent=s.paused?'RESUME':'PAUSE';s.paused?sound.pause():sound.resume();}
$('#start').onclick=()=>start();$('#retry').onclick=()=>start(true);$('#restart').onclick=()=>start();$('#pause').onclick=()=>pause();$('#action').onclick=()=>attackWorkshop(s);$('#dodge').onclick=()=>dodgeWorkshop(s,input());$('#flash').onclick=()=>flashWorkshop(s);$('#sound').onclick=()=>{muted=!muted;sound.mute(muted);$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';};
const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};
window.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(map[k]||k===' ')e.preventDefault();if(e.repeat)return;if(k==='Escape')pause();else if(k==='e')attackWorkshop(s);else if(k==='f')flashWorkshop(s);else if(k===' '||k==='Shift')dodgeWorkshop(s,input());else if(map[k]){keys.add(map[k]);route=[];}});window.addEventListener('keyup',e=>keys.delete(map[e.key.length===1?e.key.toLowerCase():e.key]));window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true);});for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);route=[];};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));}
canvas.onpointerdown=e=>{if(!running||s.paused||['caught','escaped'].includes(s.phase))return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*480/r.width+s.cameraX,y=(e.clientY-r.top)*360/r.height+s.cameraY;route=workshopPath(s,x,y);};
function world(fn){ctx.save();ctx.translate(-s.cameraX,-s.cameraY);fn();ctx.restore();}
function lightning(x,y,xx,yy,seed=0){ctx.strokeStyle='#c4f7ff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);for(let i=1;i<7;i++){const t=i/7,offset=Math.sin(i*13+s.time*70+seed)*6;ctx.lineTo(x+(xx-x)*t+offset,y+(yy-y)*t+offset*.5);}ctx.lineTo(xx,yy);ctx.stroke();ctx.strokeStyle='#6d9fff';ctx.lineWidth=.6;ctx.stroke();}
function actor(){ctx.globalAlpha=s.invincible&&Math.floor(s.time*12)%2?.45:1;if(s.fork&&forkSprites)forkSprites.draw(ctx,s);else drawPlayer(ctx,s,s.moving&&!s.paused);ctx.globalAlpha=1;if(s.fork&&!forkSprites){const d=s.face==='left'?-1:1;ctx.strokeStyle='#e7e3c9';ctx.lineWidth=1.2;ctx.beginPath();const x=s.x+d*(s.attack?26:11),y=s.y-28;ctx.moveTo(s.x+d*9,s.y-22);ctx.lineTo(x,y);for(let i=-1;i<=1;i++){ctx.moveTo(x,y+i*2);ctx.lineTo(x+d*6,y+i*2);}ctx.stroke();}if(s.flash>0){const a=({right:0,down:Math.PI/2,left:Math.PI,up:-Math.PI/2})[s.face];ctx.fillStyle='rgba(237,244,201,.24)';ctx.beginPath();ctx.moveTo(s.x,s.y-15);ctx.arc(s.x,s.y-15,170,a-.62,a+.62);ctx.closePath();ctx.fill();}}
// Steel hatch leaves slide apart before the deck and real 3D rig rise together.
function drawHatch(){const r=workshopReveal(s),{x,y,w,h}=HATCH;ctx.save();ctx.fillStyle='#030505';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#514637';ctx.lineWidth=4;ctx.strokeRect(x-1,y-1,w+2,h+2);ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.fillStyle='#171d1c';ctx.fillRect(x,y+12,w,7);for(const xx of [x+12,x+w-16]){ctx.fillStyle='#303735';ctx.fillRect(xx,y,4,h);ctx.fillStyle='#777359';ctx.fillRect(xx,y+25+r.offset*.25,4,5);}if(r.lift>0){const top=y+r.offset;ctx.fillStyle='#313633';ctx.fillRect(x+3,top,w-6,h);ctx.fillStyle='#586057';ctx.fillRect(x+5,top+3,w-10,h-8);for(let yy=0;yy<5;yy++){ctx.strokeStyle='#363e38';ctx.beginPath();ctx.moveTo(x+7,top+9+yy*17);ctx.lineTo(x+w-7,top+9+yy*17);ctx.stroke();}for(const xx of [x+10,x+w-12])for(const yy of [top+8,top+h-12]){ctx.fillStyle='#a29671';ctx.fillRect(xx,yy,3,3);}}ctx.restore();
const slide=r.opening*w/2;for(const side of [-1,1]){const sx=side<0?x:x+w/2,dx=sx+side*slide;const metal=ctx.createLinearGradient(dx,y,dx+w/2,y+h);metal.addColorStop(0,'#798789');metal.addColorStop(.28,'#49585d');metal.addColorStop(.52,'#728183');metal.addColorStop(.56,'#39494e');metal.addColorStop(1,'#222e34');ctx.fillStyle='#11191d';ctx.fillRect(dx-1,y+5,w/2+2,h);ctx.fillStyle=metal;ctx.fillRect(dx,y,w/2,h);ctx.strokeStyle='#a1aaa4';ctx.lineWidth=1;ctx.strokeRect(dx+1,y+1,w/2-2,h-2);ctx.strokeStyle='#17252b';ctx.lineWidth=2;ctx.strokeRect(dx+6,y+6,w/2-12,h-12);for(let yy=13;yy<h-8;yy+=13){ctx.strokeStyle='#9aa7a24d';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(dx+9,y+yy);ctx.lineTo(dx+w/2-9,y+yy);ctx.stroke();}for(const xx of [dx+4,dx+w/2-5])for(const yy of [y+4,y+h/2,y+h-5]){ctx.fillStyle='#172329';ctx.fillRect(xx-1,yy-1,4,4);ctx.fillStyle='#bdc3ba';ctx.fillRect(xx,yy,2,2);}ctx.fillStyle='#1e292d';ctx.fillRect(dx+w/4-10,y+h/2-3,20,6);ctx.fillStyle='#82918e';ctx.fillRect(dx+w/4-8,y+h/2-2,16,2);}if(r.lift<1){ctx.fillStyle='#59635b';ctx.globalAlpha=.08;for(let i=0;i<7;i++){ctx.beginPath();ctx.ellipse(x+w/2+Math.sin(s.time+i*2)*75,y+h-7-i*6,25,4,0,0,7);ctx.fill();}ctx.globalAlpha=1;}}
function render(){ctx.clearRect(0,0,480,360);world(()=>{ctx.drawImage(bg,0,0,720,540);drawHatch();ctx.fillStyle='#060807';ctx.fillRect(621,27,37,51);for(const p of s.footprints){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.globalAlpha=.55*Math.pow(1-p.age/14,1.3);ctx.fillStyle='#342920';ctx.fillRect(-4,-1.6,6,3);ctx.fillRect(3,-1.2,2,2.4);ctx.restore();}if(!s.fork){ctx.strokeStyle='#d2d0b4';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(FORK.x-5,FORK.y+4);ctx.lineTo(FORK.x+6,FORK.y-6);for(let i=0;i<3;i++){ctx.moveTo(FORK.x+3+i*2,FORK.y-3);ctx.lineTo(FORK.x+4+i*2,FORK.y-8);}ctx.stroke();ctx.fillStyle=`rgba(248,245,206,${.3+.3*Math.sin(s.time*4)})`;ctx.fillRect(FORK.x+1,FORK.y-9,3,3);}ctx.fillStyle='#11151088';ctx.beginPath();ctx.ellipse(s.boss.x,s.boss.y,26,8,0,0,7);ctx.fill();});
const layers=[{depth:333,draw:()=>props.draw(ctx,s)},{depth:s.phase==='arrival'?334:s.boss.y,draw:()=>world(()=>sprites.draw(ctx,s))}];if(running)layers.push({depth:s.y,draw:()=>world(actor)});layers.sort((a,b)=>a.depth-b.depth).forEach(o=>o.draw());
world(()=>{const b=s.boss;if(b.mode==='recover'){ctx.strokeStyle='#8aecd0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(b.x,b.y-72,9+Math.sin(s.time*12)*2,0,7);ctx.stroke();ctx.fillStyle='#d4fff0';ctx.font='8px monospace';ctx.textAlign='center';ctx.fillText('CONTACTS OPEN',b.x,b.y-151);}for(const p of s.shots)lightning(p.x-p.dx*.05,p.y-p.dy*.05,p.x+p.dx*.025,p.y+p.dy*.025,p.age);if(b.flash>0||b.mode==='transform')for(let i=0;i<4;i++)lightning(b.x-25+i*16,b.y-135,b.x+Math.sin(i+s.time*20)*32,b.y-8,i);for(const p of s.sparks){const x=b.x+Math.cos(p.angle)*p.speed*p.age,y=b.y-66+Math.sin(p.angle)*p.speed*p.age;ctx.fillStyle='#c3eeff';ctx.fillRect(x,y,2,2);}for(const m of s.moths){const wing=3+Math.abs(Math.sin(m.age*30))*7;ctx.fillStyle='#a19572';ctx.beginPath();ctx.ellipse(m.x-wing/2,m.y-10,wing,3.8,-.4,0,7);ctx.ellipse(m.x+wing/2,m.y-10,wing,3.8,.4,0,7);ctx.fill();ctx.fillStyle='#181b18';ctx.fillRect(m.x-1,m.y-14,2,8);ctx.fillStyle='#c4b88c';ctx.fillRect(m.x-5,m.y-12,2,2);ctx.fillRect(m.x+3,m.y-12,2,2);}
});
// Darkness lifts first inside the surgical pool; wall lamps flicker afterwards.
const first=s.phase==='arrival'&&s.age<1.4,reveal=Math.max(0,Math.min(1,(s.age-1.4)/.8));if(first){ctx.fillStyle='#030405';ctx.globalAlpha=.97;ctx.fillRect(0,0,480,360);ctx.globalAlpha=1;}else{const flicker=s.phase==='arrival'&&s.age<REVEAL.standAt+1.2?Math.sin(s.age*31)>.2?.88:.52:.3+Math.max(0,Math.sin(s.time*7.3)-.9)*.3;const light=ctx.createRadialGradient(360-s.cameraX,279-s.cameraY,20,360-s.cameraX,279-s.cameraY,250);light.addColorStop(0,`rgba(1,5,5,${.06+(1-reveal)*.8})`);light.addColorStop(.5,`rgba(1,5,5,${.15+(1-reveal)*.6})`);light.addColorStop(1,`rgba(1,5,5,${flicker})`);ctx.fillStyle=light;ctx.fillRect(0,0,480,360);}
world(()=>{for(let i=0;i<95;i++){const x=90+(i*73.17+s.time*(i%3+1)*1.2)%535,y=160+(i*47.31+Math.sin(s.time*.45+i)*11)%240;const near=Math.max(0,1-Math.hypot(x-360,y-260)/230);ctx.fillStyle=`rgba(220,211,179,${first?.015:.07+near*.23})`;ctx.fillRect(x,y,i%7===0?1.5:1,1);}for(const [i,x,y]of [[0,75,215],[1,190,79],[2,499,79],[3,658,231]]){const glow=.08+.1*Math.max(0,Math.sin(s.time*(i+3)*2));ctx.fillStyle=`rgba(244,166,68,${first?0:glow})`;ctx.beginPath();ctx.arc(x,y,14,0,7);ctx.fill();}});
if(s.paused){ctx.fillStyle='#020406bb';ctx.fillRect(0,0,480,360);ctx.fillStyle='#e8d5a8';ctx.font='18px monospace';ctx.textAlign='center';ctx.fillText('PAUSED',240,170);}$('#health').textContent='● '.repeat(Math.max(0,s.health));$('#boss-health').value=s.boss.hp;$('#boss-label').textContent=s.boss.phase===2?'THE BROKEN RIG · PHASE II':'THE SURGEON · PHASE I';$('#notice').textContent=s.noticeAge>0?s.notice:' ';$('#objective').textContent=!s.fork?'Find the metal fork on the dusty floor.':s.phase==='defeated'?'The upper-right door is open.':s.boss.mode==='recover'?'E · SHORT THE EXPOSED CONTACTS':`E · HIT CASING ${s.boss.armorHits}/2   SPACE · DODGE`;$('#hint').textContent=s.boss.mode==='recover'&&Math.hypot(s.x-s.boss.x,s.y-s.boss.y)<62?'E · SHORT CIRCUIT':'';$('#flash').textContent=s.flashCooldown>0?'FLASH RECHARGING':'FLASH · F';$('#dodge').textContent=s.dodgeCooldown>0?'RECOVERING':'DODGE · SPACE';}
function finish(){release();sound.pause();$('#veil').hidden=false;const win=s.phase==='escaped';$('#veil h1').textContent=win?'THE CURRENT IS DEAD':'THE RIG CAUGHT YOU';$('#intro').textContent=win?'The platform is silent. Your footprints lead out of the workshop. Level 8 complete.':'Hit the casing twice to open it, then strike again to short the contacts. Dodge its hands and the lightning.';$('#start').textContent=win?'PLAY AGAIN':'RETRY BOSS';$('#start').onclick=()=>start(!win);$('#next-level').hidden=!win;if(win)leaveRoom('./level-9.html?arrival=workshop');}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(running){let controls=input();if(!keys.size&&route.length){const p=route[0];if(Math.hypot(p.x-s.x,p.y-s.y)<.3)route.shift();else controls={target:p};}if(s.phase==='defeated'&&keys.has('up')&&s.x>570&&s.y<230){const path=workshopPath(s,640,82);if(path[0])controls={target:path[0]};}tickWorkshop(s,controls,dt);sound.tick(s);if(['escaped','caught'].includes(s.phase)&&$('#veil').hidden)finish();}if(props&&sprites&&bg.complete)render();requestAnimationFrame(frame);}
Promise.all([new Promise((resolve,reject)=>{bg.onload=resolve;bg.onerror=reject;bg.src='./assets/workshop-arena.png';}),createWorkshopSprites(),createForkSprites()]).then(([,art,forkArt])=>{sprites=art;forkSprites=forkArt;props=createWorkshopProps(bg);$('#start').disabled=false;$('#start').textContent='ENTER THE DARK ROOM';enterRoom(()=>start(),()=>{if(!s.paused)sound.resume();});}).catch(e=>{$('#intro').textContent='The workshop assets could not load. Reload to retry.';console.error(e);});Object.defineProperty(window,'frightWorkshop',{get:()=>({...structuredClone(s),running,reveal:workshopReveal(s),route:route.length,sprites:sprites?.snapshot(),forkSprites:forkSprites?.snapshot(),render:props?.snapshot(),audio:sound.snapshot()})});requestAnimationFrame(frame);
