import {HATCH,REVEAL,workshopReveal} from './levels/workshop-model.js';
import {loadAtlas as load} from './sprite-atlas.js';
export async function createWorkshopSprites(){const [battle,wake,contacts]=await Promise.all([load('./assets/characters/workshop-boss.png',6,4),load('./assets/characters/workshop-wake.png',3,2),load('./assets/characters/workshop-contacts.png',3,2)]);return {draw(ctx,s){const b=s.boss;let frame,w,h,y,shake=0;
if(s.phase==='arrival'&&s.age<REVEAL.standAt){const i=Math.max(0,Math.min(5,Math.floor((s.age-REVEAL.wakeAt)/.5)));frame=wake[i];const scale=Math.min(180/frame.w,148/frame.h);w=frame.w*scale;h=frame.h*scale;y=303-h;if(i<3)y=282-h*.65;}else{const broken=b.phase===2,row=broken?2:0;let index=row*6+Math.floor(b.walk)%6;if(['grab-warn','grab','cooldown','recover'].includes(b.mode)&&(!broken||b.sequence%2===0)){const i=b.mode==='grab-warn'?Math.min(2,Math.floor(b.age*3)):b.mode==='grab'?3+Math.min(1,Math.floor(b.age*5)):5;index=6+i;}if(broken&&['charge','shoot','cooldown','recover'].includes(b.mode)){const i=b.mode==='charge'?Math.min(3,Math.floor(b.age*4)):b.mode==='shoot'?4:5;index=18+i;}frame=battle[index];if(['recover','reseal','shorted'].includes(b.mode)){const i=b.mode==='reseal'?Math.max(0,2-Math.floor(b.age*10)):b.mode==='shorted'?2:Math.min(2,Math.floor(b.age*8));frame=contacts[(broken?3:0)+i];}h=148;w=h*frame.w/frame.h;y=b.y-h;if(['shorted','transform'].includes(b.mode))shake=Math.sin(s.time*80)*3;else if(b.impact>0)shake=Math.sin(s.time*95)*3*(b.impact/.24);}
// The front floor hides the submerged sprite; the rear rim must not crop raised limbs.
const reveal=workshopReveal(s);y+=reveal.offset;ctx.save();if(reveal.lift<1){ctx.beginPath();ctx.rect(HATCH.x,0,HATCH.w,HATCH.y+HATCH.h);ctx.clip();}ctx.translate(b.x+shake,0);if(b.face<0)ctx.scale(-1,1);if(b.mode==='dead'){ctx.translate(0,b.y);ctx.rotate(Math.PI/2);ctx.globalAlpha=.7;ctx.drawImage(frame.canvas,frame.x,frame.y,frame.w,frame.h,-w/2,-h,w,h);}else ctx.drawImage(frame.canvas,frame.x,frame.y,frame.w,frame.h,-w/2,y,w,h);ctx.restore();
// A physical loose eye drops on a cable, swings, then retracts into its socket.
if(s.phase!=='arrival'&&b.mode!=='dead'){const cycle=s.time%8,drop=cycle<1?0:cycle<2?(cycle-1)*40:cycle<4?40:cycle<5?(5-cycle)*40:0;const ex=b.x+shake+b.face*(-w/2+(frame.eye.x-frame.x)/frame.w*w),ey=y+(frame.eye.y-frame.y)/frame.h*h;if(drop>0){ctx.fillStyle='#070808';ctx.beginPath();ctx.ellipse(ex,ey,4,4.5,0,0,7);ctx.fill();const x=ex+Math.sin(s.time*8)*drop*.16,y=ey+drop;ctx.strokeStyle='#8c4229';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(ex,ey);ctx.quadraticCurveTo(ex-7,y-8,x,y);ctx.stroke();ctx.fillStyle='#ded2a7';ctx.beginPath();ctx.arc(x,y,4,0,7);ctx.fill();ctx.fillStyle='#101310';ctx.fillRect(x-1,y-2,2,3);}}
},snapshot:()=>({frames:36,walk:12,grab:6,electric:6,wake:6,contacts:6,height:148,transparent:true,isolatedFrames:true,bounds:[...battle,...wake,...contacts].map(f=>f.source)})};}
