import {REVEAL} from './levels/workshop-model.js';
export function createWorkshopSound(){let ac,master,muted=false,last='',lastShort=0,lastCasing=0,nextLaugh=8,laughs=0,grunts=0,whooshes=0,laughBuffer,gruntBuffer,generatedGrunt,hatchStage='closed',hatchCues=0;const active=new Set();
const loadAudio=path=>fetch(new URL(path,import.meta.url)).then(r=>r.ok?r.arrayBuffer():null).catch(()=>null);
const laughData=loadAudio('./audio/atlas-clown-laugh.mp3'),gruntData=loadAudio('./audio/atlas-monster-grunt.mp3');
async function decode(data){if(!data)return null;try{const buffer=await ac.decodeAudioData(data);let peak=0;for(let c=0;c<buffer.numberOfChannels;c++)for(const v of buffer.getChannelData(c))peak=Math.max(peak,Math.abs(v));const gain=Math.min(4,.85/(peak||1));for(let c=0;c<buffer.numberOfChannels;c++){const samples=buffer.getChannelData(c);for(let i=0;i<samples.length;i++)samples[i]*=gain;}return buffer;}catch{return null;}}
function play(buffer,volume=1,rate=1,cutoff=3500,echo=false){if(!ac||muted||ac.state!=='running'||!buffer)return;const source=ac.createBufferSource(),gain=ac.createGain(),filter=ac.createBiquadFilter();source.buffer=buffer;source.playbackRate.value=rate;gain.gain.value=volume;filter.type='lowpass';filter.frequency.value=cutoff;source.connect(filter).connect(gain).connect(master);const nodes=[source,filter,gain];if(echo){const delay=ac.createDelay(.5),wet=ac.createGain();delay.delayTime.value=.24;wet.gain.value=.19;gain.connect(delay).connect(wet).connect(master);nodes.push(delay,wet);}active.add(source);source.onended=()=>{active.delete(source);for(const n of nodes)n.disconnect();};source.start();return source;}
function burst(duration=.5,electric=false){if(!ac)return;const b=ac.createBuffer(1,Math.floor(ac.sampleRate*duration),ac.sampleRate),data=b.getChannelData(0);let low=0;for(let i=0;i<data.length;i++){const t=i/data.length,noise=Math.random()*2-1;low=low*.88+noise*.12;data[i]=(electric?noise*(.35+.65*Math.abs(Math.sin(i*.017))):low*3)*Math.sin(Math.PI*t)**1.7*.55;}play(b,electric?.23:.38,1,electric?3800:1800);if(!electric)whooshes++;}
function casingClang(){if(!ac)return;const b=ac.createBuffer(1,Math.floor(ac.sampleRate*.24),ac.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++){const t=i/ac.sampleRate;data[i]=(Math.sin(t*620*Math.PI*2)+.5*Math.sin(t*977*Math.PI*2)+.3*Math.sin(t*1631*Math.PI*2))*Math.exp(-t*27)*.35;}play(b,.35,1,2600);}
// Resonant steel scrape, hydraulic motor and locking impact follow the reveal stages.
function hatchSound(kind){if(!ac)return;const duration=kind==='opening'?REVEAL.openDuration:kind==='rising'?REVEAL.riseDuration:.7,b=ac.createBuffer(1,Math.ceil(ac.sampleRate*duration),ac.sampleRate),d=b.getChannelData(0);let low=0;for(let i=0;i<d.length;i++){const t=i/ac.sampleRate,u=t/duration,n=Math.random()*2-1;low=low*.94+n*.06;const metal=(Math.sin(t*631*6.283)+.4*Math.sin(t*997*6.283)+.2*Math.sin(t*1649*6.283));if(kind==='lock')d[i]=(low*2+metal*.32)*Math.exp(-t*8);else{const envelope=Math.min(1,t/.08,(duration-t)/.14),motor=Math.sin(t*(kind==='rising'?53:77)*6.283);d[i]=envelope*(motor*.16+low*(kind==='rising'?.5:1.4)+n*.06+metal*.055*(.5+.5*Math.sin(t*29)));}}if(play(b,kind==='lock'?.42:.38,1,kind==='rising'?1350:3400,true))hatchCues++;}
function grunt(){if(!ac)return;if(generatedGrunt){play(generatedGrunt,.55,.94+Math.random()*.1,4200,true);grunts++;return;}if(!gruntBuffer){const sr=ac.sampleRate,b=ac.createBuffer(1,Math.ceil(sr*1.2),sr),data=b.getChannelData(0);let phase=0,noise=0;for(let i=0;i<data.length;i++){const life=i/data.length,t=i/sr;noise=noise*.85+(Math.random()*2-1)*.15;phase+=(61-17*life+5*Math.sin(t*8))/sr*Math.PI*2;const voice=Math.sin(phase)+.32*Math.sin(phase*2.04)+.17*Math.sin(phase*3.1);data[i]=Math.tanh(voice*1.9+noise*1.8)*Math.sin(Math.PI*life)**.65*(.72+.28*Math.sin(t*31))*.63;}gruntBuffer=b;}play(gruntBuffer,.36,.91+Math.random()*.12,850,true);grunts++;}
return {start(){if(!ac){ac=new AudioContext();master=ac.createGain();master.gain.value=muted?0:.8;master.connect(ac.destination);laughData.then(decode).then(buffer=>{laughBuffer=buffer;});gruntData.then(decode).then(buffer=>{generatedGrunt=buffer;});}for(const source of active){try{source.stop();}catch{}}ac.resume();last='';hatchStage='closed';hatchCues=0;lastShort=lastCasing=0;nextLaugh=8;laughs=grunts=whooshes=0;},tick(s){if(s.paused)return;if(s.phase==='arrival'&&ac?.state==='running'){const stage=s.age<REVEAL.openAt?'closed':s.age<REVEAL.riseAt?'opening':s.age<REVEAL.riseAt+REVEAL.riseDuration?'rising':'lock';if(stage!==hatchStage){hatchStage=stage;if(stage!=='closed')hatchSound(stage);}}if(s.boss.mode!==last){last=s.boss.mode;if(['awakening','grab-warn','transform','dead'].includes(last))grunt();if(last==='grab')burst(.48);if(last==='charge')burst(.32,true);if(last==='shoot')burst(.28,true);}if(lastCasing!==s.casingHits){lastCasing=s.casingHits;casingClang();}if(lastShort!==s.shorts){lastShort=s.shorts;burst(.7,true);grunt();}if(s.phase==='fight'&&s.time>nextLaugh&&laughBuffer){play(laughBuffer,.42,.94+(laughs%3)*.07,3900,true);laughs++;nextLaugh=s.time+13+(laughs%3)*1.7;}},pause:()=>ac?.suspend(),resume:()=>ac?.resume(),mute(v){muted=v;if(master)master.gain.value=v?0:.8;},snapshot:()=>({muted,hatchStage,hatchCues,laughs,grunts,whooshes,laughterLoaded:!!laughBuffer,gruntLoaded:!!generatedGrunt,context:ac?.state||'locked',activeSources:active.size,source:'Atlas ElevenLabs creature SFX + Web Audio metal hatch',kind:'arm whooshes, low grunts, periodic clown laughter and electrical crackle'})};}
