import {assistDoor,BARREL_DOORS} from './door-assist.js';
export const BARREL_WORLD={width:720,height:480};
export const BARREL_FLOORS=[[30,365,105,452],[85,344,196,378],[126,316,252,353],[163,290,463,333],[206,253,610,296],[213,211,571,265],[279,198,399,238],[568,182,661,256],[597,80,674,220]];
export const BARREL_SOLIDS=[{id:'launcher',x:327,y:194,w:87,h:42},{id:'supply',x:224,y:219,w:20,h:19}];
export const WHEEL={x:658,y:211,r:30};
export const LANES=[[[353,229],[401,250],[443,264],[362,282],[278,294],[224,321],[169,347],[110,362]],[[353,229],[408,249],[461,248],[543,247],[599,227],[635,211]]];
export function newBarrelRun(){return {x:66,y:420,face:'up',spriteHeight:62,moving:false,walk:0,time:0,phase:'explore',health:3,invincible:0,paint:0,paintColor:'#efb922',cameraX:0,cameraY:120,active:false,cycle:0,cycleAge:0,warning:false,barrels:[],splashes:[],launchCount:0,hitCount:0,paused:false,inspection:false,turns:0,wheelAngle:0,gate:0,checkpoint:false,notice:'The library door slams behind you. Follow the passage.',noticeAge:6};}
export function barrelBlocked(s,x,y,r=6){if(![[-r,-r],[r,-r],[-r,r],[r,r]].every(([dx,dy])=>BARREL_FLOORS.some(([a,b,c,d])=>x+dx>=a&&x+dx<=c&&y+dy>=b&&y+dy<=d)))return true;return [...BARREL_SOLIDS,...(s.gate<.95?[{x:590,y:171,w:91,h:13}]:[])].some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h);}
export function barrelPath(s,x,y){const cell=6,W=121,H=81,key=(x,y)=>y*W+x;function nearest(x,y){const a=Math.round(x/cell),b=Math.round(y/cell);for(let r=0;r<7;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++)if(!barrelBlocked(s,(a+dx)*cell,(b+dy)*cell))return [a+dx,b+dy];}const start=nearest(s.x,s.y),end=nearest(x,y);if(!start||!end)return [];const prev=new Map([[key(...start),null]]),q=[start];for(let i=0;i<q.length;i++){const p=q[i];if(p[0]===end[0]&&p[1]===end[1]){let k=key(...p),route=[];while(prev.get(k)!==null){route.push({x:(k%W)*cell,y:Math.floor(k/W)*cell});k=prev.get(k);}return route.reverse();}for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const a=p[0]+dx,b=p[1]+dy,k=key(a,b);if(a<0||b<0||a>=W||b>=H||prev.has(k)||barrelBlocked(s,a*cell,b*cell))continue;prev.set(k,key(...p));q.push([a,b]);}}return [];}
function move(s,input,dt){let dx=Number(input.right||false)-Number(input.left||false),dy=Number(input.down||false)-Number(input.up||false);if(input.target){dx=input.target.x-s.x;dy=input.target.y-s.y;}const n=Math.hypot(dx,dy),speed=s.paint>0?67:86,dist=Math.min(speed*dt,input.target?n:Infinity);s.moving=false;if(!n)return;const ox=s.x,oy=s.y,steps=Math.ceil(dist/2);for(let i=0;i<steps;i++){const x=s.x+dx/n*dist/steps,y=s.y+dy/n*dist/steps;if(!barrelBlocked(s,x,s.y))s.x=x;if(!barrelBlocked(s,s.x,y))s.y=y;}s.moving=Math.hypot(s.x-ox,s.y-oy)>.01;if(s.moving){s.walk+=dt*11;s.face=Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up';}}
export function barrelAction(s){if(s.paused||s.phase!=='explore'||s.gate>=.95||Math.hypot(s.x-WHEEL.x,s.y-WHEEL.y)>=WHEEL.r)return false;s.inspection=true;return true;}
export function turnBarrelWheel(s){if(!s.inspection||s.paused||s.turns>=3)return false;s.turns++;s.wheelAngle+=Math.PI*2/3;if(s.turns===3){s.checkpoint=true;s.invincible=Math.max(s.invincible,2.5);s.notice='The gate is rising. Take the stairs!';s.noticeAge=5;}return true;}
export function barrelRetry(s){const n=newBarrelRun();if(s.checkpoint){Object.assign(n,{x:648,y:210,turns:3,wheelAngle:Math.PI*2,gate:1,checkpoint:true,active:true,notice:'The gate is open. Get upstairs.'});}return n;}
export function spillBarrel(s,b,hit=false){if(b.spilled)return;b.spilled=true;s.splashes.push({x:b.x,y:b.y,color:b.color,age:0,seed:b.id});if(hit&&s.invincible<=0){s.health--;s.hitCount++;s.paint=1.6;s.paintColor=b.color;s.invincible=1.65;s.notice='Paint burst! Keep moving — the next drum is coming.';s.noticeAge=2.5;if(s.health<=0)s.phase='caught';}}
function advanceBarrel(s,b,dt){const route=LANES[b.lane];let left=b.speed*dt;while(left>0&&b.segment<route.length-1){const [tx,ty]=route[b.segment+1],dx=tx-b.x,dy=ty-b.y,d=Math.hypot(dx,dy),step=Math.min(d,left);b.heading=Math.atan2(dy,dx);if(d){b.x+=dx/d*step;b.y+=dy/d*step;}b.roll+=step/12;left-=step;if(d<=step+.001)b.segment++;}
 if(!b.spilled&&Math.hypot(b.x-s.x,b.y-s.y)<18)spillBarrel(s,b,true);if(b.segment===route.length-1)spillBarrel(s,b);b.age+=dt;}
export function tickBarrelRun(s,input,dt){if(s.paused||s.inspection||s.phase!=='explore')return;s.time+=dt;s.noticeAge=Math.max(0,s.noticeAge-dt);s.invincible=Math.max(0,s.invincible-dt);s.paint=Math.max(0,s.paint-dt);input=assistDoor(s,input,BARREL_DOORS,barrelPath);move(s,input,dt);if(s.x>145)s.active=true;if(s.turns===3)s.gate=Math.min(1,s.gate+dt*.65);
 if(s.active){s.cycleAge+=dt;s.warning=s.cycleAge<.75;if(s.cycleAge>=.75&&s.cycleAge-dt<.75){const lane=s.cycle%3===2?1:0,[x,y]=LANES[lane][0],id=s.launchCount++;s.barrels.push({id,lane,x,y,age:0,segment:0,roll:0,heading:1,color:id%2?'#36bdb1':'#efb922',shell:id%2?0x294b91:0xac2922,speed:116+(s.cycle%4)*12,spilled:false});}if(s.cycle%3===2&&s.cycleAge>=1.18&&s.cycleAge-dt<1.18){const lane=0,[x,y]=LANES[lane][0],id=s.launchCount++;s.barrels.push({id,lane,x,y,age:0,segment:0,roll:0,heading:1,color:'#efb922',shell:0xac2922,speed:138,spilled:false});}if(s.cycleAge>=1.9){s.cycleAge-=1.9;s.cycle++;}}
 for(const b of s.barrels)if(!b.spilled)advanceBarrel(s,b,dt);s.barrels=s.barrels.filter(b=>!b.spilled);for(const p of s.splashes)p.age+=dt;s.splashes=s.splashes.filter(p=>p.age<16).slice(-18);
 s.cameraX=Math.max(0,Math.min(240,s.x-240));s.cameraY=Math.max(0,Math.min(120,s.y-230));if(s.gate>=.95&&s.y<101&&s.x>607){s.phase='escaped';s.notice='The machinery falls silent below. Something moves above you.';}}
