export const FALL_CAMERA={feetY:200,followSpeed:6};
export const ENTRY={startY:264,thresholdY:185,walkDuration:1.45,blackoutDuration:1};
export function fallBlackout(s){if(s.phase==='blackout')return 1;if(s.phase==='walking')return Math.max(0,Math.min(1,(s.age-(ENTRY.walkDuration-.3))/.3));if(s.phase==='fall')return Math.max(0,1-s.age/.35);return 0;}
export const SHAFT={left:116,right:364,landing:2860,height:3070};
export const FALL_OBSTACLES=Array.from({length:11},(_,i)=>({id:i,kind:i%3===1?'weight':i%3===2?'pipe':'beam',side:i%2?1:-1,y:440+i*205,phase:i*1.73})).concat([735,1160,1775,2370].map((y,i)=>({id:20+i,kind:'web',side:i%2?1:-1,y,phase:i*2}))).sort((a,b)=>a.y-b.y);
export function obstaclePose(o,time){const wave=Math.sin(time*.9+o.phase);if(o.kind==='web')return {x:o.side<0?161+wave*7:319+wave*7,y:o.y,w:86,h:103,angle:wave*.055};if(o.kind==='weight')return {x:240+Math.sin(time*.72+o.phase)*66,y:o.y+Math.cos(time+o.phase)*16,w:37,h:64,angle:wave*.32};const w=o.kind==='pipe'?98:110;return {x:o.side<0?SHAFT.left+w/2-10+wave*12:SHAFT.right-w/2+10+wave*12,y:o.y+wave*10,w,h:o.kind==='pipe'?30:22,angle:wave*.08};}
export function newFall(){return {x:240,y:ENTRY.startY,vx:0,vy:0,face:'up',spriteHeight:65,walk:0,moving:false,time:0,age:0,phase:'entry',health:4,hits:0,invincible:0,paused:false,door:0,cameraY:0,landAge:0,stones:[],stoneClock:1.2,stoneSeed:90287,stoneCount:0,stoneHits:0,snag:0,webHits:[],dust:[],dustBurst:0,notice:'A draught comes from the door beyond the silent workshop.',noticeAge:5};}
export function openFallDoor(s){if(s.phase!=='entry'||s.paused)return false;s.phase='opening';s.age=0;return true;}
function collide(s,p){return Math.abs(s.x-p.x)<p.w/2+8&&Math.abs((s.y-23)-p.y)<p.h/2+16;}
function dustBurst(s){s.dustBurst++;s.dust=Array.from({length:90},(_,i)=>({x:s.x+(i%9-4)*4,y:SHAFT.landing-5,vx:Math.sin(i*2.399)*(25+i%7*9),vy:-20-(i%11)*8,age:0,life:2.6+(i%7)*.4,r:4+i%6*2}));}
export function tickFall(s,input,dt){if(s.paused||s.phase==='caught')return;dt=Math.max(0,Math.min(.04,dt));s.time+=dt;s.age+=dt;s.noticeAge=Math.max(0,s.noticeAge-dt);s.invincible=Math.max(0,s.invincible-dt);s.snag=Math.max(0,s.snag-dt);const steer=Number(!!input.right)-Number(!!input.left);s.moving=false;
if(s.phase==='opening'){s.door=Math.min(1,s.age/1.25);if(s.age>=1.25){s.phase='walking';s.age=0;s.notice='';s.noticeAge=0;}}
else if(s.phase==='walking'){const progress=Math.min(1,s.age/ENTRY.walkDuration);s.y=ENTRY.startY+(ENTRY.thresholdY-ENTRY.startY)*progress;s.face='up';s.moving=true;s.walk+=dt*11;if(progress>=1){s.phase='blackout';s.age=0;s.moving=false;}}
else if(s.phase==='blackout'){if(s.age>=ENTRY.blackoutDuration){s.phase='fall';s.age=0;s.vy=25;s.y=260;s.cameraY=s.y-FALL_CAMERA.feetY;}}
else if(s.phase==='fall'){tickStones(s,dt);if(s.phase==='caught')return;const steps=Math.ceil(dt/.008);for(let k=0;k<steps;k++){const step=dt/steps;s.vx+=(steer*(s.snag>0?65:132)-s.vx)*Math.min(1,step*9);s.vy=s.snag>0?Math.max(68,s.vy-120*step):Math.min(150,s.vy+42*step);s.x=Math.max(SHAFT.left+11,Math.min(SHAFT.right-11,s.x+s.vx*step));s.y+=s.vy*step;for(const o of FALL_OBSTACLES){const p=obstaclePose(o,s.time-dt+step*k);if(o.kind==='web'){if(!s.webHits.includes(o.id)&&collide(s,p)){s.webHits.push(o.id);s.snag=.85;}continue;}if(s.invincible===0&&collide(s,p)){s.health--;s.hits++;s.invincible=1.6;s.vx=(s.x<p.x?-1:1)*110;s.vy=Math.max(85,s.vy*.85);if(s.health<=0){s.phase='caught';return;}}}if(s.y>=SHAFT.landing){s.y=SHAFT.landing;s.phase='landing';s.age=0;s.landAge=0;s.vx=s.vy=0;dustBurst(s);break;}}s.moving=!!steer;s.face=steer<0?'left':steer>0?'right':'down';s.walk+=dt*9;}
else if(s.phase==='landing'){s.landAge+=dt;if(s.landAge>3.8){s.phase='complete';s.age=0;s.notice='The bones settle. Somewhere above, the door swings shut.';s.noticeAge=5;}}
for(const p of s.dust){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-dt*.5);p.vy+=8*dt;}s.dust=s.dust.filter(p=>p.age<p.life);
const target=['entry','opening','walking','blackout'].includes(s.phase)?0:Math.max(0,Math.min(SHAFT.height-360,s.y-FALL_CAMERA.feetY));s.cameraY+=(target-s.cameraY)*Math.min(1,dt*FALL_CAMERA.followSpeed);
}

function stoneRandom(s){s.stoneSeed=(Math.imul(s.stoneSeed,1664525)+1013904223)>>>0;return s.stoneSeed/4294967296;}
function tickStones(s,dt){s.stoneClock-=dt;if(s.age>1&&s.y<SHAFT.landing-280&&s.stoneClock<=0){s.stoneClock=1.3+stoneRandom(s)*1.4;s.stones.push({id:s.stoneCount++,x:SHAFT.left+22+stoneRandom(s)*(SHAFT.right-SHAFT.left-44),y:s.y-225,vx:(stoneRandom(s)-.5)*28,vy:210+stoneRandom(s)*50,r:8+stoneRandom(s)*5,age:0});}for(const p of s.stones){p.age+=dt;const steps=Math.max(1,Math.ceil(dt/.008));for(let k=0;k<steps;k++){p.vy=Math.min(350,p.vy+85*dt/steps);p.x+=p.vx*dt/steps;p.y+=p.vy*dt/steps;if(p.x<SHAFT.left+p.r||p.x>SHAFT.right-p.r)p.vx*=-1;if(s.invincible===0&&Math.abs(s.x-p.x)<p.r+8&&Math.abs(s.y-23-p.y)<p.r+16){p.dead=true;s.health--;s.hits++;s.stoneHits++;s.invincible=1.6;s.vx=(s.x<p.x?-1:1)*85;if(s.health<=0)s.phase='caught';break;}}}s.stones=s.stones.filter(p=>!p.dead&&p.y<s.y+400&&p.y<SHAFT.landing&&p.age<7);}
