export const GALLERY={width:480,height:1440,cart:{x:240,y:153},start:{x:240,y:1280}};
export const CLOTHES=Array.from({length:19},(_,i)=>({id:i,x:156+(i*67)%174,y:270+(i*127)%990,kind:i%8,angle:Math.sin(i*3)*1.8}));
export const EFFIGIES=Array.from({length:8},(_,i)=>({x:i%2?405:75,y:290+Math.floor(i/2)*250,side:i%2?1:-1,phase:i*1.7}));
export function newGallery(){return {level:10,x:240,y:1280,spriteHeight:68,face:'up',moving:false,walk:0,time:0,age:0,phase:'landing',paused:false,cameraX:0,cameraY:1080,footprints:[],step:0,dust:Array.from({length:60},(_,i)=>({x:240+Math.sin(i*2.4)*90,y:1320+Math.cos(i)*22,age:0,life:3+i%5,vx:Math.sin(i*2.4)*14,vy:-7-i%9})),notice:'Small shoes. Coats. Everywhere.',noticeAge:4,boarded:false,drips:[],wet:[],dripClock:0,dripCount:0,clothes:CLOTHES.map(c=>({...c,z:0,age:0,cooldown:0,flights:0})),clothFlights:0};}
export function galleryBlocked(x,y){return x<139||x>341||y<107||y>1332||(x>214&&x<266&&y>112&&y<192);}
export function boardCart(s){if(s.paused||!['explore','flee'].includes(s.phase)||Math.hypot(s.x-240,s.y-194)>82)return false;s.phase='boarding';s.age=0;s.boardFrom={x:s.x,y:s.y};s.notice='';s.noticeAge=0;return true;}
export function tickGallery(s,input,dt){if(s.paused||s.phase==='complete')return;dt=Math.min(.04,Math.max(0,dt));s.time+=dt;s.age+=dt;s.noticeAge=Math.max(0,s.noticeAge-dt);s.moving=false;
if(s.phase==='landing'&&s.age>1.6){s.phase='explore';s.age=0;}
if(['explore','flee'].includes(s.phase)){let dx=Number(!!input.right)-Number(!!input.left),dy=Number(!!input.down)-Number(!!input.up);if(input.target&&!dx&&!dy){dx=input.target.x-s.x;dy=input.target.y-s.y;}const n=Math.hypot(dx,dy),speed=s.phase==='flee'?130:88;if(n>.5){const dist=Math.min(speed*dt,input.target?n:Infinity),ox=s.x,oy=s.y,x=s.x+dx/n*dist,y=s.y+dy/n*dist;if(!galleryBlocked(x,s.y))s.x=x;if(!galleryBlocked(s.x,y))s.y=y;s.moving=Math.hypot(s.x-ox,s.y-oy)>.01;if(s.moving){s.face=Math.abs(dx)>Math.abs(dy)?dx<0?'left':'right':dy<0?'up':'down';s.walk+=dt*(s.phase==='flee'?16:10);s.step+=dist;if(s.step>17){s.step=0;s.footprints.push({x:s.x,y:s.y,age:0,side:Math.floor(s.walk)%2});}}}if(s.phase==='explore'&&s.y<1010){s.phase='flee';s.age=0;s.notice='Are those the missing children? I have to get out fast.';s.noticeAge=5;}}
if(s.phase==='boarding'){const t=Math.min(1,s.age/1.1),e=t*t*(3-2*t);s.x=s.boardFrom.x+(240-s.boardFrom.x)*e;s.y=s.boardFrom.y+(165-s.boardFrom.y)*e;s.face='up';s.moving=t<.65;s.walk+=dt*10;if(s.age>1.7){s.boarded=true;s.phase='complete';}}
s.dripClock+=dt;if(s.dripClock>.14){s.dripClock=0;const i=s.dripCount++;s.drips.push({x:160+(i*71)%164,y:180+(i*193)%1110,z:120+i%55,vy:0});}for(const d of s.drips){d.vy+=280*dt;d.z-=d.vy*dt;if(d.z<=0){s.wet.push({x:d.x,y:d.y,age:0,r:5+s.dripCount%5});}}s.drips=s.drips.filter(d=>d.z>0);for(const p of s.wet)p.age+=dt;s.wet=s.wet.filter(p=>p.age<24);for(const c of s.clothes){c.cooldown=Math.max(0,c.cooldown-dt);if(s.moving&&Math.hypot(s.x-c.x,s.y-c.y)<29&&c.cooldown===0){const a=Math.atan2(c.y-s.y,c.x-s.x);c.from={x:c.x,y:c.y};c.to={x:Math.max(146,Math.min(334,c.x+Math.cos(a)*(c.kind===7?2:20))),y:c.y+Math.sin(a)*(c.kind===7?2:17)};c.age=0;c.cooldown=3;c.flights++;s.clothFlights++;}if(c.from){c.age+=dt;const t=Math.min(1,c.age/1.3);c.x=c.from.x+(c.to.x-c.from.x)*t;c.y=c.from.y+(c.to.y-c.from.y)*t;c.z=Math.sin(t*Math.PI)*(c.kind===7?0:c.kind===6?5:12);c.angle+=dt*(c.kind===7?.08:.8);if(t===1){c.from=null;c.z=0;}}}for(const p of s.footprints)p.age+=dt;s.footprints=s.footprints.filter(p=>p.age<12);for(const p of s.dust){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}s.dust=s.dust.filter(p=>p.age<p.life);s.cameraY+=(Math.max(0,Math.min(1080,s.y-240))-s.cameraY)*Math.min(1,dt*7);}
export const TILE=80,SIZE=17,DIRS={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]},START={c:1,r:15},EXIT={c:15,r:1};
function makeMaze(){const g=Array.from({length:SIZE},()=>Array(SIZE).fill(1));let seed=87011;const rnd=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};const stack=[[1,15]];g[15][1]=0;while(stack.length){const [x,y]=stack.at(-1),next=Object.values(DIRS).map(([dx,dy])=>[x+dx*2,y+dy*2,dx,dy]).filter(([nx,ny])=>nx>0&&ny>0&&nx<SIZE-1&&ny<SIZE-1&&g[ny][nx]);if(!next.length){stack.pop();continue;}const [nx,ny,dx,dy]=next[Math.floor(rnd()*next.length)];g[y+dy][x+dx]=0;g[ny][nx]=0;stack.push([nx,ny]);}for(let i=0;i<28;i++){const x=1+Math.floor(rnd()*15),y=1+Math.floor(rnd()*15);if(g[y][x]&&((g[y][x-1]===0&&g[y][x+1]===0)||(g[y-1][x]===0&&g[y+1][x]===0)))g[y][x]=0;}return g;}
export const MAZE=makeMaze();export const mazeOpen=(c,r)=>c>=0&&r>=0&&c<SIZE&&r<SIZE&&MAZE[r][c]===0;
export const centre=(c,r)=>({x:(c+.5)*TILE,y:(r+.5)*TILE});
export function mazeRoute(start,end){const q=[start],prev=new Map([[`${start.c},${start.r}`,null]]);for(let i=0;i<q.length;i++){const p=q[i],k=`${p.c},${p.r}`;if(p.c===end.c&&p.r===end.r){const route=[];let n=p;while(n){route.push(n);n=prev.get(`${n.c},${n.r}`);}return route.reverse();}for(const [dir,[dx,dy]]of Object.entries(DIRS)){const c=p.c+dx,r=p.r+dy,key=`${c},${r}`;if(mazeOpen(c,r)&&!prev.has(key)){const n={c,r,dir};prev.set(key,p);q.push(n);}}}return [];}
function actor(c,r,dir){return {c,r,...centre(c,r),dir,to:null,progress:0,distance:0,lane:0,laneTarget:0};}
export function newRide(){return {level:11,integrity:3,obstacleHits:0,hitObstacles:[],impact:0,speed:118,jumpAge:0,jumpZ:0,jumpCooldown:0,jumps:0,fragments:[],ink:[],inkClock:3.2,inkShots:0,inkHits:0,inkObscure:0,endingLeafFlights:0,endingLeaves:makeEndingLeaves(),time:0,age:0,phase:'ready',paused:false,cart:actor(START.c,START.r,'up'),spider:actor(START.c,START.r,'up'),queued:'up',spiderActive:false,cameraX:0,cameraY:1000,turns:0,visited:[`${START.c},${START.r}`],exit:0,notice:'Steer around the debris. Choose your exits.',noticeAge:4};}
export function startRide(s){if(s.phase!=='ready'||s.paused)return false;s.phase='ride';s.age=0;return true;}
function advanceActor(a,dist,choose){let guard=0;while(dist>.00001&&guard++<10){if(!a.to){const dir=choose(a),v=DIRS[dir];if(!v||!mazeOpen(a.c+v[0],a.r+v[1]))break;if(dir!==a.dir){a.lane=0;a.laneTarget=0;}a.dir=dir;a.to={c:a.c+v[0],r:a.r+v[1]};a.progress=0;}const amount=Math.min(dist,TILE-a.progress);a.progress+=amount;a.distance+=amount;dist-=amount;const p=centre(a.c,a.r),v=DIRS[a.dir];a.x=p.x+v[0]*a.progress;a.y=p.y+v[1]*a.progress;if(a.progress>=TILE-.00001){a.c=a.to.c;a.r=a.to.r;a.to=null;a.progress=0;}}}
export function queueRideTurn(s,dir){if(s.paused||!DIRS[dir]||!['ready','ride'].includes(s.phase))return false;s.queued=dir;const a=s.cart,v0=DIRS[a.dir],q0=DIRS[dir],side=q0[0]*(-v0[1])+q0[1]*v0[0];a.laneTarget=side*19;if(a.to){const v=DIRS[a.dir],q=DIRS[dir];if(v[0]===-q[0]&&v[1]===-q[1]){const old={c:a.c,r:a.r};a.c=a.to.c;a.r=a.to.r;a.to=old;a.progress=TILE-a.progress;a.dir=dir;a.lane*=-1;a.laneTarget*=-1;}}return true;}
export function tickRide(s,input,dt){if(s.paused||['complete','ready'].includes(s.phase))return;if(s.phase==='caught'){s.age+=Math.min(.04,dt);return;}dt=Math.min(.04,Math.max(0,dt));s.time+=dt;s.age+=dt;s.noticeAge=Math.max(0,s.noticeAge-dt);if(input.turn)queueRideTurn(s,input.turn);if(s.phase==='escape'){tickEndingLeaves(s,dt);s.exit=Math.min(1,s.age);if(s.age>16.5)s.phase='complete';return;}s.impact=Math.max(0,s.impact-dt);s.speed+=( (s.impact>0?48:118)-s.speed)*Math.min(1,dt*(s.impact>0?20:2.2));s.jumpCooldown=Math.max(0,s.jumpCooldown-dt);if(input.jump)jumpRide(s);if(s.jumpAge>0){s.jumpAge+=dt;s.jumpZ=Math.sin(Math.min(1,s.jumpAge/.95)*Math.PI)*42;if(s.jumpAge>=.95){s.jumpAge=0;s.jumpZ=0;}}s.inkObscure=Math.max(0,s.inkObscure-dt);for(const f of s.fragments){f.age+=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.z+=f.vz*dt;f.vz-=165*dt;if(f.z<0){f.z=0;f.vz=Math.abs(f.vz)*.25;f.vx*=.8;f.vy*=.8;}}s.fragments=s.fragments.filter(f=>f.age<2.2);

s.spiderActive=s.age>6;const steps=Math.max(1,Math.ceil(dt/.01));for(let i=0;i<steps;i++){s.cart.lane+=(s.cart.laneTarget-s.cart.lane)*Math.min(1,dt/steps*12);advanceActor(s.cart,s.speed*dt/steps,a=>{const legal=dir=>{const v=DIRS[dir];return mazeOpen(a.c+v[0],a.r+v[1]);};const d=legal(s.queued)?s.queued:legal(a.dir)?a.dir:null;if(d&&d!==a.dir)s.turns++;return d;});const key=`${s.cart.c},${s.cart.r}`;if(!s.visited.includes(key))s.visited.push(key);
if(s.cart.c===EXIT.c&&s.cart.r===EXIT.r){s.phase='escape';s.age=0;s.notice='Cold air. The way out.';s.noticeAge=2;return;}
const point=cartPosition(s);for(const o of RIDE_OBSTACLES){const dx=Math.abs(point.x-o.x),dy=Math.abs(point.y-o.y),inside=o.kind==='barricade'?(o.vertical?dx<37&&dy<20:dy<37&&dx<20):dx<22&&dy<22;if(!s.hitObstacles.includes(o.id)&&inside&&s.jumpZ<23){s.hitObstacles.push(o.id);s.obstacleHits++;s.integrity=Math.max(0,s.integrity-1);s.impact=1.8;s.speed=48;for(let j=0;j<18;j++){const a=j*2.4;s.fragments.push({x:o.x,y:o.y,z:12,age:0,vx:Math.cos(a)*(22+j%5*9),vy:Math.sin(a)*(20+j%4*8),vz:40+j%7*9,angle:a,kind:o.kind});}}}
if(s.spiderActive){advanceActor(s.spider,(Math.hypot(s.cart.x-s.spider.x,s.cart.y-s.spider.y)>300?172:Math.hypot(s.cart.x-s.spider.x,s.cart.y-s.spider.y)>170?132:106)*dt/steps,a=>{const path=mazeRoute(a,s.cart.to||s.cart);return path[1]?.dir;});if(Math.hypot(s.cart.x-s.spider.x,s.cart.y-s.spider.y)<29){s.phase='caught';s.age=0;return;}}}
tickInk(s,dt);const v=DIRS[s.cart.dir],trailX=s.spiderActive?Math.max(-180,Math.min(180,s.spider.x-s.cart.x))*.35:0,trailY=s.spiderActive?Math.max(-180,Math.min(180,s.spider.y-s.cart.y))*.35:0;s.cameraX+=(Math.max(0,Math.min(SIZE*TILE-480,s.cart.x-240+v[0]*20+trailX))-s.cameraX)*Math.min(1,dt*6);s.cameraY+=(Math.max(0,Math.min(SIZE*TILE-360,s.cart.y-180+v[1]*15+trailY))-s.cameraY)*Math.min(1,dt*6);}

export function cartPosition(s){const v=DIRS[s.cart.dir];return {x:s.cart.x-v[1]*s.cart.lane,y:s.cart.y+v[0]*s.cart.lane};}
const straightCell=p=>((mazeOpen(p.c,p.r-1)&&mazeOpen(p.c,p.r+1)&&!mazeOpen(p.c-1,p.r)&&!mazeOpen(p.c+1,p.r))||(mazeOpen(p.c-1,p.r)&&mazeOpen(p.c+1,p.r)&&!mazeOpen(p.c,p.r-1)&&!mazeOpen(p.c,p.r+1)));
const mainRoute=mazeRoute(START,EXIT),mainKeys=new Set(mainRoute.map(p=>`${p.c},${p.r}`)),hazardCells=mainRoute.filter((p,i)=>i>8&&i<mainRoute.length-4&&straightCell(p)).filter((p,i)=>i%2===0);
for(let r=1;r<SIZE-1;r++)for(let c=1;c<SIZE-1;c++){const p={c,r};if(mazeOpen(c,r)&&straightCell(p)&&!mainKeys.has(`${c},${r}`)&&Math.hypot(c-START.c,r-START.r)>5&&hazardCells.every(o=>Math.hypot(c-o.c,r-o.r)>=2))hazardCells.push(p);}
export const RIDE_OBSTACLES=hazardCells.map((p,i)=>{const vertical=mazeOpen(p.c,p.r-1),side=i%2?1:-1,point=centre(p.c,p.r),kind=i%4===2?'barricade':'crate';return {...p,id:i,kind,vertical,side,x:point.x+(vertical&&kind==='crate'?side*17:0),y:point.y+(!vertical&&kind==='crate'?side*17:0)};});
export function escapePose(s){const t=s.age,walking=Math.max(0,Math.min(1,(t-1)/5.5)),drive=Math.max(0,t-8.5);return {person:{x:160+walking*191,y:185+walking*121,face:'right',walk:t*12,spriteHeight:60},personVisible:t<7.4,door:t<6?0:t<7.5?Math.min(1,(t-6)*2):Math.max(0,1-(t-7.5)*2),carX:350+drive*drive*12,carY:285,wheel:drive*18,driving:drive>0};}

export function jumpRide(s){if(s.paused||s.phase!=='ride'||s.jumpCooldown>0)return false;s.jumpAge=.001;s.jumpCooldown=1.15;s.jumpZ=0;s.jumps++;return true;}
function sightClear(a,b){const steps=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/8);for(let i=0;i<=steps;i++){const t=i/Math.max(1,steps);if(!mazeOpen(Math.floor((a.x+(b.x-a.x)*t)/TILE),Math.floor((a.y+(b.y-a.y)*t)/TILE)))return false;}return true;}
function tickInk(s,dt){const target=cartPosition(s);if(s.spiderActive){s.inkClock-=dt;const distance=Math.hypot(target.x-s.spider.x,target.y-s.spider.y);if(s.inkClock<=0&&distance>65&&distance<460&&sightClear(s.spider,target)){const dx=target.x-s.spider.x,dy=target.y-s.spider.y,n=Math.hypot(dx,dy);s.ink.push({x:s.spider.x,y:s.spider.y,vx:dx/n*235,vy:dy/n*235,age:0});s.inkShots++;s.inkClock=3.2+(Math.sin(s.inkShots*7.31)+1)*1.25;}}for(const shot of s.ink){shot.age+=dt;const steps=Math.max(1,Math.ceil(dt/.01));for(let i=0;i<steps;i++){shot.x+=shot.vx*dt/steps;shot.y+=shot.vy*dt/steps;if(!mazeOpen(Math.floor(shot.x/TILE),Math.floor(shot.y/TILE))){shot.dead=true;break;}if(Math.hypot(shot.x-target.x,shot.y-target.y)<17&&s.jumpZ<23){shot.dead=true;s.inkHits++;s.inkObscure=3.8;break;}}}s.ink=s.ink.filter(p=>!p.dead&&p.age<2.5);}

function makeEndingLeaves(){return Array.from({length:38},(_,i)=>{const t=(i%28)/27;return {x:i<28?160+t*191+Math.sin(i*4)*21:75+(i*43)%350,y:i<28?195+t*111+Math.cos(i*3)*12:285+i%5*9,z:0,age:0,turn:i*2.4,vx:0,vy:0,lifted:false};});}
function tickEndingLeaves(s,dt){const pose=escapePose(s),p=pose.person;for(const leaf of s.endingLeaves){if(pose.personVisible&&!leaf.lifted&&Math.hypot(leaf.x-p.x,leaf.y-p.y)<22){leaf.lifted=true;leaf.age=.001;leaf.vx=13+Math.sin(leaf.turn)*11;leaf.vy=Math.cos(leaf.turn)*9;s.endingLeafFlights++;}if(leaf.age>0&&leaf.age<1.8){leaf.age+=dt;leaf.x+=leaf.vx*dt;leaf.y+=leaf.vy*dt;leaf.z=Math.sin(Math.min(1,leaf.age/1.8)*Math.PI)*11;leaf.turn+=dt*2.5;}}}

export function endingCamera(s){const t=s.age,follow=Math.max(0,Math.min(1,(t-9)/1.8)),zoom=1+follow*.65,pose=escapePose(s);return {zoom,x:follow*(pose.carX-270/zoom),y:follow*(pose.carY-230/zoom),iris:Math.max(0,Math.min(1,(t-10.3)/2.9)),title:Math.max(0,Math.min(1,(t-13.2)/1.1)),shadowVisible:t>=7.1&&t<8.8};}
