import {WARDROBE} from './gallery-wardrobe.js';
export const GALLERY={width:480,height:1440,cart:{x:240,y:153},start:{x:240,y:1280}};
export const CLOTHES=Array.from({length:19},(_,i)=>({id:i,design:WARDROBE[i],x:156+(i*67)%174,y:270+(i*127)%990,kind:i%8,angle:Math.sin(i*3)*1.8}));
export const EFFIGIES=Array.from({length:8},(_,i)=>({x:i%2?405:75,y:290+Math.floor(i/2)*250,side:i%2?1:-1,phase:i*1.7}));
export function newGallery(){return {level:10,x:240,y:1280,spriteHeight:68,face:'up',moving:false,walk:0,time:0,age:0,phase:'landing',paused:false,cameraX:0,cameraY:1080,footprints:[],step:0,dust:Array.from({length:60},(_,i)=>({x:240+Math.sin(i*2.4)*90,y:1320+Math.cos(i)*22,age:0,life:3+i%5,vx:Math.sin(i*2.4)*14,vy:-7-i%9})),notice:'Small shoes. Coats. Everywhere.',noticeAge:4,boarded:false,drips:[],wet:[],dripClock:0,dripCount:0,clothes:CLOTHES.map(c=>({...c,z:0,age:0,cooldown:0,flights:0})),clothFlights:0};}
export function galleryBlocked(x,y){return x<139||x>341||y<107||y>1332||(x>214&&x<266&&y>112&&y<192);}
export function boardCart(s){if(s.paused||!['explore','flee'].includes(s.phase)||Math.hypot(s.x-240,s.y-194)>82)return false;s.phase='boarding';s.age=0;s.boardFrom={x:s.x,y:s.y};s.notice='';s.noticeAge=0;return true;}
export function tickGallery(s,input,dt){if(s.paused||s.phase==='complete')return;dt=Math.min(.04,Math.max(0,dt));s.time+=dt;s.age+=dt;s.noticeAge=Math.max(0,s.noticeAge-dt);s.moving=false;
if(s.phase==='landing'&&s.age>1.6){s.phase='explore';s.age=0;}
if(['explore','flee'].includes(s.phase)){let dx=Number(!!input.right)-Number(!!input.left),dy=Number(!!input.down)-Number(!!input.up);if(input.target&&!dx&&!dy){dx=input.target.x-s.x;dy=input.target.y-s.y;}const n=Math.hypot(dx,dy),speed=s.phase==='flee'?130:88;if(n>.5){const dist=Math.min(speed*dt,input.target?n:Infinity),ox=s.x,oy=s.y,x=s.x+dx/n*dist,y=s.y+dy/n*dist;if(!galleryBlocked(x,s.y))s.x=x;if(!galleryBlocked(s.x,y))s.y=y;s.moving=Math.hypot(s.x-ox,s.y-oy)>.01;if(s.moving){s.face=Math.abs(dx)>Math.abs(dy)?dx<0?'left':'right':dy<0?'up':'down';s.walk+=dt*(s.phase==='flee'?16:10);s.step+=dist;if(s.step>17){s.step=0;s.footprints.push({x:s.x,y:s.y,age:0,side:Math.floor(s.walk)%2});}}}if(s.phase==='explore'&&s.y<1010){s.phase='flee';s.age=0;s.notice='Are the bones from.....? I have to get out of here.';s.noticeAge=5;}}
if(s.phase==='boarding'){const t=Math.min(1,s.age/1.1),e=t*t*(3-2*t);s.x=s.boardFrom.x+(240-s.boardFrom.x)*e;s.y=s.boardFrom.y+(165-s.boardFrom.y)*e;s.face='up';s.moving=t<.65;s.walk+=dt*10;if(s.age>1.7){s.boarded=true;s.phase='complete';}}
s.dripClock+=dt;if(s.dripClock>.14){s.dripClock=0;const i=s.dripCount++;s.drips.push({id:i,x:160+(i*71)%164,y:180+(i*193)%1110,z:120+i%55,vy:0});}for(const d of s.drips){d.vy+=280*dt;d.z-=d.vy*dt;if(d.z<=0){s.wet.push({id:d.id,x:d.x,y:d.y,age:0,r:5+s.dripCount%5});}}s.drips=s.drips.filter(d=>d.z>0);for(const p of s.wet)p.age+=dt;s.wet=s.wet.filter(p=>p.age<24);for(const c of s.clothes){c.cooldown=Math.max(0,c.cooldown-dt);if(s.moving&&Math.hypot(s.x-c.x,s.y-c.y)<29&&c.cooldown===0){const a=Math.atan2(c.y-s.y,c.x-s.x);c.from={x:c.x,y:c.y};c.to={x:Math.max(146,Math.min(334,c.x+Math.cos(a)*(c.kind===7?2:20))),y:c.y+Math.sin(a)*(c.kind===7?2:17)};c.age=0;c.cooldown=3;c.flights++;s.clothFlights++;}if(c.from){c.age+=dt;const t=Math.min(1,c.age/1.3);c.x=c.from.x+(c.to.x-c.from.x)*t;c.y=c.from.y+(c.to.y-c.from.y)*t;c.z=Math.sin(t*Math.PI)*(c.kind===7?0:c.kind===6?5:12);c.angle+=dt*(c.kind===7?.08:.8);if(t===1){c.from=null;c.z=0;}}}for(const p of s.footprints)p.age+=dt;s.footprints=s.footprints.filter(p=>p.age<12);for(const p of s.dust){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}s.dust=s.dust.filter(p=>p.age<p.life);s.cameraY+=(Math.max(0,Math.min(1080,s.y-240))-s.cameraY)*Math.min(1,dt*7);}
// A single forward track keeps left/right in screen space throughout the chase.
export const TILE=80,SIZE=171,COLS=6,DIRS={up:[0,-1],right:[1,0],down:[0,1],left:[-1,0]},START={c:2.5,r:169},EXIT={c:2.5,r:1};
export const MAZE=Array.from({length:SIZE},(_,r)=>Array.from({length:COLS},(_,c)=>r>0&&r<SIZE-1&&c>0&&c<COLS-1?0:1));
export const mazeOpen=(c,r)=>c>=0&&r>=0&&c<COLS&&r<SIZE&&MAZE[r][c]===0;
export const centre=(c,r)=>({x:(c+.5)*TILE,y:(r+.5)*TILE});
export const RIDE_LANES=[160,240,320],CART_RAIL_HALF=16.3;
export const RIDE_LENGTH=(START.r-EXIT.r)*TILE;
function actor(r){return {c:2.5,r,...centre(2.5,r),dir:'up',distance:0,lane:0,laneTarget:0};}
export const RIDE_OBSTACLES=Array.from({length:64},(_,i)=>{const y=centre(START.c,START.r).y-1000-i*185,kind=['crate','barricade','rubble','oil','dynamite','crate','rubble','dynamite'][i%8],lane=[-1,0,1,0,-1,1,-1,1][i%8],base={id:i*2,kind,vertical:true,side:lane,x:240+lane*80,y,c:2.5+lane,r:Math.floor(y/TILE),width:kind==='barricade'?250:kind==='oil'?62:46};if(i>=36&&kind==='barricade')return [base,{...base,id:i*2+1,kind:'rubble',x:240,side:0,width:46}];if(i>=44&&kind==='dynamite')return [base,{...base,id:i*2+1,kind:'crate',x:240,side:0,width:46}];return kind==='crate'&&i>8?[base,{...base,id:i*2+1,x:240,side:0}]:[base];}).flat();
export function newRide(){return {level:11,moving:false,rideAge:0,integrity:3,obstacleHits:0,hitObstacles:[],impact:0,skid:0,exploded:[],explosions:[],explosionCount:0,spiderlings:[],broodClock:5,broods:0,spiderlingHits:0,minionGrace:0,speed:150,jumpAge:0,jumpZ:0,jumpCooldown:0,jumps:0,fragments:[],ink:[],inkClock:3.2,inkShots:0,inkHits:0,inkObscure:0,endingLeafFlights:0,endingLeaves:makeEndingLeaves(),time:0,age:0,phase:'ready',paused:false,cart:actor(START.r),spider:actor(START.r),queued:null,spiderActive:false,cameraX:0,cameraY:centre(START.c,START.r).y-225,turns:0,visited:[],exit:0,notice:'The cart drives itself. Left and right dodge debris. Jump the striped barricades. Keep clear of oil and the spider’s ink.',noticeAge:4};}
export function startRide(s){if(s.phase!=='ready'||s.paused)return false;s.phase='ride';s.age=0;return true;}
export function queueRideTurn(s,dir){if(s.paused||!['ready','ride'].includes(s.phase))return false;s.queued=['left','right'].includes(dir)?dir:null;s.cart.laneTarget=s.queued==='left'?RIDE_LANES[0]-240:s.queued==='right'?RIDE_LANES[2]-240:0;return true;}
export function cartPosition(s){return {x:s.cart.x+s.cart.lane,y:s.cart.y};}
export function tickRide(s,input,dt){if(s.paused||['complete','ready'].includes(s.phase))return;if(s.phase==='caught'){s.age+=Math.min(.04,dt);return;}dt=Math.min(.04,Math.max(0,dt));s.time+=dt;s.age+=dt;s.noticeAge=Math.max(0,s.noticeAge-dt);queueRideTurn(s,input.turn);if(s.phase==='escape'){tickEndingLeaves(s,dt);s.exit=Math.min(1,s.age);if(s.age>16.5)s.phase='complete';return;}
 s.impact=Math.max(0,s.impact-dt);s.skid=Math.max(0,s.skid-dt);const cruise=150+Math.min(80,s.rideAge*1.1);s.speed+=((s.impact>0?75:s.skid>0?110:cruise)-s.speed)*Math.min(1,dt*(s.impact>0?20:3));s.jumpCooldown=Math.max(0,s.jumpCooldown-dt);if(input.jump)jumpRide(s);if(s.jumpAge>0){s.jumpAge+=dt;s.jumpZ=Math.sin(Math.min(1,s.jumpAge/.95)*Math.PI)*42;if(s.jumpAge>=.95){s.jumpAge=0;s.jumpZ=0;}}s.inkObscure=Math.max(0,s.inkObscure-dt);for(const f of s.fragments){f.age+=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.z=Math.max(0,f.z+f.vz*dt);f.vz-=165*dt;}s.fragments=s.fragments.filter(f=>f.age<2.2);
 s.rideAge+=dt;if(!s.spiderActive&&s.rideAge>6){s.spiderActive=true;s.spider.y=s.cart.y+235;}const step=s.speed*dt;s.cart.distance+=step;s.cart.y-=step;s.cart.r=Math.floor(s.cart.y/TILE);s.cart.lane+=(s.cart.laneTarget-s.cart.lane)*Math.min(1,dt*(s.skid>0?3:12));s.moving=true;
 if(s.cart.y<=centre(EXIT.c,EXIT.r).y){s.phase='escape';s.age=0;s.notice='Cold air. The way out.';s.noticeAge=2;return;}
 const point=cartPosition(s);for(const o of RIDE_OBSTACLES){if(o.kind==='dynamite')continue;const inside=Math.abs(point.x-o.x)<o.width/2+13&&Math.abs(point.y-o.y)<21;if(!s.hitObstacles.includes(o.id)&&inside&&(o.kind==='rubble'||s.jumpZ<23)){s.hitObstacles.push(o.id);s.obstacleHits++;if(o.kind==='oil'){s.skid=1.5;s.impact=.25;s.speed=105;}else{s.integrity=Math.max(0,s.integrity-1);s.impact=.9;s.speed=75;for(let j=0;j<18;j++){const a=j*2.4;s.fragments.push({x:o.x,y:o.y,z:12,age:0,vx:Math.cos(a)*(22+j%5*9),vy:Math.sin(a)*(20+j%4*8),vz:40+j%7*9,angle:a,kind:o.kind});}}}}
 if(s.spiderActive){const gap=s.spider.y-s.cart.y;s.spider.y-=(cruise-14+Math.max(0,gap-175)*.45)*dt;s.spider.x+=(point.x-s.spider.x)*Math.min(1,dt*1.4);s.spider.r=Math.floor(s.spider.y/TILE);if(s.spider.y-s.cart.y<37){s.phase='caught';s.age=0;return;}}
 tickDynamite(s,dt);tickSpiderlings(s,dt,cruise);tickInk(s,dt);s.cameraX=0;s.cameraY=Math.max(0,s.cart.y-225);
}
function tickDynamite(s,dt){const p=cartPosition(s);for(const o of RIDE_OBSTACLES)if(o.kind==='dynamite'&&!s.exploded.includes(o.id)&&s.cart.y-o.y<85&&s.cart.y-o.y> -30){s.exploded.push(o.id);s.explosionCount++;s.explosions.push({id:o.id,x:o.x,y:o.y,age:0,hit:false});}for(const blast of s.explosions){blast.age+=dt;if(!blast.hit&&blast.age<.4&&Math.abs(p.x-blast.x)<66&&Math.abs(p.y-blast.y)<96){blast.hit=true;s.obstacleHits++;s.hitObstacles.push(blast.id);s.integrity=Math.max(0,s.integrity-1);s.impact=1;s.speed=75;}}s.explosions=s.explosions.filter(b=>b.age<.75);}
function tickSpiderlings(s,dt,cruise){s.minionGrace=Math.max(0,s.minionGrace-dt);if(!s.spiderActive)return;s.broodClock-=dt;const p=cartPosition(s);if(s.broodClock<=0&&s.spiderlings.length===0){s.broods++;s.spiderlings.push({x:s.spider.x-10,y:s.spider.y-15,age:0,committed:false,targetX:Math.max(160,Math.min(320,p.x)),phase:s.broods});s.broodClock=Math.max(6,9-s.rideAge*.025);}for(const little of s.spiderlings){little.age+=dt;const gap=little.y-p.y;if(!little.committed){little.x+=(little.targetX-little.x)*Math.min(1,dt*3);if(gap<100)little.committed=true;}little.y-=(cruise+72)*dt;if(Math.hypot(little.x-p.x,little.y-p.y)<23&&s.jumpZ<23){little.dead=true;if(s.minionGrace===0){s.minionGrace=.7;s.spiderlingHits++;s.obstacleHits++;s.impact=.35;s.speed=115;}}}s.spiderlings=s.spiderlings.filter(a=>!a.dead&&a.age<5&&a.y>s.cart.y-170);}
export function escapePose(s){const t=s.age,walking=Math.max(0,Math.min(1,(t-1)/5.5)),drive=Math.max(0,t-8.5);return {person:{x:160+walking*125,y:185+walking*84,face:'right',walk:t*12,spriteHeight:68},personVisible:t<6.5,door:0,carX:322+drive*drive*15,carY:282,wheel:drive*18,driving:drive>0};}

export function jumpRide(s){if(s.paused||s.phase!=='ride'||s.jumpCooldown>0)return false;s.jumpAge=.001;s.jumpCooldown=1.15;s.jumpZ=0;s.jumps++;return true;}
function sightClear(a,b){const steps=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/8);for(let i=0;i<=steps;i++){const t=i/Math.max(1,steps);if(!mazeOpen(Math.floor((a.x+(b.x-a.x)*t)/TILE),Math.floor((a.y+(b.y-a.y)*t)/TILE)))return false;}return true;}
function tickInk(s,dt){const target=cartPosition(s);if(s.spiderActive){s.inkClock-=dt;const distance=Math.hypot(target.x-s.spider.x,target.y-s.spider.y);if(s.inkClock<=0&&distance>65&&distance<460&&sightClear(s.spider,target)){const dx=target.x-s.spider.x,dy=target.y-s.spider.y,n=Math.hypot(dx,dy);s.ink.push({x:s.spider.x,y:s.spider.y,vx:dx/n*(s.speed+95),vy:dy/n*(s.speed+95),age:0});s.inkShots++;s.inkClock=3.2+(Math.sin(s.inkShots*7.31)+1)*1.25;}}for(const shot of s.ink){shot.age+=dt;const steps=Math.max(1,Math.ceil(dt/.01));for(let i=0;i<steps;i++){shot.x+=shot.vx*dt/steps;shot.y+=shot.vy*dt/steps;if(!mazeOpen(Math.floor(shot.x/TILE),Math.floor(shot.y/TILE))){shot.dead=true;break;}if(Math.hypot(shot.x-target.x,shot.y-target.y)<17&&s.jumpZ<23){shot.dead=true;s.inkHits++;s.inkObscure=3.8;break;}}}s.ink=s.ink.filter(p=>!p.dead&&p.age<2.5);}

function makeEndingLeaves(){return Array.from({length:38},(_,i)=>{const t=(i%28)/27;return {x:i<28?160+t*191+Math.sin(i*4)*21:75+(i*43)%350,y:i<28?195+t*111+Math.cos(i*3)*12:285+i%5*9,z:0,age:0,turn:i*2.4,vx:0,vy:0,lifted:false};});}
function tickEndingLeaves(s,dt){const pose=escapePose(s),p=pose.person;for(const leaf of s.endingLeaves){if(pose.personVisible&&!leaf.lifted&&Math.hypot(leaf.x-p.x,leaf.y-p.y)<22){leaf.lifted=true;leaf.age=.001;leaf.vx=13+Math.sin(leaf.turn)*11;leaf.vy=Math.cos(leaf.turn)*9;s.endingLeafFlights++;}if(leaf.age>0&&leaf.age<1.8){leaf.age+=dt;leaf.x+=leaf.vx*dt;leaf.y+=leaf.vy*dt;leaf.z=Math.sin(Math.min(1,leaf.age/1.8)*Math.PI)*11;leaf.turn+=dt*2.5;}}}

export function endingCamera(s){const t=s.age,follow=Math.max(0,Math.min(1,(t-9)/1.8)),zoom=1+follow*.65,pose=escapePose(s);return {zoom,x:follow*(pose.carX-270/zoom),y:follow*(pose.carY-230/zoom),iris:0,title:Math.max(0,Math.min(1,(t-13.2)/1.1)),shadowVisible:t>=7.1&&t<8.8};}
