export const HALL_OBJECTS=[{id:'ledger',x:126,y:146,r:23,label:'READ · ticket ledger'},{id:'lamp',x:154,y:143,r:18,label:'SWITCH · desk lamp'},{id:'drawer',x:338,y:187,r:25,label:'OPEN · cupboard drawer'},{id:'staff-door',x:408,y:146,r:34,label:'TRY · red staff door'},{id:'onward',x:405,y:327,r:42,label:'EXAMINE · attraction stairs'}];
export function newHall(){return {x:268,y:116,face:'down',walk:0,time:0,light:false,lamp:true,ledger:false,drawer:false,drawerProgress:0,drawerOpening:false,door:false};}
const floors=[[58,134,433,199],[157,105,308,199],[58,196,242,226],[327,134,457,168],[378,174,432,353]];
export const CUPBOARD={x:338,y:161,left:315,right:361,top:143,bottom:174};
export function tickHallDrawer(s,dt){if(!s.drawerOpening)return false;s.drawerProgress=Math.min(1,(s.drawerProgress||0)+dt/.85);if(s.drawerProgress<1)return false;s.drawerOpening=false;s.drawer=true;return true;}
export function hallBlocked(x,y,r=4){if(x+r>CUPBOARD.left&&x-r<CUPBOARD.right&&y+r>CUPBOARD.top&&y-r<CUPBOARD.bottom)return true;if(x+r>54&&x-r<77&&y+r>208&&y-r<226)return true;return ![[-r,-r],[r,-r],[-r,r],[r,r]].every(([dx,dy])=>floors.some(([a,b,c,d])=>x+dx>=a&&x+dx<=c&&y+dy>=b&&y+dy<=d));}
export function moveHall(s,dx,dy,dt){const oldX=s.x,oldY=s.y,n=Math.hypot(dx,dy)||1,a=65*dt;if(!hallBlocked(s.x+dx/n*a,s.y))s.x+=dx/n*a;if(!hallBlocked(s.x,s.y+dy/n*a))s.y+=dy/n*a;s.moving=Math.hypot(s.x-oldX,s.y-oldY)>.001;if(s.moving){s.walk+=dt*9;s.face=Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up';}}
export function hallNear(s){return HALL_OBJECTS.filter(o=>Math.hypot(s.x-o.x,s.y-o.y)<o.r).sort((a,b)=>Math.hypot(s.x-a.x,s.y-a.y)-Math.hypot(s.x-b.x,s.y-b.y))[0];}
export function hallPath(s,x,y){const cell=5,key=p=>p.join(','),start=[Math.round(s.x/cell),Math.round(s.y/cell)],q=[start],prev=new Map([[key(start),null]]);let end;for(let i=0;i<q.length;i++){const p=q[i];if(Math.hypot(p[0]*cell-x,p[1]*cell-y)<6){end=p;break;}for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const n=[p[0]+dx,p[1]+dy];if(!prev.has(key(n))&&!hallBlocked(n[0]*cell,n[1]*cell)){prev.set(key(n),p);q.push(n);}}}const route=[];for(let p=end;p;p=prev.get(key(p)))route.unshift({x:p[0]*cell,y:p[1]*cell});return route.slice(1);}
