export const ROWS=[300,228,156];
export const CONSOLES=[{x:151,y:314,r:33},{x:648,y:230,r:33},{x:150,y:161,r:33}];
export const SETTINGS=[[2,1,0],[1,2,1],[2,0,2]];
export const RIDDLES=['Two feed pumps. One drive tooth. Keep the vent closed.','One feed pump. Two drive teeth. Open the vent halfway.','Both feed pumps. Disengage the drive. Open the vent fully.'];
const fixed=[[30,347,86,453],[58,287,142,358],[132,278,185,320],[628,141,665,319],[134,134,181,255],[602,82,674,182]];
export function newMezzanine(){return {x:63,y:420,face:'up',spriteHeight:62,moving:false,walk:0,time:0,cameraX:0,cameraY:120,stage:0,health:3,phase:'explore',paused:false,inspection:false,inspected:0,banks:ROWS.map(()=>({settings:[0,0,0],timer:0,align:0,completed:false})),checkpoint:{x:151,y:310,stage:0},scarf:false,hits:0,steamHits:0,invincible:0,notice:'The floor moves with the engine. Find the first brake console.',noticeAge:6};}
export function panels(s,row){const bank=s.banks[row];return Array.from({length:9},(_,i)=>({id:`panel-${row}-${i}`,row,x:180+i*50,y:ROWS[row]-16+(1-bank.align)*Math.sin(s.time*.95+i*.86+row)*21,w:50,h:32}));}
export function steamVents(s){return ROWS.flatMap((y,row)=>[310,461].map((x,i)=>{const phase=(s.time+row*.7+i*1.9)%4.8;return {row,x,y,phase,warning:phase<.9,active:phase>=.9&&phase<1.65};}));}
function floor(s,x,y){return fixed.some(([a,b,c,d])=>x>=a&&x<=c&&y>=b&&y<=d)||ROWS.some((_,r)=>panels(s,r).some(p=>x>=p.x&&x<=p.x+p.w&&y>=p.y&&y<=p.y+p.h));}
export function mezzBlocked(s,x,y,r=5){if(s.stage===0&&y<278)return true;if(s.stage===1&&y<205)return true;if(s.stage===2&&x>619&&y<132)return true;return ![[-r,-r],[r,-r],[-r,r],[r,r]].every(([dx,dy])=>floor(s,x+dx,y+dy));}
export function mezzPath(s,x,y){const cell=6,W=121,H=81,key=(a,b)=>b*W+a,prev=new Map(),q=[];function nearest(x,y){const a=Math.round(x/cell),b=Math.round(y/cell);for(let r=0;r<6;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++)if(!mezzBlocked(s,(a+dx)*cell,(b+dy)*cell))return [a+dx,b+dy];}const a=nearest(s.x,s.y),b=nearest(x,y);if(!a||!b)return [];q.push(a);prev.set(key(...a),null);for(let i=0;i<q.length;i++){const p=q[i];if(p[0]===b[0]&&p[1]===b[1]){const route=[];let k=key(...p);while(prev.get(k)!==null){route.push({x:k%W*cell,y:Math.floor(k/W)*cell});k=prev.get(k);}return route.reverse();}for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=p[0]+dx,ny=p[1]+dy,k=key(nx,ny);if(nx<0||ny<0||nx>=W||ny>=H||prev.has(k)||mezzBlocked(s,nx*cell,ny*cell))continue;prev.set(k,key(...p));q.push([nx,ny]);}}return [];}
export function mezzAction(s){if(s.paused||s.phase!=='explore')return false;const i=CONSOLES.findIndex(o=>Math.hypot(o.x-s.x,o.y-s.y)<o.r);if(i<0||i>s.stage||s.banks[i].completed)return false;s.inspection=true;s.inspected=i;return true;}
export function setMezzLever(s,i){if(!s.inspection||s.paused)return;s.banks[s.inspected].settings[i]=(s.banks[s.inspected].settings[i]+1)%3;}
export function engageMezzBrake(s){if(!s.inspection||s.paused)return false;const bank=s.banks[s.inspected];if(bank.settings.some((v,i)=>v!==SETTINGS[s.inspected][i])){s.notice='The gauges disagree. The brake will not catch.';s.noticeAge=5;return false;}bank.timer=15;bank.align=1;s.notice='Brake engaged for 15 seconds. Cross before the floor releases!';s.noticeAge=5;return true;}
function hurt(s,steam=false){if(s.invincible>0)return;s.health--;s.hits++;if(steam)s.steamHits++;s.invincible=2;s.x=s.checkpoint.x;s.y=s.checkpoint.y;s.banks[s.stage]&&(s.banks[s.stage].timer=0);s.notice=steam?'The steam drives you back. Wait for the hiss to stop.':'The brake released. You scramble back to the fixed landing.';s.noticeAge=5;if(s.health<=0)s.phase='caught';}
export function retryMezzanine(s){const n=newMezzanine();n.stage=s.checkpoint.stage;n.checkpoint={...s.checkpoint};n.x=n.checkpoint.x;n.y=n.checkpoint.y;n.scarf=s.scarf;for(let i=0;i<n.stage;i++)Object.assign(n.banks[i],{completed:true,align:1,timer:0,settings:[...SETTINGS[i]]});return n;}
export function tickMezzanine(s,input,dt){if(s.paused||s.inspection||s.phase!=='explore')return;s.time+=dt;s.noticeAge=Math.max(0,s.noticeAge-dt);s.invincible=Math.max(0,s.invincible-dt);for(const b of s.banks){b.timer=Math.max(0,b.timer-dt);b.align+=(Number(b.completed||b.timer>0)-b.align)*Math.min(1,dt*3);}
let dx=Number(input.right||false)-Number(input.left||false),dy=Number(input.down||false)-Number(input.up||false);if(input.target){dx=input.target.x-s.x;dy=input.target.y-s.y;}const n=Math.hypot(dx,dy),dist=Math.min(88*dt,input.target?n:Infinity),ox=s.x,oy=s.y;s.moving=false;if(n){const steps=Math.ceil(dist/2);for(let i=0;i<steps;i++){const x=s.x+dx/n*dist/steps,y=s.y+dy/n*dist/steps;if(!mezzBlocked(s,x,s.y))s.x=x;if(!mezzBlocked(s,s.x,y))s.y=y;}s.moving=Math.hypot(s.x-ox,s.y-oy)>.01;if(s.moving){s.walk+=dt*11;s.face=Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up';}}
const row=s.stage;if(row<3){const bank=s.banks[row],onBank=s.x>181&&s.x<627&&Math.abs(s.y-ROWS[row])<42;if(onBank&&bank.timer===0&&!bank.completed)hurt(s);if(bank.timer>0&&((row%2===0&&s.x>636)||(row===1&&s.x<169))&&Math.abs(s.y-ROWS[row])<26){bank.completed=true;bank.align=1;s.stage++;s.checkpoint={x:s.stage===2?151:646,y:ROWS[row],stage:s.stage};s.notice=s.stage===3?'All three stages are clear. The workshop door is ahead.':'Safe landing. The next console uses a different pressure setting.';s.noticeAge=6;}}
for(const v of steamVents(s))if(v.active&&Math.hypot(s.x-v.x,s.y-v.y)<15)hurt(s,true);
if(!s.scarf&&Math.hypot(s.x-503,s.y-228)<24){s.scarf=true;s.notice='A red scarf caught in the rail. A child made it this far.';s.noticeAge=6;}
s.cameraX=Math.max(0,Math.min(240,s.x-240));s.cameraY=Math.max(0,Math.min(120,s.y-235));if(s.stage===3&&s.x>608&&s.y<100)s.phase='escaped';}
