import {newClown,tickClown} from './clown-actor.js';
import {newAmbush,tickAmbush,ambushHazards,arrowHits} from './platform-ambush.js';
import {STAIR_PATHS,stairPose} from './platform-stairs.js';
import {newSpiders,tickSpiders,spiderHazards} from './platform-spiders.js';
// Side-view coordinates; y is the actor's feet. Shared geometry drives drawing and collisions.
export const FLOOR_Y=[690,493,355,181];
export const START_X=[95,887,68,890];
export const STAIRS=STAIR_PATHS.map(a=>({x:a.points[0][0],to:a.to}));
export const SOLIDS=[{id:'crate',floor:0,x:493,w:36,h:30},{id:'gate',floor:0,x:657,w:17,h:58},{id:'motor',floor:1,x:620,w:38,h:25},{id:'exit-gate',floor:2,x:825,w:16,h:57},{id:'trunk',floor:3,x:550,w:38,h:27}];
export function newPlatform(floor=0){floor=Math.max(0,Math.min(3,floor));return {x:START_X[floor],y:FLOOR_Y[floor],vx:0,vy:0,floor,time:0,floorTime:0,walk:0,face:'right',light:true,grounded:true,coyote:.1,jumpBuffer:0,jumpHeld:false,jumpAge:0,landingAge:0,health:3,invincible:1,checkpoint:floor,power:floor>0,powerAge:floor>0?10:0,riddleSolved:floor>0,lever:floor>0?1:0,pulling:false,inspection:null,puzzleMessage:'',stairCooldown:0,clown:newClown(floor),spiders:newSpiders(),ambush:newAmbush(floor),fuses:Array.from({length:Math.min(floor,3)},(_,i)=>i),status:'playing',paused:false,stair:null,chaser:955,flash:0,cooldown:0,hits:0,notice:floor?'CHECKPOINT · SAFE LANDING':'Inspect the wall inscription. Solve its riddle and pull the red lever.',noticeAge:5};}
export function activeSolids(s){return SOLIDS.filter(o=>o.floor===s.floor&&!(o.id==='gate'&&s.power)&&!(o.id==='exit-gate'&&s.fuses.length===3));}
export function platforms(s){return [0,1,2].map(i=>({id:'lift-'+i,x:535+i*76,w:64,y:355-14*Math.sin(s.floorTime*1.6+i*1.4)}));}
export function hazards(s){const list=[];if(s.floor===1){const phase=s.floorTime%4.4;list.push({id:'barrel',kind:'barrel',x:phase<1.1?69:69+(phase-1.1)*246,y:493-14,r:14,active:phase>=1.1,warning:phase<1.1,until:Math.max(0,1.1-phase)});}if(s.floor===2){list.push(...spiderHazards(s));}if(s.floor===3){const phase=s.floorTime%3.9;list.push({id:'press',kind:'press',x:350,y:phase<1.25?115:phase<1.65?115+(phase-1.25)/.4*57:phase<2.25?172:phase<2.8?172-(phase-2.25)/.55*57:115,r:19,active:phase>=1.25&&phase<2.8,warning:phase<1.25,until:Math.max(0,1.25-phase)});}return list.concat(ambushHazards(s));}
export function retryPlatform(s){const next=newPlatform(s.checkpoint);next.hits=s.hits;Object.assign(s,next);}
function hit(s,text,resetPosition=false){if(s.invincible>0)return;s.health--;s.hits++;s.invincible=1.6;s.notice=text;s.noticeAge=2.5;if(s.health<=0){s.status='caught';return;}if(resetPosition){s.x=START_X[s.floor];s.y=FLOOR_Y[s.floor];s.vy=0;s.grounded=true;s.chaser=955;}else{s.vy=-105;s.grounded=false;}}
export function answerPowerRiddle(s,answer){if(s.inspection!=='power'||s.paused||s.power)return false;s.riddleSolved=answer==='clock';s.puzzleMessage=s.riddleSolved?'Correct. The clock releases the safety catch. Pull the red lever.':'That is not it. Think about the hands on a face.';return s.riddleSolved;}
export function pullPowerLever(s){if(s.inspection!=='power'||s.paused||!s.riddleSolved||s.power)return false;s.pulling=true;return true;}
export function closePowerInspection(s){s.inspection=null;s.pulling=false;if(!s.power)s.lever=0;}
export function platformAction(s){if(s.paused||s.status!=='playing'||s.stair||s.inspection)return;if(s.floor===0&&Math.abs(s.x-360)<44&&Math.abs(s.y-690)<38){s.inspection='power';s.puzzleMessage=s.power?'The mains are on. The machinery is awake.':s.riddleSolved?'The safety catch is released. Pull the red lever.':'Solve the wall inscription to release the safety catch.';return;}if(s.floor===3&&Math.abs(s.x-145)<48){if(s.fuses.length===3)s.status='escaped';else{s.notice='The exit needs all three brass fuses.';s.noticeAge=3;}}}
function enterLanding(s,floor){s.floor=floor;s.ambush=newAmbush(floor);s.floorTime=0;s.stair=null;s.stairCooldown=.3;s.vy=0;s.grounded=true;s.chaser=955;if(floor>s.checkpoint){s.checkpoint=floor;s.health=3;s.invincible=1.6;}s.notice=floor===3?'RUN LEFT · Flash the pursuer with F. Reach the EXIT.':'LANDING · FLOOR '+(floor+1);s.noticeAge=4;}
function tryStairs(s,input){if(!s.grounded||s.stairCooldown>0)return false;const direction=(input.right?1:0)-(input.left?1:0);for(let i=0;i<STAIR_PATHS.length;i++){const a=STAIR_PATHS[i],base=a.points[0],top=a.points.at(-1);if(s.floor===a.from&&Math.hypot(s.x-base[0],s.y-base[1])<20&&(input.up||direction===a.dir)){if(!s.power||!s.fuses.includes(s.floor)){s.notice=!s.power?'Solve the wall riddle and pull the red lever.':'Take the glowing brass fuse before going upstairs.';s.noticeAge=2;return false;}s.stair={index:i,distance:0};return true;}if(s.floor===a.to&&Math.hypot(s.x-top[0],s.y-top[1])<24&&input.down){s.stair={index:i,distance:a.length};return true;}}return false;}
export function tickPlatform(s,input,dt){if(s.paused||s.status!=='playing')return;dt=Math.max(0,Math.min(.05,dt));if(s.inspection){if(s.pulling){s.lever=Math.min(1,s.lever+dt/1.1);if(s.lever===1){s.power=true;s.pulling=false;s.puzzleMessage='POWER RESTORED. The safety gate is open.';s.notice='POWER RESTORED · Something heard that.';s.noticeAge=5;}}return;}if(s.power)s.powerAge=(s.powerAge||0)+dt;s.landingAge=Math.max(0,(s.landingAge||0)-dt);if(!s.grounded)s.jumpAge=(s.jumpAge||0)+dt;s.stairCooldown=Math.max(0,s.stairCooldown-dt);s.time+=dt;s.floorTime+=dt;s.invincible=Math.max(0,s.invincible-dt);s.cooldown=Math.max(0,s.cooldown-dt);s.flash=Math.max(0,s.flash-dt);s.noticeAge=Math.max(0,s.noticeAge-dt);
 tickClown(s,dt);
 if(s.stair||tryStairs(s,input)){const st=s.stair,a=STAIR_PATHS[st.index],dir=input.up?1:input.down?-1:((input.right?1:0)-(input.left?1:0))*a.dir;st.distance=Math.max(0,Math.min(a.length,st.distance+dir*108*dt));const previousX=s.x;Object.assign(s,stairPose(a,st.distance));s.vx=(s.x-previousX)/Math.max(dt,.001);s.vy=0;s.grounded=true;if(dir){s.walk+=dt*10;s.face=s.vx<0?'left':'right';}if(st.distance===a.length&&dir>0)enterLanding(s,a.to);else if(st.distance===0&&dir<0)enterLanding(s,a.from);return;}
 if(s.floor===2)tickSpiders(s,dt);tickAmbush(s,dt);
 if(input.flash&&s.cooldown===0){s.cooldown=4;s.flash=.35;if(s.floor===3)s.chaser=Math.min(970,s.chaser+100);}
 if(input.jump&&!s.jumpHeld)s.jumpBuffer=.13;else s.jumpBuffer=Math.max(0,s.jumpBuffer-dt);s.jumpHeld=!!input.jump;s.coyote=s.grounded?.1:Math.max(0,s.coyote-dt);if(s.jumpBuffer>0&&s.coyote>0){s.vy=-260;s.jumpAge=0;s.landingAge=0;s.grounded=false;s.coyote=0;s.jumpBuffer=0;}
 const direction=(input.right?1:0)-(input.left?1:0);s.vx=direction*132;const oldX=s.x,oldY=s.y,wasAirborne=!s.grounded;let nx=Math.max(47,Math.min(915,s.x+s.vx*dt));for(const o of activeSolids(s)){const top=FLOOR_Y[s.floor]-o.h;if(s.y>top+1&&s.y-33<FLOOR_Y[s.floor]&&nx+7>o.x&&nx-7<o.x+o.w){if(oldX+7<=o.x)nx=o.x-7;else if(oldX-7>=o.x+o.w)nx=o.x+o.w+7;}}s.x=nx;if(direction){s.face=direction>0?'right':'left';if(Math.abs(s.x-oldX)>.001)s.walk+=dt*12;}s.vy+=650*dt;s.y+=s.vy*dt;s.grounded=false;
 const surfaces=[];if(s.floor!==2||s.x<528||s.x>767)surfaces.push({x:40,w:885,y:FLOOR_Y[s.floor]});if(s.floor===2)surfaces.push(...platforms(s));for(const o of activeSolids(s))surfaces.push({x:o.x,w:o.w,y:FLOOR_Y[s.floor]-o.h});if(s.vy>=0)for(const p of surfaces){if(s.x+5>p.x&&s.x-5<p.x+p.w&&oldY<=p.y+4&&s.y>=p.y){s.y=p.y;s.vy=0;s.grounded=true;break;}}
 // Jumping onto a sloped flight lands on its treads instead of passing through it.
 if(s.vy>=0&&s.power&&s.fuses.includes(s.floor)){const index=s.floor,a=STAIR_PATHS[index];if(a){let distance=0;for(let i=0;i<a.lengths.length;i++){const p=a.points[i],q=a.points[i+1];if(p[0]!==q[0]&&s.x>=Math.min(p[0],q[0])&&s.x<=Math.max(p[0],q[0])){const t=(s.x-p[0])/(q[0]-p[0]),y=p[1]+(q[1]-p[1])*t;if(oldY<=y+3&&s.y>=y){s.y=y;s.vy=0;s.grounded=true;s.stair={index,distance:distance+a.lengths[i]*t};break;}}distance+=a.lengths[i];}}}
 if(wasAirborne&&s.grounded)s.landingAge=.12;
 const fuseX=[450,410,480][s.floor];if(fuseX&&!s.fuses.includes(s.floor)&&Math.abs(s.x-fuseX)<17&&Math.abs(s.y-FLOOR_Y[s.floor])<28){s.fuses.push(s.floor);s.notice='BRASS FUSE '+s.fuses.length+' / 3 · Follow the stairs.';s.noticeAge=3;}
 for(const h of hazards(s)){if(h.active&&(h.kind==='arrow'?arrowHits(h,s):Math.abs(s.x-h.x)<h.r+5&&s.y>h.y-h.r&&s.y-33<h.y+h.r)){if(h.source)h.source.spent=true;hit(s,h.kind==='arrow'?'ARROW · Move away from the marked aim point.':h.kind==='balloon-bomb'?'POP! · Retreat from a flashing balloon.':h.kind==='spider'?'SPIDER · Dodge its marked landing or jump past it.':'HIT · Keep moving. Jump the next obstacle.');}}
 if(s.y>FLOOR_Y[s.floor]+58){s.invincible=0;hit(s,'Missed the moving floor · back to the landing.',true);}
 if(s.floor===3){s.chaser-=dt*(s.flash>0?0:54);if(s.chaser-s.x<17)hit(s,'The shadow caught you · back to the landing.',true);}
}
