// Side-view coordinates; y is the actor's feet. Shared geometry drives drawing and collisions.
export const FLOOR_Y=[690,493,355,181];
export const START_X=[95,887,68,890];
export const STAIRS=[{x:866,to:1},{x:68,to:2},{x:890,to:3}];
export const SOLIDS=[{id:'crate',floor:0,x:493,w:36,h:30},{id:'gate',floor:0,x:657,w:17,h:58},{id:'motor',floor:1,x:620,w:38,h:25},{id:'exit-gate',floor:2,x:825,w:16,h:57},{id:'trunk',floor:3,x:550,w:38,h:27}];
export function newPlatform(floor=0){floor=Math.max(0,Math.min(3,floor));return {x:START_X[floor],y:FLOOR_Y[floor],vx:0,vy:0,floor,time:0,floorTime:0,walk:0,face:'right',light:true,grounded:true,coyote:.1,jumpBuffer:0,jumpHeld:false,health:3,invincible:1,checkpoint:floor,power:floor>0,fuses:Array.from({length:Math.min(floor,3)},(_,i)=>i),status:'playing',paused:false,stair:null,chaser:955,flash:0,cooldown:0,hits:0,notice:floor?'CHECKPOINT · SAFE LANDING':'Find the brass fuse. Start the machinery at the switch.',noticeAge:5};}
export function activeSolids(s){return SOLIDS.filter(o=>o.floor===s.floor&&!(o.id==='gate'&&s.power)&&!(o.id==='exit-gate'&&s.fuses.length===3));}
export function platforms(s){return [0,1,2].map(i=>({id:'lift-'+i,x:535+i*76,w:64,y:355-14*Math.sin(s.floorTime*1.6+i*1.4)}));}
export function hazards(s){const list=[];if(s.floor===1){const phase=s.floorTime%4.4;list.push({id:'barrel',kind:'barrel',x:phase<1.1?69:69+(phase-1.1)*246,y:493-14,r:14,active:phase>=1.1,warning:phase<1.1,until:Math.max(0,1.1-phase)});}if(s.floor===2){const p=Math.sin(s.floorTime*1.8);list.push({id:'pendulum',kind:'pendulum',x:427+p*57,y:281+Math.sqrt(Math.max(0,75*75-(p*57)**2)),r:12,active:true});}if(s.floor===3){const phase=s.floorTime%3.9;list.push({id:'press',kind:'press',x:350,y:phase<1.25?115:phase<1.65?115+(phase-1.25)/.4*57:phase<2.25?172:phase<2.8?172-(phase-2.25)/.55*57:115,r:19,active:phase>=1.25&&phase<2.8,warning:phase<1.25,until:Math.max(0,1.25-phase)});}return list;}
export function retryPlatform(s){const next=newPlatform(s.checkpoint);next.hits=s.hits;Object.assign(s,next);}
function hit(s,text,resetPosition=false){if(s.invincible>0)return;s.health--;s.hits++;s.invincible=1.6;s.notice=text;s.noticeAge=2.5;if(s.health<=0){s.status='caught';return;}if(resetPosition){s.x=START_X[s.floor];s.y=FLOOR_Y[s.floor];s.vy=0;s.grounded=true;s.chaser=955;}else{s.vy=-105;s.grounded=false;}}
export function platformAction(s){if(s.paused||s.status!=='playing'||s.stair)return;if(s.floor===0&&Math.abs(s.x-360)<44){s.power=true;s.notice='POWER RESTORED · The safety gates are open. Something heard that.';s.noticeAge=5;return;}if(s.floor===3&&Math.abs(s.x-145)<48){s.status='escaped';return;}const a=STAIRS[s.floor];if(a&&Math.abs(s.x-a.x)<43&&s.grounded){if(!s.power){s.notice='Restore power at the counter switch first.';s.noticeAge=3;return;}if(!s.fuses.includes(s.floor)){s.notice='Take the glowing brass fuse before going upstairs.';s.noticeAge=3;return;}s.stair={from:s.floor,to:a.to,x:s.x,y:s.y,t:0};}}
export function tickPlatform(s,input,dt){if(s.paused||s.status!=='playing')return;dt=Math.max(0,Math.min(.05,dt));s.time+=dt;s.floorTime+=dt;s.invincible=Math.max(0,s.invincible-dt);s.cooldown=Math.max(0,s.cooldown-dt);s.flash=Math.max(0,s.flash-dt);s.noticeAge=Math.max(0,s.noticeAge-dt);
 if(s.stair){const a=s.stair;a.t+=dt;const p=Math.min(1,a.t/1.15);s.x=a.x+(START_X[a.to]-a.x)*p;s.y=a.y+(FLOOR_Y[a.to]-a.y)*p;s.walk+=dt*10;if(p===1){s.floor=a.to;s.checkpoint=a.to;s.floorTime=0;s.stair=null;s.health=3;s.invincible=1.6;s.vy=0;s.grounded=true;s.chaser=955;s.notice=s.floor===3?'RUN LEFT · Flash the pursuer with F. Reach the EXIT.':'CHECKPOINT · FLOOR '+(s.floor+1);s.noticeAge=4;}return;}
 if(input.flash&&s.cooldown===0){s.cooldown=4;s.flash=.35;if(s.floor===3)s.chaser=Math.min(970,s.chaser+100);}
 if(input.jump&&!s.jumpHeld)s.jumpBuffer=.13;else s.jumpBuffer=Math.max(0,s.jumpBuffer-dt);s.jumpHeld=!!input.jump;s.coyote=s.grounded?.1:Math.max(0,s.coyote-dt);if(s.jumpBuffer>0&&s.coyote>0){s.vy=-260;s.grounded=false;s.coyote=0;s.jumpBuffer=0;}
 const direction=(input.right?1:0)-(input.left?1:0);s.vx=direction*132;const oldX=s.x,oldY=s.y;let nx=Math.max(47,Math.min(915,s.x+s.vx*dt));for(const o of activeSolids(s)){const top=FLOOR_Y[s.floor]-o.h;if(s.y>top+1&&s.y-33<FLOOR_Y[s.floor]&&nx+7>o.x&&nx-7<o.x+o.w){if(oldX+7<=o.x)nx=o.x-7;else if(oldX-7>=o.x+o.w)nx=o.x+o.w+7;}}s.x=nx;if(direction){s.face=direction>0?'right':'left';s.walk+=dt*12;}s.vy+=650*dt;s.y+=s.vy*dt;s.grounded=false;
 const surfaces=[];if(s.floor!==2||s.x<528||s.x>767)surfaces.push({x:40,w:885,y:FLOOR_Y[s.floor]});if(s.floor===2)surfaces.push(...platforms(s));for(const o of activeSolids(s))surfaces.push({x:o.x,w:o.w,y:FLOOR_Y[s.floor]-o.h});if(s.vy>=0)for(const p of surfaces){if(s.x+5>p.x&&s.x-5<p.x+p.w&&oldY<=p.y+4&&s.y>=p.y){s.y=p.y;s.vy=0;s.grounded=true;break;}}
 const fuseX=[450,410,480][s.floor];if(fuseX&&!s.fuses.includes(s.floor)&&Math.abs(s.x-fuseX)<17&&Math.abs(s.y-FLOOR_Y[s.floor])<28){s.fuses.push(s.floor);s.notice='BRASS FUSE '+s.fuses.length+' / 3 · Follow the stairs.';s.noticeAge=3;}
 for(const h of hazards(s)){if(h.active&&Math.abs(s.x-h.x)<h.r+5&&s.y>h.y-h.r&&s.y-33<h.y+h.r)hit(s,'HIT · Keep moving. Jump the next obstacle.');}
 if(s.y>FLOOR_Y[s.floor]+58){s.invincible=0;hit(s,'Missed the moving floor · back to the landing.',true);}
 if(s.floor===3){s.chaser-=dt*(s.flash>0?0:54);if(s.chaser-s.x<17)hit(s,'The shadow caught you · back to the landing.',true);}
}
