// Original four-direction idle art plus four authored walking poses per direction.
import {PLAYER_HEIGHT,playerPose} from './player-animation.js';
export {PLAYER_HEIGHT,playerPose};
const directions={down:0,left:1,up:2,right:3};
const idle=new Image(),walking=new Image(),jumping=new Image(),idleFrames=[],walkFrames=[],jumpFrames=[];
function scan(image,xs,ys){const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data,rows=[];
 for(let row=0;row<ys.length-1;row++){const frames=[];for(let col=0;col<xs.length-1;col++){let x0=xs[col+1],y0=ys[row+1],x1=xs[col],y1=ys[row];for(let y=ys[row];y<ys[row+1];y++)for(let x=xs[col];x<xs[col+1];x++)if(data[(y*c.width+x)*4+3]>90){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}frames.push({x:x0,y:y0,w:x1-x0+1,h:y1-y0+1});}const height=Math.max(...frames.map(f=>f.h));rows.push(frames.map(f=>({...f,scaleHeight:height})));}return rows;}
idle.onload=()=>idleFrames.push(...scan(idle,Array.from({length:5},(_,i)=>Math.floor(i*idle.width/4)),[0,idle.height])[0]);
idle.src=new URL('../assets/characters/investigator-v2.png',import.meta.url).href;
walking.onload=()=>walkFrames.push(...scan(walking,Array.from({length:5},(_,i)=>Math.floor(i*walking.width/4)),Array.from({length:5},(_,i)=>Math.floor(i*walking.height/4))));
walking.src=new URL('../assets/characters/investigator-walk-v2.png',import.meta.url).href;
jumping.onload=()=>jumpFrames.push(...scan(jumping,Array.from({length:5},(_,i)=>Math.floor(i*jumping.width/4)),[0,Math.floor(jumping.height/2),jumping.height]));
export function preloadJumpSprites(){if(!jumping.src)jumping.src=new URL('../assets/characters/investigator-jump-v1.png',import.meta.url).href;}
function sprite(ctx,s,moving){if(idleFrames.length!==4)return false;const pose=playerPose(s,moving);let source=idle,f=idleFrames[directions[s.face]??0];if(pose.kind==='walk'&&walkFrames.length===4){source=walking;f=walkFrames[pose.row][pose.frame];}if(pose.kind==='jump')preloadJumpSprites();if(pose.kind==='jump'&&jumpFrames.length===2){source=jumping;f=jumpFrames[pose.row][pose.frame];}const scale=(s.spriteHeight||PLAYER_HEIGHT)/f.scaleHeight,w=f.w*scale,h=f.h*scale;ctx.imageSmoothingEnabled=false;if(s.grounded!==false)ellipse(ctx,s.x,s.y+1,8,2.5,'#09080b99');ctx.drawImage(source,f.x,f.y,f.w,f.h,Math.round(s.x-w/2),Math.round(s.y-h),w,h);return true;}
function rect(ctx,x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}
function ellipse(ctx,x,y,rx,ry,c){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
export function drawPlayer(ctx,s,moving){if(sprite(ctx,s,moving))return;const x=Math.round(s.x),y=Math.round(s.y),bob=moving?Math.sin(s.walk)*.7:0,feet=moving?Math.sin(s.walk)*2:0;ellipse(ctx,x,y+1,8,3,'#09080bb0');rect(ctx,x-5,y-7,4,7+feet,'#242e37');rect(ctx,x+1,y-7,4,7-feet,'#293641');rect(ctx,x-6,y-13+bob,12,9,'#372429');rect(ctx,x-5,y-14+bob,10,8,'#775b40');rect(ctx,x-5,y-14+bob,2,7,'#a27b51');rect(ctx,x-4,y-23+bob,9,9,'#372524');rect(ctx,x-3,y-22+bob,7,7,s.face==='up'?'#42312b':'#c5976a');rect(ctx,x-5,y-23+bob,10,4,'#302326');rect(ctx,x-6,y-21+bob,3,5,'#302326');if(s.face!=='up'){rect(ctx,x+(s.face==='left'?-3:2),y-19+bob,1,2,'#171a21');rect(ctx,x,y-15+bob,4,1,'#8e573f');}const dir=s.face==='left'?-1:1;rect(ctx,x+dir*6-2,y-12+bob,4,5,'#8a6846');rect(ctx,x+dir*8-2,y-10+bob,5,3,'#252a2e');rect(ctx,x+dir*10,y-10+bob,2,3,s.light?'#f8dea2':'#74634e');}
