import * as THREE from 'three';
import {ASSET} from '../assetlib.js';
const faces=['duck','cat','clown','sun','moon','rabbit','owl','pig','fish','jester','tragedy','ringmaster'],doors=['grin','wink','frown','exit'];
const descriptions={duck:'A cracked yellow shell, one missing eye, purple socket rims and a projecting bill.',cat:'A turquoise cat with pointed ears, a closed wink, hollow socket, whiskers and broken paint.',clown:'A grinning showman: bulbous nose, recessed mouth, individual teeth, cheek disks and a pleated ruff.',sun:'An ochre sun with an uneven ring of sculpted rays and a small, tight grin.',moon:'A crescent silhouette with a long profile, empty eye and descending tear.',rabbit:'A pale rabbit with one broken folded ear, mismatched eyes and two long front teeth.',owl:'A carved owl with deep circular sockets, heavy brows and layered feather ridges.',pig:'A rose-colored pig with folded ears, a protruding snout and missing teeth.',fish:'A green fish with mismatched sockets, an open round mouth, fin and gill ridges.',jester:'A two-horned jester, curled hat, brass bells, lopsided stare and protruding tongue.',tragedy:'A long, narrow mourning mask with hollow eyes, tears and a raised downturned lip.',ringmaster:'A top-hatted ringmaster with a curled moustache, recessed eyes and battered brim.',grin:'A rounded show door with an arched bulb marquee, brass pulls and red framing.',wink:'A crooked optical-illusion door with nested contrasting frames and a side latch.',frown:'A pointed industrial door with corrugated panels, cross-braces and three levers.',exit:'A narrow service door with a ventilator, heavy hinges and three red mechanical release handles.'};
const stage=document.querySelector('#stage'),renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(stage.clientWidth,stage.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;stage.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#202524');const camera=new THREE.PerspectiveCamera(37,stage.clientWidth/stage.clientHeight,.01,50);const key=new THREE.DirectionalLight(0xffedd1,3);key.position.set(-2,3,4);scene.add(key);const fill=new THREE.DirectionalLight(0x94cfdb,1.6);fill.position.set(3,1,2);scene.add(fill);scene.add(new THREE.HemisphereLight(0xc3cbd0,0x262821,1.0));
let object,mode='faces',request=0,drag=false,lastX=0,lastY=0,ambient=false;
async function show(name){const own=++request;const o=await ASSET(`../assets/art/${mode==='faces'?'face':'door'}_${name}.js`,{height:2.1,surfaces:true});if(own!==request)return;if(object)scene.remove(object);object=o;object.rotation.y=.10;scene.add(o);camera.position.set(0,1.13,mode==='faces'?4.8:5.6);camera.lookAt(0,1.05,0);document.querySelector('#caption').textContent=name.toUpperCase();document.querySelector('#info').textContent=descriptions[name];window.__ART__={name,mode};}
function menu(next){mode=next;document.querySelector('#pick').replaceChildren(...(mode==='faces'?faces:doors).map(n=>{const o=document.createElement('option');o.value=n;o.textContent=n.toUpperCase();return o;}));document.querySelector('#faces').classList.toggle('active',mode==='faces');document.querySelector('#doors').classList.toggle('active',mode==='doors');show(document.querySelector('#pick').value);}
document.querySelector('#pick').onchange=e=>show(e.target.value);document.querySelector('#faces').onclick=()=>menu('faces');document.querySelector('#doors').onclick=()=>menu('doors');document.querySelector('#reset').onclick=()=>{object.rotation.set(0,0,0);};document.querySelector('#light').onclick=e=>{ambient=!ambient;key.color.setHex(ambient?0xffaf66:0xffedd1);key.intensity=ambient?1.8:3;fill.intensity=ambient?.35:1.6;scene.background.set(ambient?'#101715':'#202524');e.target.textContent=ambient?'LIGHT: FUNHOUSE':'LIGHT: NEUTRAL';};
renderer.domElement.onpointerdown=e=>{drag=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointerup=()=>drag=false;renderer.domElement.onpointermove=e=>{if(drag&&object){object.rotation.y+=(e.clientX-lastX)*.01;object.rotation.x=Math.max(-.3,Math.min(.3,object.rotation.x+(e.clientY-lastY)*.003));lastX=e.clientX;lastY=e.clientY;}};renderer.domElement.style.touchAction='none';
window.addEventListener('resize',()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();});renderer.setAnimationLoop(()=>renderer.render(scene,camera));menu('faces');
