import * as THREE from 'three';
import {ASSET} from '../assetlib.js';
const faces=["grinner", "watcher", "hollow", "widow", "usher", "sleeper", "penitent", "drowned", "mourner", "harlequin", "contortionist", "ringmaster"],doors=['grin','wink','frown','exit'];
const descriptions={"grinner": "A gaunt human cast with an uneven fixed smile, individual teeth and misaligned glass eyes.", "watcher": "Heavy orbital ridges and alert, mismatched eyes above a tightly closed mouth.", "hollow": "Sunken cheeks, an empty eye socket and a slack mouth with missing teeth.", "widow": "A narrow, pale face with fine lips, recessed eyes and a quiet downturned expression.", "usher": "A broad, weathered face with a crooked nose, heavy brow and compressed lips.", "sleeper": "Drooping eyelids, one closed eye and a slack, slightly open mouth.", "penitent": "A long face with furrowed brows, deep folds and a downturned mouth.", "drowned": "A swollen, grey-green human cast with an empty eye and parted lips.", "mourner": "An aged face with pinched brows, a closed eye and fine forehead creases.", "harlequin": "A human performer\u2019s face with faded makeup and a violently lopsided smile.", "contortionist": "An asymmetric face with a shifted jaw, crooked bridge and uneven eye line.", "ringmaster": "A broad older face with prominent nasal cartilage, heavy brows and an uncomfortable grin.", "grin": "An arched show door with brass pulls and a bulb marquee.", "wink": "A crooked optical-illusion door with nested contrasting frames.", "frown": "A pointed industrial door with cross-braces and release levers.", "exit": "A ventilated service door with heavy hinges and three red handles."};
const stage=document.querySelector('#stage'),renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(stage.clientWidth,stage.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;stage.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#202524');const camera=new THREE.PerspectiveCamera(37,stage.clientWidth/stage.clientHeight,.01,50);const key=new THREE.DirectionalLight(0xffedd1,3);key.position.set(-2,3,4);scene.add(key);const fill=new THREE.DirectionalLight(0x94cfdb,1.6);fill.position.set(3,1,2);scene.add(fill);scene.add(new THREE.HemisphereLight(0xc3cbd0,0x262821,1.0));
let object,mode='faces',request=0,drag=false,lastX=0,lastY=0,ambient=false;
async function show(name){const own=++request;const o=await ASSET(`../assets/${mode==='faces'?'humanoid':'art'}/${mode==='faces'?'face':'door'}_${name}.js`,{height:2.1,surfaces:true});if(own!==request)return;if(object)scene.remove(object);object=o;object.rotation.y=.10;scene.add(o);camera.position.set(0,1.13,mode==='faces'?4.8:5.6);camera.lookAt(0,1.05,0);document.querySelector('#caption').textContent=name.toUpperCase();document.querySelector('#info').textContent=descriptions[name];window.__ART__={name,mode};}
function menu(next){mode=next;document.querySelector('#pick').replaceChildren(...(mode==='faces'?faces:doors).map(n=>{const o=document.createElement('option');o.value=n;o.textContent=n.toUpperCase();return o;}));document.querySelector('#faces').classList.toggle('active',mode==='faces');document.querySelector('#doors').classList.toggle('active',mode==='doors');show(document.querySelector('#pick').value);}
document.querySelector('#pick').onchange=e=>show(e.target.value);document.querySelector('#faces').onclick=()=>menu('faces');document.querySelector('#doors').onclick=()=>menu('doors');document.querySelector('#reset').onclick=()=>{object.rotation.set(0,0,0);};document.querySelector('#light').onclick=e=>{ambient=!ambient;key.color.setHex(ambient?0xffaf66:0xffedd1);key.intensity=ambient?1.8:3;fill.intensity=ambient?.35:1.6;scene.background.set(ambient?'#101715':'#202524');e.target.textContent=ambient?'LIGHT: FUNHOUSE':'LIGHT: NEUTRAL';};
renderer.domElement.onpointerdown=e=>{drag=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointerup=()=>drag=false;renderer.domElement.onpointermove=e=>{if(drag&&object){object.rotation.y+=(e.clientX-lastX)*.01;object.rotation.x=Math.max(-.3,Math.min(.3,object.rotation.x+(e.clientY-lastY)*.003));lastX=e.clientX;lastY=e.clientY;}};renderer.domElement.style.touchAction='none';
window.addEventListener('resize',()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();});renderer.setAnimationLoop(()=>renderer.render(scene,camera));menu('faces');
