export const ROUTE=[{id:'forecourt',x:0,z:-24,w:24,d:16},{id:'dark-corridor',x:0,z:-7.5,w:3.4,d:17},{id:'barrel',x:0,z:3,w:3.4,d:6},{id:'stairs',x:0,z:8,w:3.4,d:4},{id:'moving-floor',x:3.5,z:10,w:10.4,d:3.4},{id:'gallery',x:7,z:5,w:3.4,d:10},{id:'return',x:3.5,z:0,w:10.4,d:3.4}];
export function newEntrance(){return {age:0,turnstile:false,flashlight:false,power:false,upper:false,door:false,foulDoor:false,foulAge:-1,scareAge:-1,disturbance:false,fallAge:-1,done:false,barrelHits:0,hitCooldown:0};}
export function barrelState(t){return {x:Math.sin(t*.92)*1.12,z:3.15+Math.cos(t*.64)*.42,r:.51};}
export function movingFloor(i,t){return {height:Math.sin(t*1.3+i*1.7)*.14,tilt:Math.sin(t*.87+i)*.035};}
export function entranceHeight(s,x,z){if(s.fallAge>=0)return Math.max(0,9-4.9*s.fallAge*s.fallAge);if(!s.upper)return 6+Math.max(0,Math.min(1,(z-6)/3.5))*3;if(z>8.3){const i=Math.max(0,Math.min(4,Math.floor((x+.7)/1.65)));return 9+movingFloor(i,s.age).height+(x-i*1.65)*movingFloor(i,s.age).tilt;}return 9;}
export function entranceWalkable(s,x,z,r=.25){const regions=s.upper?ROUTE.slice(4):[...ROUTE.slice(0,5),...(s.foulDoor?[{x:-3.8,z:-8,w:5.9,d:2.5}]:[])];const inside=(xx,zz)=>regions.some(b=>Math.abs(xx-b.x)<=b.w/2&&Math.abs(zz-b.z)<=b.d/2);if(![[0,0],[r,0],[-r,0],[0,r],[0,-r]].every(([dx,dz])=>inside(x+dx,z+dz)))return false;if(!s.turnstile&&z> -16.4&&z< -15.5)return false;if(!s.power&&z>-.6&&!s.upper)return false;if(!s.upper&&z>6&&z<9.45&&x>1.4)return false;if(s.upper&&!s.door&&Math.abs(z-6.15)<.3&&x>5.3)return false;return true;}
export function stepEntrance(s,dt,p){s.age+=dt;if(s.foulAge>=0)s.foulAge+=dt;s.hitCooldown=Math.max(0,s.hitCooldown-dt);const events=[];if(s.upper&&p.x<1.4&&p.z>6&&p.z<9.45)s.upper=false;if(!s.upper&&p.z>9.45){s.upper=true;events.push('upper');}if(s.scareAge>=0)s.scareAge+=dt;if(s.upper&&s.door&&p.x>5.4&&p.z<3&&!s.disturbance){s.disturbance=true;events.push('run');}if(s.disturbance&&p.x<1&&p.z<1.1&&s.fallAge<0){s.fallAge=0;events.push('fall');}if(s.fallAge>=0){s.fallAge+=dt;if(s.fallAge>1.5){s.done=true;events.push('maze');}}
 const b=barrelState(s.age);if(!s.upper&&s.power&&s.hitCooldown===0&&Math.hypot(p.x-b.x,p.z-b.z)<b.r+.25){s.barrelHits++;s.hitCooldown=1.7;p.z=Math.max(1,p.z-.8);events.push('barrel');}return events;}
export function entranceSnapshot(s,p){return {...s,height:entranceHeight(s,p.x,p.z),barrel:barrelState(s.age),floors:Array.from({length:5},(_,i)=>movingFloor(i,s.age))};}
