import * as THREE from 'three';
import {buildWorld,label} from './world.js';
import {buildCartRide} from './cart-ride.js';
import {newRide,stepRide,rideSnapshot,RIDE_LENGTH} from './ride-model.js';
import {CreatureMind} from './creature-mind.js';
import {Suspense} from './suspense.js';
import {Soundscape} from './audio.js';
import {SIZE,N,key,edgeKey,GATES,EVIDENCE,INITIAL_GATES,POWER_GATES,ESCAPE_SECONDS,EXIT_ORDER,RELEASE_ORDER,pathfind,cellAt,point} from './model.js';
const $=id=>document.getElementById(id),show=(id,on=true)=>$(id).classList.toggle('hidden',!on);
const touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
const renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,touch?1.25:1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.14;renderer.info.autoReset=false;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x101b1a);scene.fog=new THREE.FogExp2(0x101b1a,.048);scene.add(new THREE.HemisphereLight(0x7eaaa1,0x201c19,.28));
const camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.055,65);camera.rotation.order='YXZ';scene.add(camera);
const torch=new THREE.SpotLight(0xffdfa9,48,16,Math.PI/5,.70,1.5);torch.position.set(.13,-.14,-.1);camera.add(torch);torch.castShadow=true;torch.shadow.mapSize.set(touch?512:1024,touch?512:1024);torch.shadow.bias=-.0005;torch.shadow.normalBias=.025;torch.shadow.camera.near=.1;torch.shadow.camera.far=16;const target=new THREE.Object3D();target.position.set(0,-.12,-9);camera.add(target);torch.target=target;
const sound=new Soundscape(),suspense=new Suspense(),mind=new CreatureMind();let nextFootNoise=0,mindRevision=-1;let glimpsePosition=null;
const mazeRoot=new THREE.Group();scene.add(mazeRoot);let park,ride=null;
let world,phase='menu',paused=false,dialog=null,found=new Set(),gates=[...INITIAL_GATES],rotations=[0,0,0],power=false,recording=false,jamSolved=false,timeLeft=ESCAPE_SECONDS,elapsed=0,grace=8,stamina=1,noise=0,subtitleTime=0,checkpoint=null;
let yaw=Math.PI,pitch=0,player={x:0,z:-.90},near=null,started=false,ending=false,moved=0,screenTime=0;
let monster={x:0,z:0,route:[],target:null},release=[0,0,0],releaseLeft=15,exitProgress=0,powerProgress=0;
const keys=new Set(),stick={x:0,y:0},input={drag:false,lookId:null,lastX:0,lastY:0,stickId:null,cx:0,cy:0,run:false};
const raycaster=new THREE.Raycaster();
const isActive=()=>started&&!paused&&!ending;
function say(text,seconds=6){$('subtitle').textContent=text;subtitleTime=seconds;}
function updateObjective(){let title='01 / INVESTIGATE',s='Find what the children left behind.';
 if(found.size===3){s='Set the three walls. Restore power in maintenance.';title='02 / DISCOVER';}
 if(power){s='Play the recovered cassette in maintenance.';title='02 / DISCOVER';}
 if(recording)s='The broken telephone is ringing.';
 if(phase==='chase'){title='03 / ESCAPE';s=jamSolved?'Reach the service exit. Turn walls behind you.':'The passage has jammed. Find its release.';}
 $('chapter').textContent=title;$('objective').textContent=s;$('evidence').textContent=EVIDENCE.map(e=>found.has(e.id)?e.symbol:'○').join('  ');$('evidence-count').textContent=found.size+' / '+EVIDENCE.length;Object.entries(world.evidenceMeshes).forEach(([id,mesh])=>mesh.visible=!found.has(id));show('clock',phase==='chase');}
function lock(){if(!touch&&isActive()&&!dialog)renderer.domElement.requestPointerLock?.().catch?.(()=>{});}
function clearInput(){keys.clear();stick.x=stick.y=0;input.run=false;input.brake=false;input.lookBack=false;input.drag=false;input.stickId=null;input.lookId=null;}
function releasePointer(){document.exitPointerLock?.();clearInput();}
function hideDialog(){show('dialog',false);dialog=null;clearInput();lock();}
function openDialog(type,labelText,title,body,buttons=[]){sound.stop('suspense');dialog=type;releasePointer();$('dialog-label').textContent=labelText;$('dialog-title').textContent=title;$('dialog-body').innerHTML=body;$('dialog-actions').replaceChildren();for(const [text,fn] of buttons){const b=document.createElement('button');b.className='primary';b.textContent=text;b.onclick=fn;$('dialog-actions').append(b);}show('dialog');}
function pause(){if(!started||ending)return;paused=true;clearInput();releasePointer();show('pause');sound.pause?.();}
function resume(){paused=false;show('pause',false);sound.start();lock();}
function mazeMode(){mazeRoot.visible=true;if(park)park.root.visible=false;if(world.creature.parent!==mazeRoot)mazeRoot.add(world.creature);scene.background.set(0x101b1a);scene.fog.density=.048;scene.fog.color.set(0x101b1a);camera.far=65;camera.updateProjectionMatrix();document.body.classList.remove('cart-ride');$('run').textContent='RUN';$('notes').textContent='NOTES';$('stick').querySelector('span').textContent='MOVE';$('clock').querySelector('span').textContent='EMERGENCY SHUTDOWN';$('resume').textContent='RETURN TO THE MAZE ↗';$('pause').querySelector('p').textContent='Move with WASD. Look with the mouse. E interacts, Shift runs and J opens notes.';}
function reset(){mind.reset();nextFootNoise=0;mindRevision=-1;suspense.reset();world.setSuspense(null);glimpsePosition=null;mazeMode();ride=null;found=new Set();gates=[...INITIAL_GATES];rotations=[0,0,0];power=recording=jamSolved=false;timeLeft=ESCAPE_SECONDS;elapsed=0;grace=8;stamina=1;noise=0;phase='investigate';ending=false;paused=false;player={x:0,z:-.90};yaw=Math.PI;pitch=0;monster={x:0,z:0,route:[],target:null};checkpoint=null;dialog=null;show('ending',false);show('dialog',false);show('pause',false);world.jam.visible=false;world.creature.visible=false;world.resetCreature();world.shutter.visible=false;world.setLighting(false);sound.resetAtmosphere();sound.stop('recording');sound.stop('phoneVoice');document.body.classList.remove('chase');updateObjective();}
function begin(){sound.start();reset();started=true;show('menu',false);show('hud');show('touch',touch);lock();say('October 17, 1987. Three children were last seen here. Find what they left behind.',9);}
function finish(won){const wasRide=phase==='ride';sound.stop('monsterLaugh');sound.stop('monsterGrunt');sound.stop('monsterBreath');sound.stop('suspense');sound.stop('laughter');sound.stop('recording');sound.stop('phoneVoice');ending=true;phase=won?'escaped':'caught';releasePointer();show('dialog',false);dialog=null;show('hud',false);show('touch',false);show('ending');$('end-label').textContent=won?'CASE 087 / EVIDENCE RECOVERED':'CASE 087 / SIGNAL LOST';$('end-title').textContent=won?'You made it outside.':'The laughter stops.';$('end-copy').textContent=won?'Cold sea air. The tape is still in your hand. As its last few seconds play, a child whispers: “There’s another door.” You have proof. You don’t have answers.':timeLeft<=0?'The emergency lights went out before you reached the service exit. Your investigation is saved.':'A shape unfolded from the dark. Your investigation is saved. Remember: turn a wall to force it onto another route.';$('retry').textContent='START A NEW INVESTIGATION ↗';if(wasRide){$('end-copy').textContent=won?'The cart bursts through the park gate. The red moon hangs over an empty coast road. You still have the children’s belongings and the tape. Behind the fog, the laughter fades.':'The cart slowed. The thing unfolded across the rails and caught you. Your park checkpoint is saved. Switch tracks before the reflectors; boost when it gets close.';} $('checkpoint').textContent=checkpoint?.stage==='ride'?'RETRY THE CART RIDE':'RETRY FROM THE PHONE';show('checkpoint',!won&&!!checkpoint);sound.tone(won?220:48,2,.15,'sine',won?330:22);}
function startChase(){mind.reset();nextFootNoise=0;mindRevision=-1;suspense.reset();world.setSuspense(null);checkpoint={gates:[...gates],x:player.x,z:player.z,yaw,pitch};phase='chase';sound.resetAtmosphere();jamSolved=false;timeLeft=ESCAPE_SECONDS;grace=8;stamina=1;elapsed=0;monster={x:0,z:0,route:[],target:null};release=[0,0,0];releaseLeft=15;exitProgress=0;world.jam.visible=true;world.creature.visible=false;world.resetCreature();world.shutter.visible=true;world.shutter.position.y=4.8;world.setLighting(true);document.body.classList.add('chase');hideDialog();updateObjective();sound.knock();sound.play?.('phoneVoice');mind.hear(monster,player,gates,100,'telephone');say('“You switched the lights on. Now it knows where you are.”',8);}
function retryCheckpoint(){if(checkpoint?.stage==='ride'){startRide(checkpoint.progress);return;}const saved=checkpoint;found=new Set(EVIDENCE.map(e=>e.id));power=recording=true;gates=[...saved.gates];rotations=[0,0,0];player={x:saved.x,z:saved.z};yaw=saved.yaw;pitch=saved.pitch;ending=false;paused=false;show('ending',false);show('hud');show('touch',touch);startChase();sound.start();lock();}
function startRide(progress=0){
 suspense.reset();world.setSuspense(null);
 if(!park)park=buildCartRide(scene);park.root.visible=true;mazeRoot.visible=false;park.root.add(world.creature);world.creature.visible=true;world.resetCreature();
 sound.start();sound.resetAtmosphere();sound.stop('recording');sound.stop('phoneVoice');phase='ride';ending=false;paused=false;started=true;elapsed=0;timeLeft=110;ride=newRide(progress);checkpoint={stage:'ride',progress};
 scene.background.set(0x192221);scene.fog.color.set(0x26312f);scene.fog.density=.037;camera.far=650;camera.fov=70;camera.updateProjectionMatrix();
 document.body.classList.add('chase','cart-ride');show('menu',false);show('ending',false);show('pause',false);show('hud');show('touch',touch);hideDialog();show('interact',false);show('click-look',false);$('use').disabled=false;$('use').textContent='BRAKE';$('run').textContent='BOOST';$('notes').textContent='LOOK BACK';$('stick').querySelector('span').textContent='STEER';$('chapter').textContent='04 / THE LAST RIDE';$('clock').querySelector('span').textContent='DISTANCE TO EXIT';show('clock');$('resume').textContent='RETURN TO THE CART ↗';$('pause').querySelector('p').textContent='The cart moves automatically. A/D or the joystick steers. Shift/BOOST gives a short burst. S/BRAKE slows down. E/LOOK BACK checks the creature.';
 $('evidence-count').textContent=found.size+' / 3';say('The service door leads to the old park railway. Steer around the wreckage. It runs faster out here.',8);park.update(ride,0,camera,world.creature);lock();
}
function updateRide(dt,raw){
 elapsed+=dt;timeLeft-=raw;subtitleTime-=dt;if(subtitleTime<=0)$('subtitle').textContent='';
 const steer=Math.max(-1,Math.min(1,(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stick.x));
 const hits=ride.hits,old=ride.progress;stepRide(ride,dt,{steer,boost:input.run||keys.has('ShiftLeft')||keys.has('ShiftRight'),brake:input.brake||keys.has('KeyS')||keys.has('ArrowDown')||stick.y>.55});moved=ride.progress-old;
 if(ride.hits>hits){sound.knock();say('Wreckage! The cart is slowing—switch tracks and boost.',2.5);}
 park.update(ride,elapsed,camera,world.creature,input.lookBack||keys.has('KeyE'));player.x=camera.position.x;player.z=camera.position.z;monster.x=world.creature.position.x;monster.z=world.creature.position.z;
 sound.monster(elapsed,true,ride.gap,0,false);world.updateCreature(elapsed*1.65,dt,{distance:ride.gap,clear:true,laughing:sound.sources.has('monsterLaugh'),grunting:sound.sources.has('monsterGrunt')});sound.cart(elapsed,ride.speed);sound.update(elapsed,false,false,true,ride.gap,false);
 const near=rideSnapshot(ride).next;$('objective').textContent=near&&near.distance<24?'Wreckage ahead — switch to a clear track.':'Stay on the rails. Reach the coast road.';$('time').textContent=Math.ceil(RIDE_LENGTH-ride.progress)+' m';$('danger').textContent='IT IS '+Math.max(0,Math.round(ride.gap))+' m BEHIND';show('danger',true);$('stamina').firstElementChild.style.width=ride.energy*100+'%';show('click-look',false);
 if(ride.status==='escaped')finish(true);else if(ride.status==='caught'||timeLeft<=0)finish(false);
}
function jumpCheckpoint(which){begin();found=new Set(EVIDENCE.map(e=>e.id));power=recording=true;gates=[...POWER_GATES];gates.forEach((v,i)=>world.gateMeshes[i].rotation.y=v?-Math.PI/2:0);updateObjective();if(which==='chase'){player={x:16.8,z:16.8};yaw=0;pitch=0;startChase();}else startRide(which==='final'?300:0);}
document.querySelectorAll('[data-test-checkpoint]').forEach(b=>b.onclick=()=>jumpCheckpoint(b.dataset.testCheckpoint));
function gateBoxes(states=gates){return GATES.map((g,i)=>states[i]?{x:(g.x+.5)*SIZE,z:g.z*SIZE,w:.23,d:SIZE}:{x:g.x*SIZE,z:(g.z+.5)*SIZE,w:SIZE,d:.23});}
function collides(x,z,r=.25,states=gates){if(GATES.some((g,i)=>{if(rotations[i]<=0)return false;const px=(g.x+.5)*SIZE,pz=(g.z+.5)*SIZE;return x>px-SIZE-r&&x<px+r&&z>pz-SIZE-r&&z<pz+r&&Math.hypot(x-px,z-pz)<SIZE+r;}))return true;const a=[...world.collision,...gateBoxes(states)];if(world.jam.visible)a.push({x:4*SIZE,z:3.5*SIZE,w:SIZE,d:.14});return a.some(b=>Math.abs(x-b.x)<b.w/2+r&&Math.abs(z-b.z)<b.d/2+r);}
function turnGate(i){if(rotations[i]>0)return;const proposed=[...gates];proposed[i]=1-proposed[i];const wall=gateBoxes(proposed)[i];const intersects=p=>Math.abs(p.x-wall.x)<wall.w/2+.35&&Math.abs(p.z-wall.z)<wall.d/2+.35;const gp=world.gateMeshes[i].position;const inSweep=p=>p.x>gp.x-SIZE-.3&&p.x<gp.x+.3&&p.z>gp.z-SIZE-.3&&p.z<gp.z+.3&&Math.hypot(p.x-gp.x,p.z-gp.z)<SIZE+.3;
 if(intersects(player)||inSweep(player)||(phase==='chase'&&grace<=0&&(intersects(monster)||inSweep(monster)))){say('Stand back beside the handle; keep the wall’s sweep clear.',3);return;}
 // Control stands are safely northwest of the quarter-circle swept by the panel.
 gates=proposed;rotations[i]=1;monster.route=[];monster.target=null;sound.grind();noise=2.5;if(phase==='chase')mind.hear(monster,point(GATES[i].a),gates,22,'wall-mechanism');say(`${GATES[i].name}: ${gates[i]?'south':'east'} passage open.`,3);}
function journal(){if(phase==='ride'){input.lookBack=!input.lookBack;return;}const rows=EVIDENCE.map(e=>`<p class="notes">${found.has(e.id)?`<b>${e.symbol} ${e.title}</b><br>${e.note}`:'○ Unrecovered belonging'}</p>`).join('');openDialog('notes','FIELD NOTES / CASE 087','What you know',`<p>Three children entered this attraction. None came home. Their belongings may show where they went.</p>${rows}<p class="notes"><b>Wall controls:</b> each turn opens one passage and closes another. Painted compass marks show north and south. Maintenance is in the southeast. The service exit is southwest.</p>${recording?'<p class="clue">Exit handles: LEFT → RIGHT → MIDDLE</p>':''}${phase==='chase'?'<small>The creature and shutdown timer are still moving while you read. Running and wall mechanisms carry sound through corridors; break its line of sight, then move quietly.</small>':''}`);}
function drawPower(){const all=found.size===3,ready=gates.every((v,i)=>v===POWER_GATES[i]);openDialog('power','MAINTENANCE / POWER DISTRIBUTION','Restore the circuit',`<p>The wall mechanisms feed this circuit. Set all three routes using the maintenance scraps, then engage the breakers in the order printed below.</p><p class="notes">${GATES.map((g,i)=>`${g.name}: ${gates[i]===POWER_GATES[i]?'● CONNECTED':'○ MISALIGNED'}`).join('<br>')}</p><p class="clue">RED → AMBER → BLUE</p><div class="switches">${['RED','AMBER','BLUE'].map((n,i)=>`<button data-breaker="${i}">${n}</button>`).join('')}</div><p class="puzzle-status" id="pstatus">${!all?'Recover all three belongings first.':!ready?'Wall circuits misaligned. Check your field notes.':'Circuit ready. Engage the breakers.'}</p>`);powerProgress=0;document.querySelectorAll('[data-breaker]').forEach(b=>b.onclick=()=>{if(!all||!ready){sound.tick();return;}const n=+b.dataset.breaker;if(n===powerProgress){b.classList.add('active');powerProgress++;sound.tick();if(powerProgress===3){power=true;hideDialog();updateObjective();sound.tone(120,1,.15,'triangle',160);say('Power restored. The cassette player is working.',5);}}else{powerProgress=0;document.querySelectorAll('[data-breaker]').forEach(e=>e.classList.remove('active'));$('pstatus').textContent='Breaker sequence reset. RED → AMBER → BLUE.';sound.knock();}});}
function playRecording(){if(!power){say('The player has no power. Check the wall circuits and breakers.',5);return;}if(!found.has('tape')){say('There is no tape in the player.',3);return;}recording=true;updateObjective();sound.play?.('recording');openDialog('recording','CASSETTE / RECOVERED AUDIO','“Take this outside.”',`<p>“The children found the service passage. The smiling walls turn, and the thing follows the corridors. Turn a wall behind you.”</p><p class="clue">“At the emergency exit:<br>LEFT handle, RIGHT handle, then the MIDDLE.”</p><p>“Take this tape outside. Do not leave it here.”</p><small>The sequence has been copied into your field notes.</small>`,[['STOP THE TAPE',hideDialog]]);}
function drawRelease(){if(phase!=='chase'||jamSolved)return;release=[0,0,0];releaseLeft=15;openDialog('release','EMERGENCY / MECHANICAL RELEASE','The passage is jammed',`<p>Three rotating indicators control the release. The service card had the sequence. You have fifteen seconds before the mechanism slips.</p><div class="switches">${release.map((_,i)=>`<button data-wheel="${i}">☀ SUN</button>`).join('')}</div><p class="puzzle-status" id="pstatus">15 seconds · The shutdown timer is still running.</p><small>J or NOTES opens your collected clues. Closing this panel lets you move again.</small>`,[['PULL RELEASE',()=>{if(release.every((v,i)=>v===RELEASE_ORDER[i])){jamSolved=true;world.jam.visible=false;hideDialog();updateObjective();sound.grind();say('The passage is open. Get to the southwest service exit.',6);}else{release=[0,0,0];updateWheels();noise=4;sound.knock();$('pstatus').textContent='Wrong alignment. The mechanism rattles.';}}]]);document.querySelectorAll('[data-wheel]').forEach(b=>b.onclick=()=>{const i=+b.dataset.wheel;release[i]=(release[i]+1)%3;updateWheels();sound.tick();});}
function updateWheels(){document.querySelectorAll('[data-wheel]').forEach((b,i)=>b.textContent=['☀ SUN','☾ MOON','✦ STAR'][release[i]]);}
function drawExit(){if(phase!=='chase'){openDialog('exit','CONCEALED / SERVICE EXIT','An emergency-only door','<p>A narrow service door behind the painted walls. Its three handles are locked into a release mechanism. The indicator reads: EMERGENCY CIRCUIT OFFLINE.</p><small>Remember where this is. It may be another way outside.</small>');return;}exitProgress=0;openDialog('exit','EMERGENCY / FINAL RELEASE','One more door',`<p>The exit has three handles. The cassette described their order. Pull carefully. The creature is still coming.</p><div class="switches">${['LEFT','MIDDLE','RIGHT'].map((s,i)=>`<button data-handle="${i}">${s}</button>`).join('')}</div><p class="puzzle-status" id="pstatus">0 / 3 catches released</p>`,[]);document.querySelectorAll('[data-handle]').forEach(b=>b.onclick=()=>{if(+b.dataset.handle===EXIT_ORDER[exitProgress]){exitProgress++;sound.tick();$('pstatus').textContent=`${exitProgress} / 3 catches released`;if(exitProgress===3)startRide();}else{exitProgress=0;noise=4;sound.knock();$('pstatus').textContent='Wrong handle. The catches locked again.';}});}
function interact(o=near){if(!o||!isActive()||dialog)return;if(o.type==='gate')return turnGate(o.index);if(o.type==='evidence'){if(found.has(o.id))return;const e=EVIDENCE.find(e=>e.id===o.id);found.add(e.id);suspense.milestone(e.id);updateObjective();sound.tick();openDialog('evidence','EVIDENCE / '+found.size+' OF 3',e.title,`<p>${e.text}</p><p class="clue">${e.note}</p><small>Added to your field notes. J / NOTES to read again.</small>`);return;}if(o.type==='power'){if(power){say('The circuit is running.',3);return;}drawPower();}if(o.type==='recording')playRecording();if(o.type==='phone'){if(!recording){say('The line is dead.',3);return;}openDialog('phone','INCOMING CALL / UNKNOWN','The line was disconnected.','<p>The receiver trembles against its cradle. Somewhere in the attraction, heavy machinery starts to move.</p>',[['PICK UP THE RECEIVER',startChase]]);}if(o.type==='release')drawRelease();if(o.type==='exit')drawExit();}
function obstruction(a,b){const blockers=[...world.collision,...gateBoxes()];if(world.jam.visible)blockers.push({x:4*SIZE,z:3.5*SIZE,w:SIZE,d:.14,h:3.2});const dx=b.x-a.x,dz=b.z-a.z,n=Math.ceil(Math.hypot(dx,dz)/.15);for(let i=1;i<n;i++){const x=a.x+dx*i/n,z=a.z+dz*i/n;if(blockers.some(w=>Math.abs(x-w.x)<w.w/2&&Math.abs(z-w.z)<w.d/2&&(w.h??3.2)>((a.y??1.65)+((b.y??1.65)-(a.y??1.65))*i/n)))return true;}return false;}
function findInteraction(){near=null;let best=-Infinity;const forward=new THREE.Vector3();camera.getWorldDirection(forward);for(const o of world.interactables){if(o.type==='evidence'&&found.has(o.id))continue;if(o.type==='release'&&(phase!=='chase'||jamSolved))continue;if(o.type==='phone'&&phase==='chase')continue;const delta=o.position.clone().sub(camera.position),dist=delta.length();if(dist>2.45)continue;const dot=forward.dot(delta.normalize());if(dot<.60||obstruction(player,o.position))continue;const score=dot*3-dist*.18;if(score>best){near=o;best=score;}}
 show('interact',!!near&&!dialog);if(near){$('interact').querySelector('span').textContent=near.type==='gate'?near.name+' · '+(gates[near.index]?'south':'east')+' open':near.name;$('use').textContent=near.type==='gate'?'TURN':'USE';}else $('use').textContent='USE';$('use').disabled=!near;$('danger').textContent='SOMETHING IS CLOSE';}
function updateMonster(dt){if(grace>0){grace-=dt;return;}world.creature.visible=true;const visible=Math.hypot(player.x-monster.x,player.z-monster.z)<12&&!obstruction(monster,player);mind.step(dt,{position:monster,player,visible,gates});const destination=mind.target;if(!destination)return;const goal=cellAt(destination.x,destination.z),current=cellAt(monster.x,monster.z),routeKey=goal;if(routeKey!==mindRevision){monster.target=null;monster.route=[];mindRevision=routeKey;}
 if(!monster.target){const center=point(current);const p=pathfind(current,goal,gates);if(Math.hypot(center.x-monster.x,center.z-monster.z)>.16&&current!==goal){monster.target=center;}else if(p.length>1){monster.route=p;monster.target=point(p[1]);}else if(current===goal){monster.target={...destination};}else return;}
 const aim=monster.target,dx=aim.x-monster.x,dz=aim.z-monster.z,dist=Math.hypot(dx,dz),speed=mind.mode==='pursue'?2.6:mind.mode==='search'?1.65:2.25;
 if(dist<.12){monster.target=null;return;}const step=Math.min(dist,dt*speed),nx=monster.x+dx/dist*step,nz=monster.z+dz/dist*step;
 // Navigation steers through tile centers; collision stops it crossing a newly turned wall.
 if(!collides(nx,nz,.19)){monster.x=nx;monster.z=nz;}else{monster.target=point(current);if(Math.hypot(monster.x-monster.target.x,monster.z-monster.target.z)<.2)monster.target=null;}
 world.creature.position.set(monster.x,Math.sin(elapsed*6)*.023,monster.z);world.creature.rotation.y=Math.atan2(dx,dz);world.creature.rotation.z=Math.sin(elapsed*3)*.025;
 if(Math.hypot(player.x-monster.x,player.z-monster.z)<.66&&!obstruction(player,monster))finish(false);
}
function update(dt,raw){screenTime+=dt;if(!started){camera.position.set(.1,1.67,-.50);camera.rotation.set(-.025,Math.PI+.12+Math.sin(screenTime*.11)*.12,0);return;}if(!isActive())return;if(phase==='ride'){updateRide(dt,raw);return;}elapsed+=dt;noise=Math.max(0,noise-dt);subtitleTime-=dt;if(subtitleTime<=0)$('subtitle').textContent='';
 let moving=false,sprinting=false;if(!dialog){yaw+=(Number(keys.has('ArrowLeft'))-Number(keys.has('ArrowRight')))*dt*1.75;pitch+=((keys.has('PageUp')?1:0)-(keys.has('PageDown')?1:0))*dt;pitch=Math.max(-1.15,Math.min(1.15,pitch));let f=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-stick.y;let r=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+stick.x;const len=Math.hypot(f,r);if(len>0){f/=Math.max(1,len);r/=Math.max(1,len);sprinting=(keys.has('ShiftLeft')||keys.has('ShiftRight')||input.run)&&stamina>.035;const speed=sprinting?3.6:2.15;const dx=(-Math.sin(yaw)*f+Math.cos(yaw)*r)*speed*dt,dz=(-Math.cos(yaw)*f-Math.sin(yaw)*r)*speed*dt;const old={...player};if(!collides(player.x+dx,player.z))player.x+=dx;if(!collides(player.x,player.z+dz))player.z+=dz;const travel=Math.hypot(player.x-old.x,player.z-old.z);moved+=travel;moving=travel>.0001;}stamina=Math.max(0,Math.min(1,stamina+(sprinting&&moving?-.20:.12)*dt));}
 const suspenseBusy=!!dialog||sound.sources.has('recording')||sound.sources.has('phoneVoice');const event=suspense.step(dt,{busy:suspenseBusy});if(event){sound.creak();glimpsePosition={x:player.x-Math.sin(yaw)*3.4+Math.cos(yaw)*.7,z:player.z-Math.cos(yaw)*3.4-Math.sin(yaw)*.7,yaw};}world.setSuspense(suspenseBusy?null:suspense.active,glimpsePosition);
 camera.position.set(player.x,1.65+(moving?Math.sin(elapsed*(sprinting?15:9))*.026:Math.sin(elapsed*1.1)*.004),player.z);camera.rotation.set(pitch,yaw,0);camera.fov=THREE.MathUtils.lerp(camera.fov,sprinting?74:70,Math.min(1,dt*5));camera.updateProjectionMatrix();
 for(let i=0;i<3;i++){rotations[i]=Math.max(0,rotations[i]-dt);world.gateMeshes[i].rotation.y=rotations[i]===0?(gates[i]?-Math.PI/2:0):THREE.MathUtils.lerp(world.gateMeshes[i].rotation.y,gates[i]?-Math.PI/2:0,Math.min(1,dt*8));}
 if(phase==='chase'){if(sprinting&&moving&&elapsed>=nextFootNoise){mind.hear(monster,player,gates,11,'running');nextFootNoise=elapsed+.8;}world.shutter.position.y=THREE.MathUtils.lerp(world.shutter.position.y,1.58,Math.min(1,dt*5));timeLeft=Math.max(0,timeLeft-raw);if(timeLeft===0)finish(false);else updateMonster(dt);if(dialog==='release'){releaseLeft-=raw;if(releaseLeft<=0){release=[0,0,0];releaseLeft=15;updateWheels();sound.knock();noise=3;}const e=$('pstatus');if(e)e.textContent=`${Math.ceil(releaseLeft)} seconds · ${Math.ceil(timeLeft)} until shutdown`;}}
 const distance=Math.hypot(player.x-monster.x,player.z-monster.z);show('danger',phase==='chase'&&grace<=0&&distance<7);$('time').textContent=`${Math.floor(Math.ceil(timeLeft)/60).toString().padStart(2,'0')}:${(Math.ceil(timeLeft)%60).toString().padStart(2,'0')}`;$('stamina').firstElementChild.style.width=`${stamina*100}%`;
 const monsterActive=phase==='chase'&&grace<=0&&!ending,clear=monsterActive&&!obstruction(player,monster);
 sound.monster(elapsed,monsterActive,distance,((monster.x-player.x)*Math.cos(yaw)-(monster.z-player.z)*Math.sin(yaw))/Math.max(.1,distance),!clear);
 if(monsterActive)world.updateCreature(elapsed,dt,{distance,clear,laughing:sound.sources.has('monsterLaugh'),grunting:sound.sources.has('monsterGrunt')});
 sound.update(elapsed,moving,sprinting,phase==='chase'&&grace<=0,distance,recording&&phase!=='chase'&&!dialog);findInteraction();show('click-look',!touch&&!document.pointerLockElement&&!dialog&&!paused);
}
// Touch controls use separate pointers for movement, looking, and running.
const t=document.createElement('div');t.id='touch';t.className='hidden';t.innerHTML='<div id="look" aria-label="Drag to look"></div><div id="stick" aria-label="Drag to move"><i></i><span>MOVE</span></div><button id="use">USE</button><button id="run">RUN</button><button id="notes">NOTES</button><button id="pause-touch" aria-label="Pause">Ⅱ</button>';document.body.append(t);
$('stick').addEventListener('pointerdown',e=>{if(dialog||paused)return;input.stickId=e.pointerId;const r=$('stick').getBoundingClientRect();input.cx=r.x+r.width/2;input.cy=r.y+r.height/2;$('stick').setPointerCapture(e.pointerId);updateStick(e);});function updateStick(e){if(e.pointerId!==input.stickId)return;const dx=(e.clientX-input.cx)/42,dy=(e.clientY-input.cy)/42,n=Math.max(1,Math.hypot(dx,dy));stick.x=dx/n;stick.y=dy/n;$('stick').querySelector('i').style.transform=`translate(${stick.x*28}px,${stick.y*28}px)`;}
$('stick').addEventListener('pointermove',updateStick);for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(ev,()=>{input.stickId=null;stick.x=stick.y=0;$('stick').querySelector('i').style.transform='';});
$('look').addEventListener('pointerdown',e=>{if(dialog||paused)return;input.lookId=e.pointerId;input.lastX=e.clientX;input.lastY=e.clientY;$('look').setPointerCapture(e.pointerId);});$('look').addEventListener('pointermove',e=>{if(e.pointerId!==input.lookId||dialog||paused)return;yaw-=(e.clientX-input.lastX)*.005;pitch-= (e.clientY-input.lastY)*.004;pitch=Math.max(-1.15,Math.min(1.15,pitch));input.lastX=e.clientX;input.lastY=e.clientY;});for(const ev of ['pointerup','pointercancel'])$('look').addEventListener(ev,()=>input.lookId=null);
$('use').onclick=()=>{if(phase!=='ride')interact();};$('use').addEventListener('pointerdown',e=>{if(phase==='ride'){input.brake=true;$('use').setPointerCapture(e.pointerId);}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('use').addEventListener(ev,()=>input.brake=false);$('notes').onclick=()=>dialog?hideDialog():journal();$('pause-touch').onclick=pause;$('run').addEventListener('pointerdown',e=>{input.run=true;$('run').setPointerCapture(e.pointerId);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('run').addEventListener(ev,()=>input.run=false);
$('begin').onclick=begin;$('retry').onclick=begin;$('checkpoint').onclick=retryCheckpoint;$('close-dialog').onclick=hideDialog;$('resume').onclick=resume;
function toggleSound(){sound.toggle();$('sound').textContent=sound.enabled?'SOUND ON':'SOUND OFF';$('sound').setAttribute('aria-pressed',String(!sound.enabled));}$('sound').onclick=toggleSound;$('pause-sound').onclick=toggleSound;
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(dialog){hideDialog();pause();}else if(paused)resume();else pause();return;}if(e.repeat)return;if(e.code==='KeyJ'&&isActive()){if(dialog==='notes')hideDialog();else journal();return;}if(e.code==='KeyE'&&isActive()&&phase!=='ride'){if(dialog==='evidence')hideDialog();else interact();return;}keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));
renderer.domElement.addEventListener('pointerdown',e=>{if(isActive()&&!dialog){lock();input.drag=true;input.lastX=e.clientX;input.lastY=e.clientY;}});window.addEventListener('pointerup',()=>input.drag=false);window.addEventListener('mousemove',e=>{if(!isActive()||dialog||touch)return;if(document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.0025;pitch-=e.movementY*.0025;}else if(input.drag){yaw-=(e.clientX-input.lastX)*.004;pitch-=(e.clientY-input.lastY)*.004;input.lastX=e.clientX;input.lastY=e.clientY;}pitch=Math.max(-1.15,Math.min(1.15,pitch));});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',()=>{if(isActive())pause();});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
let last=performance.now(),frameCount=0,fps=0,fpsWindow=0;
async function init(){try{await document.fonts.load('16px "Special Elite"');await sound.load();world=await buildWorld(mazeRoot);world.shutter.visible=false;gates.forEach((v,i)=>world.gateMeshes[i].rotation.y=v?-Math.PI/2:0);show('loading',false);show('menu');window.__READY__=true;window.__START__=begin;renderer.setAnimationLoop(now=>{const raw=(now-last)/1000;last=now;const dt=Math.min(raw,.05);frameCount++;fpsWindow+=raw;if(fpsWindow>.5){fps=frameCount/fpsWindow;frameCount=0;fpsWindow=0;}update(dt,raw);if(mazeRoot.visible){if(!started||isActive()){world.updateAtmosphere(started?elapsed:screenTime,dt);world.updateGaze(camera);}world.mirrors.updateForCamera(camera);}renderer.info.reset();renderer.render(scene,camera);window.__GAME__={pos:[player.x,player.z],yaw,pitch,fps,speed:isActive()&&!dialog?moved/Math.max(raw,.0001):0,score:found.size,over:ending,draws:renderer.info.render.calls,tris:renderer.info.render.triangles,phase,paused,dialog,ride:ride?rideSnapshot(ride):null,park:ride?park.state():null,gates:[...gates],rotating:[...rotations],found:[...found],power,recording,jamSolved,timeLeft,grace,monster:[monster.x,monster.z],investigation:mind.snapshot(),suspense:suspense.snapshot(),atmosphere:world.atmosphereState(),monsterLaugh:sound.sources.has('monsterLaugh'),monsterGrunt:sound.sources.has('monsterGrunt'),monsterBreath:sound.sources.has('monsterBreath'),viewRight:[camera.matrixWorld.elements[0],camera.matrixWorld.elements[2]],audioState:sound.ctx?.state||'locked',near:near?.id||null,evidenceVisible:Object.fromEntries(Object.entries(world.evidenceMeshes).map(([id,o])=>[id,o.visible])),mirrors:world.mirrors.map(m=>({id:m.userData.id,mode:m.userData.mode,updates:m.userData.updates})),ready:true};moved=0;});}catch(e){console.error(e);$('loadtext').textContent='The attraction could not load. Please refresh. '+e.message;}}
init();
